In [ ]:
import pandas as pd

# Replace 'file_path' with the path to your CSV file
df = pd.read_csv('../prediction_output/PTS_outputs/PTS_output_2025-03-15.csv')

df[['First', 'Second', 'Third']] = df['PTS'].str.split(' - ', expand=True).astype(int)

df= df.drop(columns=['recentgames_PTS', 'PTS'])

# display(df)


df_box = pd. read_csv("../../../box_score_data/box_score_csv/chi-vs-hou_content_3-15-25.csv")

df_box = df_box[['PLAYER','PTS']]


merged_df = pd.merge(df_box, df, left_on='PLAYER', right_on='Player')

# Creates a new column 'first_comparsion' that will be 1 if either:
# 1. 'First' is not 0, OR
# 2. 'PTS' is less than 'First'.
# Otherwise, it will be 0.
merged_df['first_comparsion'] = ((merged_df["First"] != 0) | (merged_df['PTS'] < merged_df['First'])).astype(int)


# Creates a new column 'second_comparsion' that will be 1 if both:
# 1. 'Second' is not 0, AND
# 2. 'Second' is less than or equal to 'PTS'.
# Otherwise, it will be 0.
merged_df['second_comparsion'] = ((merged_df["Second"] != 0) & (merged_df['Second'] <= merged_df['PTS'])).astype(int)


merged_df['third_comparsion'] = ((merged_df["Third"] != 0) & (merged_df['Third'] <= merged_df['PTS'])).astype(int)


# Calculate the proportion of 1's in each comparison column
first_comparison_proportion = round(merged_df['first_comparsion'].sum() / len(merged_df) * 100, 2)
second_comparison_proportion = round(merged_df['second_comparsion'].sum() / len(merged_df) * 100, 2)
third_comparison_proportion = round(merged_df['third_comparsion'].sum() / len(merged_df) * 100, 2)

# Print the results
print(f"Proportion of 1's in first_comparsion: {first_comparison_proportion}")
print(f"Proportion of 1's in second_comparsion: {second_comparison_proportion}")
print(f"Proportion of 1's in third_comparsion: {third_comparison_proportion}")


import pandas as pd

# Create a dictionary with the calculated proportions
new_row = {
    'PLAYER': 'Proportions',  # Label for the new row
    'PTS': 0,  # Set as 0 or another placeholder value for 'PTS'
    'Player': '',  # Set as an empty string or another placeholder for 'Player'
    'team': '',  # Set as an empty string or another placeholder for 'team'
    'confidence_level_PTS': 0,  # Set as 0 or another placeholder for 'confidence_level_PTS'
    'First': 0,  # Set as 0 or another placeholder for 'First'
    'Second': 0,  # Set as 0 or another placeholder for 'Second'
    'Third': 0,  # Set as 0 or another placeholder for 'Third'
    'first_comparsion': first_comparison_proportion.astype(int),  # Proportion for first_comparsion
    'second_comparsion': second_comparison_proportion.astype(int),  # Proportion for second_comparsion
    'third_comparsion': third_comparison_proportion.astype(int)  # Proportion for third_comparsion
}

# Convert the dictionary to a DataFrame with a single row
new_row_df = pd.DataFrame([new_row])

# Concatenate the new row to the original DataFrame
merged_df = pd.concat([merged_df, new_row_df], ignore_index=True)

# Print the updated DataFrame








display(merged_df)

In [ ]:
import pandas as pd

prediction_files =[]
box_score_files = []

def accuracy_checker(prediction_files,box_score_files):


    df = pd.read_csv(prediction_files)

    df[['First', 'Second', 'Third']] = df['PTS'].str.split(' - ', expand=True).astype(int)

    df= df.drop(columns=['recentgames_PTS', 'PTS'])

    for file_name_box_score in box_score_files:
        df = pd.read_csv(file_name_box_score)
        df_box = df_box[['PLAYER','PTS']]

    merged_df = pd.merge(df_box, df, left_on='PLAYER', right_on='Player')

    # Creates a new column 'first_comparsion' that will be 1 if either:
    # 1. 'First' is not 0, OR
    # 2. 'PTS' is less than 'First'.
    # Otherwise, it will be 0.
    merged_df['first_comparsion'] = ((merged_df["First"] != 0) | (merged_df['PTS'] < merged_df['First'])).astype(int)


    # Creates a new column 'second_comparsion' that will be 1 if both:
    # 1. 'Second' is not 0, AND
    # 2. 'Second' is less than or equal to 'PTS'.
    # Otherwise, it will be 0.
    merged_df['second_comparsion'] = ((merged_df["Second"] != 0) & (merged_df['Second'] <= merged_df['PTS'])).astype(int)


    merged_df['third_comparsion'] = ((merged_df["Third"] != 0) & (merged_df['Third'] <= merged_df['PTS'])).astype(int)


    # Calculate the proportion of 1's in each comparison column
    first_comparison_proportion = round(merged_df['first_comparsion'].sum() / len(merged_df) * 100, 2)
    second_comparison_proportion = round(merged_df['second_comparsion'].sum() / len(merged_df) * 100, 2)
    third_comparison_proportion = round(merged_df['third_comparsion'].sum() / len(merged_df) * 100, 2)

    # Print the results
    print(f"Proportion of 1's in first_comparsion: {first_comparison_proportion}")
    print(f"Proportion of 1's in second_comparsion: {second_comparison_proportion}")
    print(f"Proportion of 1's in third_comparsion: {third_comparison_proportion}")


    import pandas as pd

    # Create a dictionary with the calculated proportions
    new_row = {
        'PLAYER': 'Proportions',  # Label for the new row
        'PTS': 0,  # Set as 0 or another placeholder value for 'PTS'
        'Player': '',  # Set as an empty string or another placeholder for 'Player'
        'team': '',  # Set as an empty string or another placeholder for 'team'
        'confidence_level_PTS': 0,  # Set as 0 or another placeholder for 'confidence_level_PTS'
        'First': 0,  # Set as 0 or another placeholder for 'First'
        'Second': 0,  # Set as 0 or another placeholder for 'Second'
        'Third': 0,  # Set as 0 or another placeholder for 'Third'
        'first_comparsion': first_comparison_proportion.astype(int),  # Proportion for first_comparsion
        'second_comparsion': second_comparison_proportion.astype(int),  # Proportion for second_comparsion
        'third_comparsion': third_comparison_proportion.astype(int)  # Proportion for third_comparsion
    }

    # Convert the dictionary to a DataFrame with a single row
    new_row_df = pd.DataFrame([new_row])

    # Concatenate the new row to the original DataFrame
    merged_df = pd.concat([merged_df, new_row_df], ignore_index=True)

In [148]:
import pandas as pd
import os

def accuracy_checker(prediction_files, box_score_files, target):

    df = pd.read_csv(prediction_files)
    df[['First', 'Second', 'Third']] = df[target].str.split(' - ', expand=True).astype(int)

    # Check if 'First', 'Second', and 'Third' are all zero, but keep 'First' as is if it is greater than zero
    df['First'] = df.apply(lambda row: 0 if (row['First'] == 0 and row['Second'] == 0 and row['Third'] == 0) else (row['First'] if row['First'] > 0 else 1), axis=1)


    df = df.drop(columns=[f'recentgames_{target}', target])

    # Initialize an empty list to store the dataframes for each box score file
    df_box_list = []

    # Get all files in the box_score_folder_path
    for file_name in os.listdir(box_score_files):
        # Only process files that end with '.csv'
        if file_name.endswith('.csv'):
            file_path = os.path.join(box_score_files, file_name)
            df_box = pd.read_csv(file_path)
            df_box = df_box[['PLAYER', target]]  # Select the necessary columns
            df_box_7 = df_box.head(7)
            next_box = df_box.iloc[15:22]
            df_box = pd.concat([df_box_7, next_box], ignore_index=True)
            # display(df_box)
            df_box_list.append(df_box)  # Append the df_box DataFrame to the list

    # Concatenate all the box score dataframes into one
    df_box_combined = pd.concat(df_box_list, ignore_index=True)

    # Merge the combined box score dataframe with the prediction dataframe
    merged_df = pd.merge(df_box_combined, df, left_on='PLAYER', right_on='Player')
    merged_df = merged_df.dropna()
    merged_df = merged_df[~merged_df['PLAYER'].str.contains('DNP|DND', na=False)]

    # Creates new comparison columns
    # merged_df['first_comparsion'] = (~((merged_df[target] < merged_df['First']) | ((merged_df['First'] == 0) & (merged_df[target] > 0)))).astype(int)
    # merged_df['second_comparsion'] = (~((merged_df[target] < merged_df['Second']) | ((merged_df['Second'] == 0) & (merged_df[target] > 0)))).astype(int)
    # merged_df['third_comparsion'] = (~((merged_df[target] < merged_df['Third']) | ((merged_df['Third'] == 0) & (merged_df[target] > 0)))).astype(int)

    # merged_df['first_comparsion'] = ((merged_df['First'] == 0) & (merged_df[target] >= 0) | (merged_df[target] >= merged_df['First'])).astype(int)
    # merged_df['second_comparsion'] = ((merged_df['Second'] == 0) & (merged_df[target] >= 0) | (merged_df[target] >= merged_df['Second'])).astype(int)
    # merged_df['third_comparsion'] = ((merged_df['Third'] == 0) & (merged_df[target] >= 0) | (merged_df[target] >= merged_df['Third'])).astype(int)


    merged_df['first_comparsion'] = (~((merged_df[target] < merged_df['First']) | ((merged_df['First'] == 0) & (merged_df[target] > 0)))).astype(int)

    merged_df['second_comparsion'] = (~((merged_df[target] < merged_df['Second']) |  ((merged_df['Second'] == 0) & (merged_df[target] > 0)))).astype(int)

    merged_df['third_comparsion'] = (~((merged_df[target] < merged_df['Third']) |   ((merged_df['Third'] == 0) & (merged_df[target] > 0)))).astype(int)

    # Set to 0 when all First, Second, Third are 0 and target > 0
    condition = (merged_df['First'] == 0) & (merged_df['Second'] == 0) & (merged_df['Third'] == 0) & (merged_df[target] > 0)
    merged_df.loc[condition, ['first_comparsion', 'second_comparsion', 'third_comparsion']] = 0








    # merged_df['second_comparsion'] = ((merged_df["Second"] != 0) & (merged_df['Second'] <= merged_df[target])).astype(int)
    # merged_df['third_comparsion'] = ((merged_df["Third"] != 0) & (merged_df['Third'] <= merged_df[target])).astype(int)

    # Calculate the proportion of 1's in each comparison column
    first_comparison_proportion = round(merged_df['first_comparsion'].sum() / len(merged_df) * 100, 2)
    second_comparison_proportion = round(merged_df['second_comparsion'].sum() / len(merged_df) * 100, 2)
    third_comparison_proportion = round(merged_df['third_comparsion'].sum() / len(merged_df) * 100, 2)

    # Print the results
    print(f"Proportion of 1's in first_comparsion: {first_comparison_proportion}")
    print(f"Proportion of 1's in second_comparsion: {second_comparison_proportion}")
    print(f"Proportion of 1's in third_comparsion: {third_comparison_proportion}")

    # Create a dictionary with the calculated proportions
    new_row = {
        'PLAYER': 'Proportions',
        target: 0,
        'Player': '',
        'team': '',
        f'confidence_level_{target}': 0,
        'First': 0,
        'Second': 0,
        'Third': 0,
        'first_comparsion': first_comparison_proportion,
        'second_comparsion': second_comparison_proportion,
        'third_comparsion': third_comparison_proportion
    }

    # Convert the dictionary to a DataFrame with a single row
    new_row_df = pd.DataFrame([new_row])

    # Concatenate the new row to the original DataFrame
    merged_df = pd.concat([merged_df, new_row_df], ignore_index=True)

    pd.set_option('display.max_rows', 1000)  # Maximum number of rows to display
    pd.set_option('display.max_columns', None)  # Show all columns
    pd.set_option('display.width', 1000)  # Adjust column width for better readability


    # Print the updated DataFrame
    return merged_df

In [ ]:
target = '3PM'
prediction_date = ""
prediction_file = f'../prediction_output/{target}_outputs/{target}_output_2025-03-16.csv'
box_score_file = f"../../../box_score_data/box_score_csv/matchup_3-16-25"


accuracy_checker(prediction_file,box_score_file,target)

In [150]:
target = '3PM'
box_dates = [ "3-23-25", "3-24-25", "3-25-25", "3-26-25", "3-27-25", "3-28-25","3-31-25"]
prediction_dates = [  "2025-03-23", "2025-03-24",  "2025-03-25",  "2025-03-26",  "2025-03-27",  "2025-03-28", "2025-03-31"]

# Create lists of file paths
prediction_files = [f'../prediction_output/{target}_outputs/{target}_output_{prediction_date}.csv' for prediction_date in prediction_dates]
box_score_files = [f"../../../box_score_data/box_score_csv/matchup_{box_date}" for box_date in box_dates]

# Loop through each pair of files and process
for p_file, b_file in zip(prediction_files, box_score_files):
    df = accuracy_checker(p_file, b_file, target)
    display(df.head(2))

Proportion of 1's in first_comparsion: 85.71
Proportion of 1's in second_comparsion: 57.14
Proportion of 1's in third_comparsion: 42.86

               PLAYER  3PM              Player team  confidence_level_3PM  First  Second  Third  first_comparsion  second_comparsion  third_comparsion
0       Luguentz Dort  2.0       Luguentz Dort  OKC                  2.62      1       3      5               1.0                0.0               0.0
1  Isaiah Hartenstein  0.0  Isaiah Hartenstein  OKC                100.00      0       0      0               1.0                1.0               1.0

Proportion of 1's in first_comparsion: 67.65
Proportion of 1's in second_comparsion: 57.35
Proportion of 1's in third_comparsion: 47.06

         PLAYER  3PM        Player team  confidence_level_3PM  First  Second  Third  first_comparsion  second_comparsion  third_comparsion
0  Jaylen Brown  1.0  Jaylen Brown  BOS                 12.50      0       0      0               0.0                0.0               0.0
1  Jayson Tatum  5.0  Jayson Tatum  BOS                 55.48      1       1      1               1.0                1.0               1.0

Proportion of 1's in first_comparsion: 66.67
Proportion of 1's in second_comparsion: 53.7
Proportion of 1's in third_comparsion: 48.15

               PLAYER  3PM              Player team  confidence_level_3PM  First  Second  Third  first_comparsion  second_comparsion  third_comparsion
0  Zaccharie Risacher  0.0  Zaccharie Risacher  ATL                 36.40      1       2      3               0.0                0.0               0.0
1      Mouhamed Gueye  0.0      Mouhamed Gueye  ATL                 15.04      0       0      0               1.0                1.0               1.0

Proportion of 1's in first_comparsion: 68.29
Proportion of 1's in second_comparsion: 53.66
Proportion of 1's in third_comparsion: 48.78

               PLAYER  3PM              Player team  confidence_level_3PM  First  Second  Third  first_comparsion  second_comparsion  third_comparsion
0        Jaylen Brown  4.0        Jaylen Brown  BOS                  9.52      1       4      7               1.0                1.0               0.0
1  Kristaps Porzingis  4.0  Kristaps Porzingis  BOS                 35.76      1       2      3               1.0                1.0               1.0

Proportion of 1's in first_comparsion: 70.15
Proportion of 1's in second_comparsion: 58.21
Proportion of 1's in third_comparsion: 41.79

               PLAYER  3PM              Player team  confidence_level_3PM  First  Second  Third  first_comparsion  second_comparsion  third_comparsion
0  Zaccharie Risacher  1.0  Zaccharie Risacher  ATL                 32.05      1       1      1               1.0                1.0               1.0
1      Onyeka Okongwu  1.0      Onyeka Okongwu  ATL                 49.90      1       1      2               1.0                1.0               0.0

Proportion of 1's in first_comparsion: 74.51
Proportion of 1's in second_comparsion: 66.67
Proportion of 1's in third_comparsion: 50.98

          PLAYER  3PM         Player team  confidence_level_3PM  First  Second  Third  first_comparsion  second_comparsion  third_comparsion
0     Josh Green  0.0     Josh Green  CHA                 22.68      1       1      2               0.0                0.0               0.0
1  Miles Bridges  1.0  Miles Bridges  CHA                 38.84      0       0      0               0.0                0.0               0.0

Proportion of 1's in first_comparsion: 78.85
Proportion of 1's in second_comparsion: 67.31
Proportion of 1's in third_comparsion: 57.69

            PLAYER  3PM           Player team  confidence_level_3PM  First  Second  Third  first_comparsion  second_comparsion  third_comparsion
0     Jalen Wilson  2.0     Jalen Wilson  BKN                  6.15      1       1      1               1.0                1.0               1.0
1  Ziaire Williams  2.0  Ziaire Williams  BKN                 22.61      1       1      1               1.0                1.0               1.0