In [136]:
from prediction import prediction

import os
import pandas as pd

# List of target teams
matchup = ["NYK", "ATL","MEM","DET","MIN", "PHI", "MIL","MIA", "DAL", "LAC"]
df_list = []  # List to store DataFrames

# Loop through each team's roster file
for team in matchup:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path

    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Store DataFrame in list
    else:
        print(f"File not found: {roster_path}")  # Debugging message

# Combine all DataFrames if any were found
if df_list:
    df_combined = pd.concat(df_list, ignore_index=True)

    # Extract two columns as a dictionary
    player_dict = dict(zip(df_combined['PLAYER_uni'], df_combined['api_team_name']))

    print(player_dict)  # Display dictionary
else:
    print("No valid roster files found.")





# remember to run mover
# remember to check schedule csv
import pandas as pd
date_list = ["2023-24","2024-25"]
stats_path = {
    'usage_path':'D:/nba_usage_csv_historic/usage_csv_{date}/{date}_content.csv',
    'catch_shoot':"D:/nba_tracking_data_csv/nba_csv_{date}/catch_shoot_content.csv",
    'drives':"D:/nba_tracking_data_csv/nba_csv_{date}/drives_content.csv",
    'elbow_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/elbow_touch_content.csv",
    'paint_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/paint_touch_content.csv",
    'passing':"D:/nba_tracking_data_csv/nba_csv_{date}/passing_content.csv",
    'pullup':"D:/nba_tracking_data_csv/nba_csv_{date}/pullup_content.csv",
    'shooting_efficiency':"D:/nba_tracking_data_csv/nba_csv_{date}/shooting_efficiency_content.csv",
    'touches':"D:/nba_tracking_data_csv/nba_csv_{date}/touches_content.csv",
    'tracking_post_ups_content':"D:/nba_tracking_data_csv/nba_csv_{date}/tracking_post_ups_content.csv"
}
schedule_base_path = "D:/nba_scheduled_csv/schedule_csv_2025/{schedule_team}_schedule_content.csv"
player_base_path = "D:/nba_player_csv_historic/season_{date}/all_quarters/{player}_content.csv"
defense_base_path = "D:/nba_defense_history_csv/defense_csv_{date}/all_quarter_defense_content.csv"

results_reb = prediction(player_dict, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'REB','REB')
results_ast = prediction(player_dict, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'AST','AST')
results_pts = prediction(player_dict, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'PTS','PTS')
results_3pm = prediction(player_dict, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'3PM','3PM')
results_pts = results_pts.rename(columns={'FGA': 'PTS'})



# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

{'Delon Wright': 'NYK', 'MarJon Beauchamp': 'NYK', 'P.J. Tucker': 'NYK', 'Cameron Payne': 'NYK', 'Miles McBride': 'NYK', 'Josh Hart': 'NYK', 'Pacome Dadiet': 'NYK', 'Precious Achiuwa': 'NYK', 'OG Anunoby': 'NYK', 'Kevin McCullar Jr.': 'NYK', 'Jalen Brunson': 'NYK', 'Tyler Kolek': 'NYK', 'Mitchell Robinson': 'NYK', 'Mikal Bridges': 'NYK', 'Anton Watson': 'NYK', 'Karl-Anthony Towns': 'NYK', 'Landry Shamet': 'NYK', 'Ariel Hukporti': 'NYK', 'Jacob Toppin': 'ATL', 'Jalen Johnson': 'ATL', 'Keaton Wallace': 'ATL', 'Caris LeVert': 'ATL', 'Kobe Bufkin': 'ATL', 'Dyson Daniels': 'ATL', 'Zaccharie Risacher': 'ATL', 'Trae Young': 'ATL', 'Terance Mann': 'ATL', 'Clint Capela': 'ATL', 'Onyeka Okongwu': 'ATL', 'Mouhamed Gueye': 'ATL', 'Georges Niang': 'ATL', 'Larry Nance Jr.': 'ATL', 'Garrison Mathews': 'ATL', 'Dominick Barlow': 'ATL', 'Vit Krejci': 'ATL', 'Daeqwon Plowden': 'ATL', 'Zyon Pullin': 'MEM', 'Jaylen Wells': 'MEM', 'Scotty Pippen Jr.': 'MEM', 'Vince Williams Jr.': 'MEM', 'Santi Aldama': 'MEM', 'Lamar Stevens': 'MEM', 'Luke Kennard': 'MEM', 'Ja Morant': 'MEM', 'Jaren Jackson Jr.': 'MEM', 'Zach Edey': 'MEM', 'Brandon Clarke': 'MEM', 'Yuki Kawamura': 'MEM', 'Desmond Bane': 'MEM', 'Cam Spencer': 'MEM', 'Jay Huff': 'MEM', 'Marvin Bagley III': 'MEM', 'GG Jackson': 'MEM', 'John Konchar': 'MEM', 'Jalen Duren': 'DET', 'Ronald Holland II': 'DET', 'Cade Cunningham': 'DET', 'Malik Beasley': 'DET', 'Paul Reed': 'DET', 'Tim Hardaway Jr.': 'DET', 'Ausar Thompson': 'DET', 'Tobias Harris': 'DET', 'Ron Harper Jr.': 'DET', 'Dennis Schroder': 'DET', 'Simone Fontecchio': 'DET', 'Jaden Ivey': 'DET', 'Daniss Jenkins': 'DET', 'Marcus Sasser': 'DET', 'Isaiah Stewart': 'DET', 'Bobi Klintman': 'DET', 'Tolu Smith': 'DET', 'Lindy Waters III': 'DET', 'Terrence Shannon Jr.': 'MIN', 'Donte DiVincenzo': 'MIN', 'Jaden McDaniels': 'MIN', 'Rob Dillingham': 'MIN', 'Anthony Edwards': 'MIN', 'Joe Ingles': 'MIN', 'Josh Minott': 'MIN', 'Nickeil Alexander-Walker': 'MIN', 'Mike Conley': 'MIN', 'Naz Reid': 'MIN', 'Tristen Newton': 'MIN', 'Jesse Edwards': 'MIN', 'Jaylen Clark': 'MIN', 'Rudy Gobert': 'MIN', 'Julius Randle': 'MIN', 'Leonard Miller': 'MIN', 'Luka Garza': 'MIN', 'Bones Hyland': 'MIN', 'Phillip Wheeler': 'PHI', 'Tyrese Maxey': 'PHI', 'Andre Drummond': 'PHI', 'Quentin Grimes': 'PHI', 'Kyle Lowry': 'PHI', 'Paul George': 'PHI', 'Kelly Oubre Jr.': 'PHI', 'Jeff Dowtin Jr.': 'PHI', 'Colin Castleton': 'PHI', 'Jared Butler': 'PHI', 'Ricky Council IV': 'PHI', 'Lonnie Walker IV': 'PHI', 'Jalen Hood-Schifino': 'PHI', 'Justin Edwards': 'PHI', 'Jared McCain': 'PHI', 'Joel Embiid': 'PHI', 'Eric Gordon': 'PHI', 'Guerschon Yabusele': 'PHI', 'Adem Bona': 'PHI', 'Alex Reese': 'PHI', 'Damian Lillard': 'MIL', 'Jericho Sims': 'MIL', 'Kevin Porter Jr.': 'MIL', 'Gary Trent Jr.': 'MIL', 'Chris Livingston': 'MIL', 'Bobby Portis': 'MIL', 'Brook Lopez': 'MIL', 'Taurean Prince': 'MIL', 'Ryan Rollins': 'MIL', 'Jamaree Bouyea': 'MIL', 'Stanley Umude': 'MIL', 'Kyle Kuzma': 'MIL', 'AJ Green': 'MIL', 'Tyler Smith': 'MIL', 'Pat Connaughton': 'MIL', 'Giannis Antetokounmpo': 'MIL', 'Pete Nance': 'MIL', 'Andre Jackson Jr.': 'MIL', 'Isaiah Stevens': 'MIA', 'Terry Rozier': 'MIA', 'Nikola Jovic': 'MIA', "Kel'el Ware": 'MIA', 'Josh Christopher': 'MIA', 'Pelle Larsson': 'MIA', 'Jaime Jaquez Jr.': 'MIA', 'Dru Smith': 'MIA', 'Bam Adebayo': 'MIA', 'Tyler Herro': 'MIA', 'Keshad Johnson': 'MIA', 'Alec Burks': 'MIA', 'Kyle Anderson': 'MIA', 'Andrew Wiggins': 'MIA', 'Haywood Highsmith': 'MIA', 'Kevin Love': 'MIA', 'Davion Mitchell': 'MIA', 'Duncan Robinson': 'MIA', 'Dante Exum': 'DAL', 'Max Christie': 'DAL', 'Jaden Hardy': 'DAL', 'Dereck Lively II': 'DAL', 'Anthony Davis': 'DAL', 'Dwight Powell': 'DAL', 'Olivier-Maxence Prosper': 'DAL', 'Brandon Williams': 'DAL', 'Kyrie Irving': 'DAL', 'Naji Marshall': 'DAL', 'Caleb Martin': 'DAL', 'Kessler Edwards': 'DAL', 'Daniel Gafford': 'DAL', 'Kai Jones': 'DAL', 'P.J. Washington': 'DAL', 'Spencer Dinwiddie': 'DAL', 'Klay Thompson': 'DAL', 'James Harden': 'LAC', 'Kawhi Leonard': 'LAC', 'Seth Lundy': 'LAC', 'Amir Coffey': 'LAC', 'Kris Dunn': 'LAC', 'Trentyn Flowers': 'LAC', 'Bogdan Bogdanovic': 'LAC', 'Jordan Miller': 'LAC', 'Cam Christie': 'LAC', 'Drew Eubanks': 'LAC', 'Kobe Brown': 'LAC', 'Patrick Baldwin Jr.': 'LAC', 'Norman Powell': 'LAC', 'Ben Simmons': 'LAC', 'Nicolas Batum': 'LAC', 'Ivica Zubac': 'LAC', 'Derrick Jones Jr.': 'LAC', 'Patty Mills': 'LAC'}
Player data missing for Pacome Dadiet on 2023-24, skipping.
Skipping merge for Pacome Dadiet on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2023-24, skipping.
Skipping merge for Kevin McCullar Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2024-25, skipping.
Skipping merge for Kevin McCullar Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Kevin McCullar Jr. - No valid data found.
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Anton Watson on 2023-24, skipping.
Skipping merge for Anton Watson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ariel Hukporti on 2023-24, skipping.
Skipping merge for Ariel Hukporti on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keaton Wallace on 2023-24, skipping.
Skipping merge for Keaton Wallace on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zaccharie Risacher on 2023-24, skipping.
Skipping merge for Zaccharie Risacher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Daeqwon Plowden on 2023-24, skipping.
Skipping merge for Daeqwon Plowden on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zyon Pullin on 2023-24, skipping.
Skipping merge for Zyon Pullin on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yuki Kawamura on 2023-24, skipping.
Skipping merge for Yuki Kawamura on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cam Spencer on 2023-24, skipping.
Skipping merge for Cam Spencer on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ronald Holland II on 2023-24, skipping.
Skipping merge for Ronald Holland II on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2023-24, skipping.
Skipping merge for Ron Harper Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2024-25, skipping.
Skipping merge for Ron Harper Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Ron Harper Jr. - No valid data found.
Player data missing for Daniss Jenkins on 2023-24, skipping.
Skipping merge for Daniss Jenkins on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Bobi Klintman on 2023-24, skipping.
Skipping merge for Bobi Klintman on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2023-24, skipping.
Skipping merge for Tolu Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2024-25, skipping.
Skipping merge for Tolu Smith on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Tolu Smith - No valid data found.
Player data missing for Terrence Shannon Jr. on 2023-24, skipping.
Skipping merge for Terrence Shannon Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Rob Dillingham on 2023-24, skipping.
Skipping merge for Rob Dillingham on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tristen Newton on 2023-24, skipping.
Skipping merge for Tristen Newton on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jesse Edwards on 2023-24, skipping.
Skipping merge for Jesse Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Clark on 2023-24, skipping.
Skipping merge for Jaylen Clark on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Phillip Wheeler on 2023-24, skipping.
Skipping merge for Phillip Wheeler on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Edwards on 2023-24, skipping.
Skipping merge for Justin Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jared McCain on 2023-24, skipping.
Skipping merge for Jared McCain on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Guerschon Yabusele on 2023-24, skipping.
Skipping merge for Guerschon Yabusele on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Adem Bona on 2023-24, skipping.
Skipping merge for Adem Bona on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Reese on 2023-24, skipping.
Skipping merge for Alex Reese on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin Porter Jr. on 2023-24, skipping.
Skipping merge for Kevin Porter Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Smith on 2023-24, skipping.
Skipping merge for Tyler Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Stevens on 2023-24, skipping.
Skipping merge for Isaiah Stevens on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kel'el Ware on 2023-24, skipping.
Skipping merge for Kel'el Ware on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Josh Christopher on 2023-24, skipping.
Skipping merge for Josh Christopher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pelle Larsson on 2023-24, skipping.
Skipping merge for Pelle Larsson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keshad Johnson on 2023-24, skipping.
Skipping merge for Keshad Johnson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2023-24, skipping.
Skipping merge for Brandon Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2024-25, skipping.
Skipping merge for Brandon Williams on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Brandon Williams - No valid data found.
Player data missing for Kai Jones on 2023-24, skipping.
Skipping merge for Kai Jones on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Seth Lundy on 2024-25, skipping.
Skipping merge for Seth Lundy on 2024-25 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2023-24, skipping.
Skipping merge for Trentyn Flowers on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2024-25, skipping.
Skipping merge for Trentyn Flowers on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Trentyn Flowers - No valid data found.
Player data missing for Cam Christie on 2023-24, skipping.
Skipping merge for Cam Christie on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pacome Dadiet on 2023-24, skipping.
Skipping merge for Pacome Dadiet on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2023-24, skipping.
Skipping merge for Kevin McCullar Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2024-25, skipping.
Skipping merge for Kevin McCullar Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Kevin McCullar Jr. - No valid data found.
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Anton Watson on 2023-24, skipping.
Skipping merge for Anton Watson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ariel Hukporti on 2023-24, skipping.
Skipping merge for Ariel Hukporti on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keaton Wallace on 2023-24, skipping.
Skipping merge for Keaton Wallace on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zaccharie Risacher on 2023-24, skipping.
Skipping merge for Zaccharie Risacher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Daeqwon Plowden on 2023-24, skipping.
Skipping merge for Daeqwon Plowden on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zyon Pullin on 2023-24, skipping.
Skipping merge for Zyon Pullin on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yuki Kawamura on 2023-24, skipping.
Skipping merge for Yuki Kawamura on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cam Spencer on 2023-24, skipping.
Skipping merge for Cam Spencer on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ronald Holland II on 2023-24, skipping.
Skipping merge for Ronald Holland II on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2023-24, skipping.
Skipping merge for Ron Harper Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2024-25, skipping.
Skipping merge for Ron Harper Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Ron Harper Jr. - No valid data found.
Player data missing for Daniss Jenkins on 2023-24, skipping.
Skipping merge for Daniss Jenkins on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Bobi Klintman on 2023-24, skipping.
Skipping merge for Bobi Klintman on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2023-24, skipping.
Skipping merge for Tolu Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2024-25, skipping.
Skipping merge for Tolu Smith on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Tolu Smith - No valid data found.
Player data missing for Terrence Shannon Jr. on 2023-24, skipping.
Skipping merge for Terrence Shannon Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Rob Dillingham on 2023-24, skipping.
Skipping merge for Rob Dillingham on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tristen Newton on 2023-24, skipping.
Skipping merge for Tristen Newton on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jesse Edwards on 2023-24, skipping.
Skipping merge for Jesse Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Clark on 2023-24, skipping.
Skipping merge for Jaylen Clark on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Phillip Wheeler on 2023-24, skipping.
Skipping merge for Phillip Wheeler on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Edwards on 2023-24, skipping.
Skipping merge for Justin Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jared McCain on 2023-24, skipping.
Skipping merge for Jared McCain on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Guerschon Yabusele on 2023-24, skipping.
Skipping merge for Guerschon Yabusele on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Adem Bona on 2023-24, skipping.
Skipping merge for Adem Bona on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Reese on 2023-24, skipping.
Skipping merge for Alex Reese on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin Porter Jr. on 2023-24, skipping.
Skipping merge for Kevin Porter Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Smith on 2023-24, skipping.
Skipping merge for Tyler Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Stevens on 2023-24, skipping.
Skipping merge for Isaiah Stevens on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kel'el Ware on 2023-24, skipping.
Skipping merge for Kel'el Ware on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Josh Christopher on 2023-24, skipping.
Skipping merge for Josh Christopher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pelle Larsson on 2023-24, skipping.
Skipping merge for Pelle Larsson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keshad Johnson on 2023-24, skipping.
Skipping merge for Keshad Johnson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2023-24, skipping.
Skipping merge for Brandon Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2024-25, skipping.
Skipping merge for Brandon Williams on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Brandon Williams - No valid data found.
Player data missing for Kai Jones on 2023-24, skipping.
Skipping merge for Kai Jones on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Seth Lundy on 2024-25, skipping.
Skipping merge for Seth Lundy on 2024-25 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2023-24, skipping.
Skipping merge for Trentyn Flowers on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2024-25, skipping.
Skipping merge for Trentyn Flowers on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Trentyn Flowers - No valid data found.
Player data missing for Cam Christie on 2023-24, skipping.
Skipping merge for Cam Christie on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(

Skipping Daeqwon Plowden due to insufficient data (3 samples).
Skipping Zyon Pullin due to insufficient data (3 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

Skipping Jesse Edwards due to insufficient data (2 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(

Skipping Isaiah Stevens due to insufficient data (3 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(

Skipping Kevin McCullar Jr. - No data available.
No valid features found for Daeqwon Plowden for predicting REB
No valid features found for Zyon Pullin for predicting REB
Skipping Ron Harper Jr. - No data available.
Skipping Tolu Smith - No data available.
No valid features found for Jesse Edwards for predicting REB
No valid features found for Isaiah Stevens for predicting REB
Skipping Brandon Williams - No data available.
Skipping Trentyn Flowers - No data available.
Player data missing for Pacome Dadiet on 2023-24, skipping.
Skipping merge for Pacome Dadiet on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2023-24, skipping.
Skipping merge for Kevin McCullar Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2024-25, skipping.
Skipping merge for Kevin McCullar Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Kevin McCullar Jr. - No valid data found.
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Anton Watson on 2023-24, skipping.
Skipping merge for Anton Watson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ariel Hukporti on 2023-24, skipping.
Skipping merge for Ariel Hukporti on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keaton Wallace on 2023-24, skipping.
Skipping merge for Keaton Wallace on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zaccharie Risacher on 2023-24, skipping.
Skipping merge for Zaccharie Risacher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Daeqwon Plowden on 2023-24, skipping.
Skipping merge for Daeqwon Plowden on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zyon Pullin on 2023-24, skipping.
Skipping merge for Zyon Pullin on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yuki Kawamura on 2023-24, skipping.
Skipping merge for Yuki Kawamura on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cam Spencer on 2023-24, skipping.
Skipping merge for Cam Spencer on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ronald Holland II on 2023-24, skipping.
Skipping merge for Ronald Holland II on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2023-24, skipping.
Skipping merge for Ron Harper Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2024-25, skipping.
Skipping merge for Ron Harper Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Ron Harper Jr. - No valid data found.
Player data missing for Daniss Jenkins on 2023-24, skipping.
Skipping merge for Daniss Jenkins on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Bobi Klintman on 2023-24, skipping.
Skipping merge for Bobi Klintman on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2023-24, skipping.
Skipping merge for Tolu Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2024-25, skipping.
Skipping merge for Tolu Smith on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Tolu Smith - No valid data found.
Player data missing for Terrence Shannon Jr. on 2023-24, skipping.
Skipping merge for Terrence Shannon Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Rob Dillingham on 2023-24, skipping.
Skipping merge for Rob Dillingham on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tristen Newton on 2023-24, skipping.
Skipping merge for Tristen Newton on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jesse Edwards on 2023-24, skipping.
Skipping merge for Jesse Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Clark on 2023-24, skipping.
Skipping merge for Jaylen Clark on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Phillip Wheeler on 2023-24, skipping.
Skipping merge for Phillip Wheeler on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Edwards on 2023-24, skipping.
Skipping merge for Justin Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jared McCain on 2023-24, skipping.
Skipping merge for Jared McCain on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Guerschon Yabusele on 2023-24, skipping.
Skipping merge for Guerschon Yabusele on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Adem Bona on 2023-24, skipping.
Skipping merge for Adem Bona on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Reese on 2023-24, skipping.
Skipping merge for Alex Reese on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin Porter Jr. on 2023-24, skipping.
Skipping merge for Kevin Porter Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Smith on 2023-24, skipping.
Skipping merge for Tyler Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Stevens on 2023-24, skipping.
Skipping merge for Isaiah Stevens on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kel'el Ware on 2023-24, skipping.
Skipping merge for Kel'el Ware on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Josh Christopher on 2023-24, skipping.
Skipping merge for Josh Christopher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pelle Larsson on 2023-24, skipping.
Skipping merge for Pelle Larsson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keshad Johnson on 2023-24, skipping.
Skipping merge for Keshad Johnson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2023-24, skipping.
Skipping merge for Brandon Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2024-25, skipping.
Skipping merge for Brandon Williams on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Brandon Williams - No valid data found.
Player data missing for Kai Jones on 2023-24, skipping.
Skipping merge for Kai Jones on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Seth Lundy on 2024-25, skipping.
Skipping merge for Seth Lundy on 2024-25 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2023-24, skipping.
Skipping merge for Trentyn Flowers on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2024-25, skipping.
Skipping merge for Trentyn Flowers on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Trentyn Flowers - No valid data found.
Player data missing for Cam Christie on 2023-24, skipping.
Skipping merge for Cam Christie on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pacome Dadiet on 2023-24, skipping.
Skipping merge for Pacome Dadiet on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2023-24, skipping.
Skipping merge for Kevin McCullar Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2024-25, skipping.
Skipping merge for Kevin McCullar Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Kevin McCullar Jr. - No valid data found.
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Anton Watson on 2023-24, skipping.
Skipping merge for Anton Watson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ariel Hukporti on 2023-24, skipping.
Skipping merge for Ariel Hukporti on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keaton Wallace on 2023-24, skipping.
Skipping merge for Keaton Wallace on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zaccharie Risacher on 2023-24, skipping.
Skipping merge for Zaccharie Risacher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Daeqwon Plowden on 2023-24, skipping.
Skipping merge for Daeqwon Plowden on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zyon Pullin on 2023-24, skipping.
Skipping merge for Zyon Pullin on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yuki Kawamura on 2023-24, skipping.
Skipping merge for Yuki Kawamura on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cam Spencer on 2023-24, skipping.
Skipping merge for Cam Spencer on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ronald Holland II on 2023-24, skipping.
Skipping merge for Ronald Holland II on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2023-24, skipping.
Skipping merge for Ron Harper Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2024-25, skipping.
Skipping merge for Ron Harper Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Ron Harper Jr. - No valid data found.
Player data missing for Daniss Jenkins on 2023-24, skipping.
Skipping merge for Daniss Jenkins on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Bobi Klintman on 2023-24, skipping.
Skipping merge for Bobi Klintman on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2023-24, skipping.
Skipping merge for Tolu Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2024-25, skipping.
Skipping merge for Tolu Smith on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Tolu Smith - No valid data found.
Player data missing for Terrence Shannon Jr. on 2023-24, skipping.
Skipping merge for Terrence Shannon Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Rob Dillingham on 2023-24, skipping.
Skipping merge for Rob Dillingham on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tristen Newton on 2023-24, skipping.
Skipping merge for Tristen Newton on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jesse Edwards on 2023-24, skipping.
Skipping merge for Jesse Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Clark on 2023-24, skipping.
Skipping merge for Jaylen Clark on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Phillip Wheeler on 2023-24, skipping.
Skipping merge for Phillip Wheeler on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Edwards on 2023-24, skipping.
Skipping merge for Justin Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jared McCain on 2023-24, skipping.
Skipping merge for Jared McCain on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Guerschon Yabusele on 2023-24, skipping.
Skipping merge for Guerschon Yabusele on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Adem Bona on 2023-24, skipping.
Skipping merge for Adem Bona on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Reese on 2023-24, skipping.
Skipping merge for Alex Reese on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin Porter Jr. on 2023-24, skipping.
Skipping merge for Kevin Porter Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Smith on 2023-24, skipping.
Skipping merge for Tyler Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Stevens on 2023-24, skipping.
Skipping merge for Isaiah Stevens on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kel'el Ware on 2023-24, skipping.
Skipping merge for Kel'el Ware on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Josh Christopher on 2023-24, skipping.
Skipping merge for Josh Christopher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pelle Larsson on 2023-24, skipping.
Skipping merge for Pelle Larsson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keshad Johnson on 2023-24, skipping.
Skipping merge for Keshad Johnson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2023-24, skipping.
Skipping merge for Brandon Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2024-25, skipping.
Skipping merge for Brandon Williams on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Brandon Williams - No valid data found.
Player data missing for Kai Jones on 2023-24, skipping.
Skipping merge for Kai Jones on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Seth Lundy on 2024-25, skipping.
Skipping merge for Seth Lundy on 2024-25 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2023-24, skipping.
Skipping merge for Trentyn Flowers on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2024-25, skipping.
Skipping merge for Trentyn Flowers on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Trentyn Flowers - No valid data found.
Player data missing for Cam Christie on 2023-24, skipping.
Skipping merge for Cam Christie on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.483e-01, tolerance: 1.092e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.187e-03, tolerance: 1.889e-03
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.591e-01, tolerance: 1.032e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.897e-01, tolerance: 2.061e-02
  model = cd_fast.enet_coordinate_descent(

Skipping Daeqwon Plowden due to insufficient data (3 samples).
Skipping Zyon Pullin due to insufficient data (3 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.372e-01, tolerance: 3.956e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.007e-02, tolerance: 3.964e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.937e-01, tolerance: 3.712e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.256e-01, tolerance: 4.131e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.998e-02, tolerance: 3.916e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.132e-01, tolerance: 4.420e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

Skipping Jesse Edwards due to insufficient data (2 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.085e-02, tolerance: 3.899e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.434e-01, tolerance: 3.452e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.681e-02, tolerance: 1.291e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.612e-02, tolerance: 3.319e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.296e+00, tolerance: 2.895e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.170e-01, tolerance: 3.181e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.769e-02, tolerance: 1.520e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(

Skipping Isaiah Stevens due to insufficient data (3 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.360e-02, tolerance: 1.048e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.055e-02, tolerance: 1.053e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.601e-02, tolerance: 2.980e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.847e-02, tolerance: 2.063e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.836e-03, tolerance: 4.897e-03
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.757e-01, tolerance: 3.480e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()

Skipping Kevin McCullar Jr. - No data available.

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

No valid features found for Daeqwon Plowden for predicting AST
No valid features found for Zyon Pullin for predicting AST

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

Skipping Ron Harper Jr. - No data available.
Skipping Tolu Smith - No data available.

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

No valid features found for Jesse Edwards for predicting AST

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()

No valid features found for Isaiah Stevens for predicting AST

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

Skipping Brandon Williams - No data available.

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

Skipping Trentyn Flowers - No data available.

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

Player data missing for Pacome Dadiet on 2023-24, skipping.
Skipping merge for Pacome Dadiet on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2023-24, skipping.
Skipping merge for Kevin McCullar Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2024-25, skipping.
Skipping merge for Kevin McCullar Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Kevin McCullar Jr. - No valid data found.
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Anton Watson on 2023-24, skipping.
Skipping merge for Anton Watson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ariel Hukporti on 2023-24, skipping.
Skipping merge for Ariel Hukporti on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keaton Wallace on 2023-24, skipping.
Skipping merge for Keaton Wallace on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zaccharie Risacher on 2023-24, skipping.
Skipping merge for Zaccharie Risacher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Daeqwon Plowden on 2023-24, skipping.
Skipping merge for Daeqwon Plowden on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zyon Pullin on 2023-24, skipping.
Skipping merge for Zyon Pullin on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yuki Kawamura on 2023-24, skipping.
Skipping merge for Yuki Kawamura on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cam Spencer on 2023-24, skipping.
Skipping merge for Cam Spencer on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ronald Holland II on 2023-24, skipping.
Skipping merge for Ronald Holland II on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2023-24, skipping.
Skipping merge for Ron Harper Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2024-25, skipping.
Skipping merge for Ron Harper Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Ron Harper Jr. - No valid data found.
Player data missing for Daniss Jenkins on 2023-24, skipping.
Skipping merge for Daniss Jenkins on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Bobi Klintman on 2023-24, skipping.
Skipping merge for Bobi Klintman on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2023-24, skipping.
Skipping merge for Tolu Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2024-25, skipping.
Skipping merge for Tolu Smith on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Tolu Smith - No valid data found.
Player data missing for Terrence Shannon Jr. on 2023-24, skipping.
Skipping merge for Terrence Shannon Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Rob Dillingham on 2023-24, skipping.
Skipping merge for Rob Dillingham on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tristen Newton on 2023-24, skipping.
Skipping merge for Tristen Newton on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jesse Edwards on 2023-24, skipping.
Skipping merge for Jesse Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Clark on 2023-24, skipping.
Skipping merge for Jaylen Clark on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Phillip Wheeler on 2023-24, skipping.
Skipping merge for Phillip Wheeler on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Edwards on 2023-24, skipping.
Skipping merge for Justin Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jared McCain on 2023-24, skipping.
Skipping merge for Jared McCain on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Guerschon Yabusele on 2023-24, skipping.
Skipping merge for Guerschon Yabusele on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Adem Bona on 2023-24, skipping.
Skipping merge for Adem Bona on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Reese on 2023-24, skipping.
Skipping merge for Alex Reese on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin Porter Jr. on 2023-24, skipping.
Skipping merge for Kevin Porter Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Smith on 2023-24, skipping.
Skipping merge for Tyler Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Stevens on 2023-24, skipping.
Skipping merge for Isaiah Stevens on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kel'el Ware on 2023-24, skipping.
Skipping merge for Kel'el Ware on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Josh Christopher on 2023-24, skipping.
Skipping merge for Josh Christopher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pelle Larsson on 2023-24, skipping.
Skipping merge for Pelle Larsson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keshad Johnson on 2023-24, skipping.
Skipping merge for Keshad Johnson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2023-24, skipping.
Skipping merge for Brandon Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2024-25, skipping.
Skipping merge for Brandon Williams on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Brandon Williams - No valid data found.
Player data missing for Kai Jones on 2023-24, skipping.
Skipping merge for Kai Jones on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Seth Lundy on 2024-25, skipping.
Skipping merge for Seth Lundy on 2024-25 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2023-24, skipping.
Skipping merge for Trentyn Flowers on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2024-25, skipping.
Skipping merge for Trentyn Flowers on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Trentyn Flowers - No valid data found.
Player data missing for Cam Christie on 2023-24, skipping.
Skipping merge for Cam Christie on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pacome Dadiet on 2023-24, skipping.
Skipping merge for Pacome Dadiet on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2023-24, skipping.
Skipping merge for Kevin McCullar Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2024-25, skipping.
Skipping merge for Kevin McCullar Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Kevin McCullar Jr. - No valid data found.
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Anton Watson on 2023-24, skipping.
Skipping merge for Anton Watson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ariel Hukporti on 2023-24, skipping.
Skipping merge for Ariel Hukporti on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keaton Wallace on 2023-24, skipping.
Skipping merge for Keaton Wallace on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zaccharie Risacher on 2023-24, skipping.
Skipping merge for Zaccharie Risacher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Daeqwon Plowden on 2023-24, skipping.
Skipping merge for Daeqwon Plowden on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zyon Pullin on 2023-24, skipping.
Skipping merge for Zyon Pullin on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yuki Kawamura on 2023-24, skipping.
Skipping merge for Yuki Kawamura on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cam Spencer on 2023-24, skipping.
Skipping merge for Cam Spencer on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ronald Holland II on 2023-24, skipping.
Skipping merge for Ronald Holland II on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2023-24, skipping.
Skipping merge for Ron Harper Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2024-25, skipping.
Skipping merge for Ron Harper Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Ron Harper Jr. - No valid data found.
Player data missing for Daniss Jenkins on 2023-24, skipping.
Skipping merge for Daniss Jenkins on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Bobi Klintman on 2023-24, skipping.
Skipping merge for Bobi Klintman on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2023-24, skipping.
Skipping merge for Tolu Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2024-25, skipping.
Skipping merge for Tolu Smith on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Tolu Smith - No valid data found.
Player data missing for Terrence Shannon Jr. on 2023-24, skipping.
Skipping merge for Terrence Shannon Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Rob Dillingham on 2023-24, skipping.
Skipping merge for Rob Dillingham on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tristen Newton on 2023-24, skipping.
Skipping merge for Tristen Newton on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jesse Edwards on 2023-24, skipping.
Skipping merge for Jesse Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Clark on 2023-24, skipping.
Skipping merge for Jaylen Clark on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Phillip Wheeler on 2023-24, skipping.
Skipping merge for Phillip Wheeler on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Edwards on 2023-24, skipping.
Skipping merge for Justin Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jared McCain on 2023-24, skipping.
Skipping merge for Jared McCain on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Guerschon Yabusele on 2023-24, skipping.
Skipping merge for Guerschon Yabusele on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Adem Bona on 2023-24, skipping.
Skipping merge for Adem Bona on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Reese on 2023-24, skipping.
Skipping merge for Alex Reese on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin Porter Jr. on 2023-24, skipping.
Skipping merge for Kevin Porter Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Smith on 2023-24, skipping.
Skipping merge for Tyler Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Stevens on 2023-24, skipping.
Skipping merge for Isaiah Stevens on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kel'el Ware on 2023-24, skipping.
Skipping merge for Kel'el Ware on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Josh Christopher on 2023-24, skipping.
Skipping merge for Josh Christopher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pelle Larsson on 2023-24, skipping.
Skipping merge for Pelle Larsson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keshad Johnson on 2023-24, skipping.
Skipping merge for Keshad Johnson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2023-24, skipping.
Skipping merge for Brandon Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2024-25, skipping.
Skipping merge for Brandon Williams on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Brandon Williams - No valid data found.
Player data missing for Kai Jones on 2023-24, skipping.
Skipping merge for Kai Jones on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Seth Lundy on 2024-25, skipping.
Skipping merge for Seth Lundy on 2024-25 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2023-24, skipping.
Skipping merge for Trentyn Flowers on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2024-25, skipping.
Skipping merge for Trentyn Flowers on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Trentyn Flowers - No valid data found.
Player data missing for Cam Christie on 2023-24, skipping.
Skipping merge for Cam Christie on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(

Skipping Daeqwon Plowden due to insufficient data (3 samples).
Skipping Zyon Pullin due to insufficient data (3 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

Skipping Jesse Edwards due to insufficient data (2 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(

Skipping Isaiah Stevens due to insufficient data (3 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(

Skipping Kevin McCullar Jr. - No data available.
No valid features found for Daeqwon Plowden for predicting PTS
No valid features found for Zyon Pullin for predicting PTS
Skipping Ron Harper Jr. - No data available.
Skipping Tolu Smith - No data available.
No valid features found for Jesse Edwards for predicting PTS
No valid features found for Isaiah Stevens for predicting PTS
Skipping Brandon Williams - No data available.
Skipping Trentyn Flowers - No data available.
Player data missing for Pacome Dadiet on 2023-24, skipping.
Skipping merge for Pacome Dadiet on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2023-24, skipping.
Skipping merge for Kevin McCullar Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2024-25, skipping.
Skipping merge for Kevin McCullar Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Kevin McCullar Jr. - No valid data found.
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Anton Watson on 2023-24, skipping.
Skipping merge for Anton Watson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ariel Hukporti on 2023-24, skipping.
Skipping merge for Ariel Hukporti on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keaton Wallace on 2023-24, skipping.
Skipping merge for Keaton Wallace on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zaccharie Risacher on 2023-24, skipping.
Skipping merge for Zaccharie Risacher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Daeqwon Plowden on 2023-24, skipping.
Skipping merge for Daeqwon Plowden on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zyon Pullin on 2023-24, skipping.
Skipping merge for Zyon Pullin on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yuki Kawamura on 2023-24, skipping.
Skipping merge for Yuki Kawamura on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cam Spencer on 2023-24, skipping.
Skipping merge for Cam Spencer on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ronald Holland II on 2023-24, skipping.
Skipping merge for Ronald Holland II on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2023-24, skipping.
Skipping merge for Ron Harper Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2024-25, skipping.
Skipping merge for Ron Harper Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Ron Harper Jr. - No valid data found.
Player data missing for Daniss Jenkins on 2023-24, skipping.
Skipping merge for Daniss Jenkins on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Bobi Klintman on 2023-24, skipping.
Skipping merge for Bobi Klintman on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2023-24, skipping.
Skipping merge for Tolu Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2024-25, skipping.
Skipping merge for Tolu Smith on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Tolu Smith - No valid data found.
Player data missing for Terrence Shannon Jr. on 2023-24, skipping.
Skipping merge for Terrence Shannon Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Rob Dillingham on 2023-24, skipping.
Skipping merge for Rob Dillingham on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tristen Newton on 2023-24, skipping.
Skipping merge for Tristen Newton on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jesse Edwards on 2023-24, skipping.
Skipping merge for Jesse Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Clark on 2023-24, skipping.
Skipping merge for Jaylen Clark on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Phillip Wheeler on 2023-24, skipping.
Skipping merge for Phillip Wheeler on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Edwards on 2023-24, skipping.
Skipping merge for Justin Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jared McCain on 2023-24, skipping.
Skipping merge for Jared McCain on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Guerschon Yabusele on 2023-24, skipping.
Skipping merge for Guerschon Yabusele on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Adem Bona on 2023-24, skipping.
Skipping merge for Adem Bona on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Reese on 2023-24, skipping.
Skipping merge for Alex Reese on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin Porter Jr. on 2023-24, skipping.
Skipping merge for Kevin Porter Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Smith on 2023-24, skipping.
Skipping merge for Tyler Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Stevens on 2023-24, skipping.
Skipping merge for Isaiah Stevens on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kel'el Ware on 2023-24, skipping.
Skipping merge for Kel'el Ware on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Josh Christopher on 2023-24, skipping.
Skipping merge for Josh Christopher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pelle Larsson on 2023-24, skipping.
Skipping merge for Pelle Larsson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keshad Johnson on 2023-24, skipping.
Skipping merge for Keshad Johnson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2023-24, skipping.
Skipping merge for Brandon Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2024-25, skipping.
Skipping merge for Brandon Williams on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Brandon Williams - No valid data found.
Player data missing for Kai Jones on 2023-24, skipping.
Skipping merge for Kai Jones on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Seth Lundy on 2024-25, skipping.
Skipping merge for Seth Lundy on 2024-25 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2023-24, skipping.
Skipping merge for Trentyn Flowers on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2024-25, skipping.
Skipping merge for Trentyn Flowers on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Trentyn Flowers - No valid data found.
Player data missing for Cam Christie on 2023-24, skipping.
Skipping merge for Cam Christie on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pacome Dadiet on 2023-24, skipping.
Skipping merge for Pacome Dadiet on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2023-24, skipping.
Skipping merge for Kevin McCullar Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin McCullar Jr. on 2024-25, skipping.
Skipping merge for Kevin McCullar Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Kevin McCullar Jr. - No valid data found.
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Anton Watson on 2023-24, skipping.
Skipping merge for Anton Watson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ariel Hukporti on 2023-24, skipping.
Skipping merge for Ariel Hukporti on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keaton Wallace on 2023-24, skipping.
Skipping merge for Keaton Wallace on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zaccharie Risacher on 2023-24, skipping.
Skipping merge for Zaccharie Risacher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Daeqwon Plowden on 2023-24, skipping.
Skipping merge for Daeqwon Plowden on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zyon Pullin on 2023-24, skipping.
Skipping merge for Zyon Pullin on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yuki Kawamura on 2023-24, skipping.
Skipping merge for Yuki Kawamura on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cam Spencer on 2023-24, skipping.
Skipping merge for Cam Spencer on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ronald Holland II on 2023-24, skipping.
Skipping merge for Ronald Holland II on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2023-24, skipping.
Skipping merge for Ron Harper Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ron Harper Jr. on 2024-25, skipping.
Skipping merge for Ron Harper Jr. on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Ron Harper Jr. - No valid data found.
Player data missing for Daniss Jenkins on 2023-24, skipping.
Skipping merge for Daniss Jenkins on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Bobi Klintman on 2023-24, skipping.
Skipping merge for Bobi Klintman on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2023-24, skipping.
Skipping merge for Tolu Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tolu Smith on 2024-25, skipping.
Skipping merge for Tolu Smith on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Tolu Smith - No valid data found.
Player data missing for Terrence Shannon Jr. on 2023-24, skipping.
Skipping merge for Terrence Shannon Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Rob Dillingham on 2023-24, skipping.
Skipping merge for Rob Dillingham on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tristen Newton on 2023-24, skipping.
Skipping merge for Tristen Newton on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jesse Edwards on 2023-24, skipping.
Skipping merge for Jesse Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Clark on 2023-24, skipping.
Skipping merge for Jaylen Clark on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Phillip Wheeler on 2023-24, skipping.
Skipping merge for Phillip Wheeler on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Edwards on 2023-24, skipping.
Skipping merge for Justin Edwards on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jared McCain on 2023-24, skipping.
Skipping merge for Jared McCain on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Guerschon Yabusele on 2023-24, skipping.
Skipping merge for Guerschon Yabusele on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Adem Bona on 2023-24, skipping.
Skipping merge for Adem Bona on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Reese on 2023-24, skipping.
Skipping merge for Alex Reese on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kevin Porter Jr. on 2023-24, skipping.
Skipping merge for Kevin Porter Jr. on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Smith on 2023-24, skipping.
Skipping merge for Tyler Smith on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Stevens on 2023-24, skipping.
Skipping merge for Isaiah Stevens on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kel'el Ware on 2023-24, skipping.
Skipping merge for Kel'el Ware on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Josh Christopher on 2023-24, skipping.
Skipping merge for Josh Christopher on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Pelle Larsson on 2023-24, skipping.
Skipping merge for Pelle Larsson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Keshad Johnson on 2023-24, skipping.
Skipping merge for Keshad Johnson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2023-24, skipping.
Skipping merge for Brandon Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandon Williams on 2024-25, skipping.
Skipping merge for Brandon Williams on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Brandon Williams - No valid data found.
Player data missing for Kai Jones on 2023-24, skipping.
Skipping merge for Kai Jones on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Seth Lundy on 2024-25, skipping.
Skipping merge for Seth Lundy on 2024-25 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2023-24, skipping.
Skipping merge for Trentyn Flowers on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Trentyn Flowers on 2024-25, skipping.
Skipping merge for Trentyn Flowers on 2024-25 due to missing data.
defense data skipping defense merge
Skipping Trentyn Flowers - No valid data found.
Player data missing for Cam Christie on 2023-24, skipping.
Skipping merge for Cam Christie on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

Skipping Daeqwon Plowden due to insufficient data (3 samples).
Skipping Zyon Pullin due to insufficient data (3 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1107: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

Skipping Jesse Edwards due to insufficient data (2 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(

Skipping Isaiah Stevens due to insufficient data (3 samples).

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(

Skipping Kevin McCullar Jr. - No data available.

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

No valid features found for Daeqwon Plowden for predicting 3PM
No valid features found for Zyon Pullin for predicting 3PM

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

Skipping Ron Harper Jr. - No data available.

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

Skipping Tolu Smith - No data available.

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

No valid features found for Jesse Edwards for predicting 3PM

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

No valid features found for Isaiah Stevens for predicting 3PM

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

Skipping Brandon Williams - No data available.

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

Skipping Trentyn Flowers - No data available.

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:221: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:222: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

In [141]:

# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

# results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != 100.00]
df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
    .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
    .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))




# players_to_remove = ['Tyrese Haliburton', 'Player1', 'Player2', 'Player3']
# matchup = ["UTA", "IND","SAC","CHA","DET", "TOR", "PHX","BOS", "CLE", "SAS", "OKC", "HOU", "POR", "CHI","DEN", "GSW", "DAL", "LAC", "NOP", "LAC"]

# matchup = ["NYK", "ATL","MEM","DET","MIN", "PHI", "MIL","MIA", "DAL", "LAC"]
matchup = ["MEM","DET"]

df_list = []  # List to store dataframes
for team in matchup:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path



    # Iterate through all files in the directory
    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Append DataFrame to the list




        # Concatenate all the box score dataframes into one
        df= pd.concat(df_list, ignore_index=True)
        


        df =df['PLAYER_uni'].tolist()

list_of_names = df

print(list_of_names) # check history for all comments on what this is doing

players = list_of_names




Team_to_remove = []
# Team_to_remove = ["PHX","MIL", "PHI", "NYK", "POR", "ATL", "GSW","GSW", "MEM", "TOR", "CHI",]

# df_merged = df_merged[~df_merged["team"].isin(Team_to_remove)]

find_player = players

df_merged = df_merged[df_merged["Player"].isin(find_player)]
df_merged = df_merged.sort_values(by=["team", "Player"], ascending=[True, True])



display(df_merged)



# from parlay_picker import create_parlays

# num_groups = 25  # Number of parlays you want to generate
# players_per_group = 20 # Number of players in each parlay
# min_confidence = 20
# threepm_confidence = 20

# parlays_df, group_confidence_scores = create_parlays(df_merged, num_groups, players_per_group,min_confidence,threepm_confidence)


# # Display the confidence scores for each group
# print("Confidence scores for each group:")
# for group, score in group_confidence_scores:
#     print(f"{group}: {score:.2f}")


# # Display the DataFrames for each parlay and their confidence scores
# for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
#     print("\n")
#     print(f"{parlay_name}: total confidence score: {score:.2f}")
#     display(parlay_df)
#     print("\n")

['Zyon Pullin', 'Jaylen Wells', 'Scotty Pippen Jr.', 'Vince Williams Jr.', 'Santi Aldama', 'Lamar Stevens', 'Luke Kennard', 'Ja Morant', 'Jaren Jackson Jr.', 'Zach Edey', 'Brandon Clarke', 'Yuki Kawamura', 'Desmond Bane', 'Cam Spencer', 'Jay Huff', 'Marvin Bagley III', 'GG Jackson', 'John Konchar', 'Jalen Duren', 'Ronald Holland II', 'Cade Cunningham', 'Malik Beasley', 'Paul Reed', 'Tim Hardaway Jr.', 'Ausar Thompson', 'Tobias Harris', 'Ron Harper Jr.', 'Dennis Schroder', 'Simone Fontecchio', 'Jaden Ivey', 'Daniss Jenkins', 'Marcus Sasser', 'Isaiah Stewart', 'Bobi Klintman', 'Tolu Smith', 'Lindy Waters III']

                Player team          REB  confidence_level_REB                       recentgames_REB        AST  confidence_level_AST                     recentgames_AST           PTS  confidence_level_PTS                           recentgames_PTS        3PM  confidence_level_3PM                 recentgames_3PM
57      Ausar Thompson  DET    2 - 4 - 5                 62.06       [7, 8, 4, 10, 6, 1, 3, 6, 4, 4]  1 - 1 - 1                 37.35      [4, 3, 1, 2, 3, 1, 3, 1, 3, 1]     1 - 3 - 4                 64.21      [15, 13, 14, 18, 14, 5, 8, 14, 9, 8]  0 - 0 - 0                 45.39  [0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
65       Bobi Klintman  DET    0 - 0 - 0                100.00                 [0, 1, 1, 0, 0, 0, 2]  0 - 0 - 0                100.00               [0, 0, 0, 0, 0, 1, 0]     0 - 0 - 0                100.00                     [0, 0, 0, 0, 0, 0, 0]  0 - 0 - 0                100.00           [0, 0, 0, 0, 0, 0, 0]
53     Cade Cunningham  DET    2 - 4 - 5                 50.72       [7, 12, 4, 7, 3, 8, 4, 4, 7, 1]  4 - 6 - 7                 72.83  [6, 11, 8, 9, 10, 10, 5, 5, 10, 9]  17 - 26 - 34                 67.83  [35, 25, 24, 11, 38, 27, 28, 31, 37, 29]  0 - 1 - 1                 13.59  [2, 3, 1, 0, 0, 1, 2, 2, 2, 1]
62      Daniss Jenkins  DET    0 - 0 - 0                100.00                    [0, 0, 0, 0, 0, 0]  0 - 0 - 0                100.00                  [0, 0, 0, 0, 0, 0]     2 - 2 - 2                100.00                        [5, 0, 0, 0, 0, 0]  0 - 0 - 0                100.00              [1, 0, 0, 0, 0, 0]
59     Dennis Schroder  DET    1 - 2 - 3                 33.58        [4, 4, 4, 7, 2, 1, 3, 1, 0, 3]  3 - 6 - 8                 58.16   [7, 7, 11, 10, 6, 5, 4, 3, 5, 11]   7 - 11 - 14                 65.68    [16, 15, 11, 17, 7, 16, 11, 8, 12, 17]  0 - 1 - 2                  0.00  [1, 1, 0, 1, 0, 1, 2, 0, 0, 4]
64      Isaiah Stewart  DET    2 - 4 - 5                 65.66        [4, 4, 6, 3, 6, 6, 5, 7, 1, 7]  1 - 1 - 1                 36.94      [1, 1, 2, 2, 2, 2, 1, 0, 2, 4]     1 - 4 - 6                 49.08           [0, 14, 4, 9, 8, 6, 6, 9, 4, 7]  0 - 0 - 0                 25.14  [0, 0, 0, 1, 0, 0, 0, 1, 0, 0]
61          Jaden Ivey  DET    1 - 1 - 1                 41.42        [1, 3, 6, 3, 8, 3, 4, 2, 3, 2]  1 - 2 - 3                 38.76      [4, 1, 0, 2, 8, 2, 4, 2, 5, 5]  15 - 24 - 32                 66.52   [22, 17, 19, 18, 20, 10, 16, 11, 8, 15]  1 - 4 - 6                 41.02  [5, 2, 3, 2, 4, 2, 2, 1, 1, 3]
51         Jalen Duren  DET   5 - 8 - 10                 62.58  [18, 13, 11, 13, 4, 12, 9, 11, 7, 5]  1 - 2 - 3                 24.22      [6, 3, 3, 0, 7, 2, 3, 1, 6, 2]   7 - 11 - 14                 70.79    [21, 13, 13, 16, 14, 22, 14, 15, 9, 8]  0 - 0 - 0                100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
66    Lindy Waters III  DET    1 - 2 - 5                  0.00        [0, 1, 4, 0, 0, 2, 0, 0, 0, 0]  1 - 1 - 2                 30.80      [2, 1, 1, 0, 1, 2, 1, 0, 0, 0]    1 - 9 - 19                 15.21            [3, 3, 0, 3, 3, 0, 6, 8, 0, 0]  0 - 2 - 4                 33.10  [1, 1, 0, 1, 1, 0, 2, 2, 0, 0]
54       Malik Beasley  DET    1 - 2 - 3                 23.94        [4, 1, 2, 4, 3, 4, 1, 1, 4, 0]  1 - 1 - 1                 30.92      [2, 0, 0, 4, 3, 2, 2, 3, 3, 2]   6 - 10 - 13                 67.44  [21, 11, 27, 19, 13, 13, 16, 16, 11, 15]  1 - 2 - 2                 64.63  [3, 3, 6, 3, 2, 4, 5, 5, 3, 3]
63       Marcus Sasser  DET    1 - 2 - 4                 27.94        [4, 1, 1, 4, 1, 2, 0, 0, 0, 0]  1 - 4 - 6                 34.49      [1, 3, 4, 1, 2, 1, 1, 3, 1, 2]   1 - 12 - 23                  1.68         [10, 3, 4, 27, 20, 3, 0, 5, 2, 6]  0 - 1 - 2                 25.72  [1, 1, 1, 5, 3, 1, 0, 1, 0, 1]
55           Paul Reed  DET    1 - 5 - 9                 15.92        [1, 9, 3, 0, 4, 2, 4, 2, 4, 3]  1 - 2 - 4                 32.73      [1, 0, 0, 0, 1, 0, 2, 0, 2, 1]    1 - 6 - 11                 16.52            [0, 9, 4, 3, 3, 0, 6, 2, 8, 2]  0 - 0 - 0                 45.39  [0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
52   Ronald Holland II  DET    1 - 3 - 4                 36.30        [5, 2, 2, 6, 5, 5, 1, 2, 3, 4]  1 - 1 - 1                 10.69      [3, 1, 1, 2, 6, 1, 1, 3, 2, 0]    2 - 8 - 13                 32.85        [3, 4, 10, 8, 26, 12, 7, 10, 6, 3]  0 - 0 - 0                  9.90  [0, 0, 2, 1, 1, 1, 0, 0, 0, 0]
60   Simone Fontecchio  DET    1 - 1 - 1                 23.77        [1, 0, 5, 1, 3, 2, 0, 2, 7, 2]  0 - 0 - 0                  5.31      [1, 1, 1, 0, 1, 1, 0, 0, 0, 2]   1 - 11 - 21                  3.70           [5, 6, 3, 3, 2, 8, 4, 2, 23, 4]  0 - 2 - 4                  6.72  [1, 0, 1, 1, 0, 2, 0, 0, 5, 0]
56    Tim Hardaway Jr.  DET    1 - 3 - 4                 34.86        [3, 3, 4, 1, 2, 1, 2, 3, 1, 3]  0 - 0 - 0                 23.16      [0, 3, 0, 3, 4, 0, 1, 0, 0, 1]    3 - 9 - 14                 41.42    [23, 23, 20, 32, 12, 0, 10, 8, 11, 10]  0 - 1 - 1                 15.15  [5, 5, 3, 7, 1, 0, 1, 2, 3, 2]
58       Tobias Harris  DET    2 - 4 - 5                 58.49        [4, 8, 3, 6, 5, 6, 7, 6, 8, 9]  1 - 1 - 1                 34.09      [2, 4, 4, 3, 2, 0, 0, 3, 1, 2]    5 - 8 - 10                 74.19    [10, 15, 14, 9, 13, 9, 18, 14, 12, 20]  0 - 0 - 0                 20.71  [0, 3, 0, 1, 0, 0, 2, 2, 2, 1]
43      Brandon Clarke  MEM    2 - 5 - 7                 42.87       [1, 8, 2, 5, 4, 5, 8, 11, 7, 7]  0 - 0 - 0                 17.10      [0, 3, 0, 1, 1, 0, 2, 2, 1, 2]   6 - 14 - 21                 49.71     [0, 15, 12, 13, 8, 2, 17, 13, 11, 11]  0 - 0 - 0                100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
46         Cam Spencer  MEM    0 - 0 - 0                  0.00        [0, 0, 2, 0, 0, 3, 2, 0, 3, 0]  0 - 0 - 0                  0.00      [0, 0, 1, 0, 0, 2, 3, 2, 1, 0]     0 - 0 - 0                  0.00           [0, 0, 4, 0, 0, 7, 6, 3, 16, 2]  0 - 0 - 0                  0.00  [0, 0, 0, 0, 0, 1, 2, 1, 4, 0]
45        Desmond Bane  MEM    2 - 6 - 9                 46.51       [9, 4, 2, 4, 2, 4, 5, 7, 6, 10]  2 - 5 - 7                 56.92      [6, 5, 3, 6, 6, 6, 4, 4, 4, 8]  12 - 25 - 37                 49.78   [17, 19, 12, 29, 3, 21, 10, 20, 44, 22]  0 - 2 - 3                 25.22  [1, 4, 1, 5, 1, 2, 2, 2, 7, 4]
49          GG Jackson  MEM    1 - 3 - 5                 17.26        [2, 6, 4, 4, 1, 2, 3, 7, 1, 1]  1 - 1 - 2                  3.93      [0, 1, 0, 3, 0, 0, 2, 3, 1, 3]   1 - 12 - 22                 11.51          [5, 4, 8, 14, 0, 5, 6, 11, 4, 0]  0 - 2 - 3                 10.56  [1, 0, 2, 2, 0, 1, 2, 2, 0, 0]
40           Ja Morant  MEM    2 - 4 - 5                 51.79        [5, 3, 6, 8, 8, 1, 4, 4, 4, 3]  3 - 5 - 6                 62.55    [3, 6, 5, 10, 7, 7, 12, 6, 8, 6]  23 - 33 - 42                 70.05  [30, 36, 26, 22, 44, 28, 29, 32, 31, 24]  0 - 4 - 7                 18.19  [3, 5, 2, 1, 1, 4, 1, 3, 1, 2]
41   Jaren Jackson Jr.  MEM    2 - 6 - 9                 36.79       [4, 7, 15, 4, 2, 3, 2, 5, 3, 6]  1 - 1 - 1                 23.05      [1, 1, 1, 1, 4, 1, 1, 2, 3, 1]  14 - 26 - 37                 55.76  [13, 22, 20, 24, 27, 19, 23, 14, 12, 31]  0 - 0 - 0                 16.52  [3, 2, 3, 3, 5, 2, 3, 2, 0, 1]
47            Jay Huff  MEM    1 - 1 - 2                 17.45        [0, 0, 2, 6, 1, 3, 2, 0, 4, 3]  0 - 0 - 0                 37.55      [0, 0, 1, 0, 0, 2, 0, 0, 1, 0]    1 - 6 - 13                 19.87         [0, 0, 8, 15, 13, 8, 0, 2, 5, 14]  0 - 0 - 0                 41.06  [0, 0, 2, 1, 3, 1, 0, 0, 1, 4]
34        Jaylen Wells  MEM    1 - 4 - 6                 48.55        [7, 4, 4, 3, 5, 6, 3, 1, 4, 3]  1 - 2 - 3                 26.66      [3, 1, 2, 3, 0, 5, 2, 0, 2, 2]   4 - 13 - 21                 38.04      [13, 5, 10, 11, 13, 10, 3, 2, 14, 8]  0 - 2 - 3                 15.42  [2, 1, 2, 1, 2, 2, 1, 0, 3, 1]
50        John Konchar  MEM    1 - 3 - 5                  4.22        [1, 1, 7, 2, 3, 8, 2, 1, 1, 3]  0 - 0 - 0                  0.00      [0, 0, 3, 0, 2, 1, 0, 1, 0, 0]     1 - 4 - 9                  0.00            [0, 0, 8, 0, 3, 8, 0, 2, 0, 0]  0 - 1 - 2                 28.36  [0, 0, 2, 0, 1, 2, 0, 0, 0, 0]
38       Lamar Stevens  MEM    1 - 5 - 9                 15.94        [0, 0, 0, 0, 1, 5, 5, 6, 5, 2]  0 - 0 - 0                 11.11      [0, 0, 0, 0, 0, 1, 1, 0, 3, 0]   1 - 11 - 21                  2.86           [0, 0, 0, 2, 0, 7, 7, 2, 13, 1]  0 - 0 - 0                  9.13  [0, 0, 0, 0, 0, 0, 1, 0, 4, 0]
39        Luke Kennard  MEM    1 - 1 - 1                 30.59        [2, 1, 1, 0, 5, 3, 2, 3, 2, 4]  1 - 4 - 6                 34.30      [1, 5, 0, 2, 1, 6, 4, 3, 8, 4]   1 - 11 - 20                 12.09          [3, 3, 1, 0, 9, 8, 15, 6, 8, 11]  0 - 2 - 4                  0.00  [1, 1, 0, 0, 1, 2, 3, 0, 0, 1]
48   Marvin Bagley III  MEM   1 - 6 - 12                  2.23        [0, 5, 1, 1, 1, 1, 5, 2, 0, 6]  0 - 0 - 0                 12.71      [0, 1, 0, 0, 0, 0, 0, 0, 0, 1]    1 - 9 - 19                  4.40            [2, 2, 0, 2, 0, 0, 9, 3, 0, 7]  0 - 0 - 0                 27.05  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
37        Santi Aldama  MEM    2 - 4 - 5                 72.93        [8, 6, 8, 5, 5, 5, 5, 5, 5, 8]  1 - 2 - 3                 25.08     [2, 1, 4, 2, 5, 3, 7, 1, 3, 11]     3 - 5 - 6                 62.59      [9, 18, 21, 8, 10, 9, 16, 16, 6, 15]  0 - 0 - 0                 33.75  [3, 4, 3, 0, 1, 2, 3, 2, 0, 1]
35   Scotty Pippen Jr.  MEM    1 - 5 - 8                 30.59       [1, 2, 1, 3, 10, 5, 3, 6, 6, 3]  2 - 6 - 9                 35.64    [7, 2, 3, 5, 7, 10, 5, 4, 11, 6]   8 - 17 - 25                 48.71    [17, 10, 5, 16, 17, 16, 15, 18, 11, 8]  0 - 1 - 1                 18.39  [3, 1, 0, 3, 3, 2, 3, 0, 2, 2]
36  Vince Williams Jr.  MEM    1 - 1 - 1                 22.35        [0, 3, 0, 4, 8, 2, 3, 3, 3, 4]  1 - 2 - 3                 43.62      [2, 2, 3, 1, 3, 3, 0, 2, 3, 2]     1 - 2 - 3                 39.72           [2, 3, 7, 15, 5, 4, 2, 3, 2, 7]  0 - 0 - 0                 14.16  [0, 1, 1, 3, 1, 0, 0, 1, 0, 1]
44       Yuki Kawamura  MEM    0 - 0 - 0                  0.00        [0, 0, 1, 0, 1, 3, 0, 0, 0, 0]  0 - 0 - 0                  0.00      [0, 1, 1, 0, 1, 3, 1, 0, 0, 0]     1 - 1 - 3                  0.00           [0, 0, 0, 0, 0, 10, 0, 4, 0, 2]  0 - 0 - 0                  0.00  [0, 0, 0, 0, 0, 2, 0, 1, 0, 0]
42           Zach Edey  MEM  7 - 14 - 20                 53.48     [13, 16, 2, 11, 4, 7, 8, 3, 8, 8]  1 - 1 - 1                 20.53      [1, 1, 0, 2, 1, 2, 2, 2, 1, 1]    5 - 9 - 12                 60.85       [8, 10, 4, 14, 8, 15, 8, 6, 12, 12]  0 - 0 - 0                  0.00  [0, 0, 0, 0, 0, 2, 0, 0, 0, 0]

In [ ]:
def get_safe_bets(df, confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df["confidence_level_PTS"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets["PTS"].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", "PTS", "Safe Bet", "confidence_level_PTS"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_pts, confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df, confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df["confidence_level_REB"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets["REB"].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", "REB", "Safe Bet", "confidence_level_REB"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_reb, confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df,target ,confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df[f"confidence_level_{target}"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets[target].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", f"{target}", "Safe Bet", f"confidence_level_{target}"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_ast,"AST" ,confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df,target ,confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df[f"confidence_level_{target}"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets[target].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", f"{target}", "Safe Bet", f"confidence_level_{target}"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_3pm,"3PM" ,confidence_threshold=50)
print(safe_bets_df)

In [ ]:
results_pts.head(10)

In [ ]:
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players

# Retrieve player ID (e.g., LeBron James)
for basketball_players in results_pts["Player"]:
    a_player = players.find_players_by_full_name(basketball_players)[0]
    player_id = a_player['id']

    gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')  # Use the latest season
    games = gamelog.get_data_frames()[0]  # Extract data frame
    
    latest_game = games.iloc[0]
    print(basketball_players,latest_game['PTS'])




# player_name = "LeBron James"
# player = players.find_players_by_full_name(player_name)[0]  # Get player data by name

# player_id = player['id']  # Get player ID

# # Fetch the player's game log (latest games)
# gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')  # Use the latest season
# games = gamelog.get_data_frames()[0]  # Extract data frame

# # Get the latest game data
# latest_game = games.iloc[0]  # Latest game data
# print(type(latest_game))
# print(latest_game["PTS"])
# display(latest_game)

In [42]:
from nba_api.stats.endpoints import commonteamroster
from nba_api.stats.static import teams
import pandas as pd
from unidecode import unidecode

team_abbreviations = [
    "BOS", "BKN", "NYK", "PHI", "TOR",  # Atlantic Division
    "CHI", "CLE", "DET", "IND", "MIL",  # Central Division
    "ATL", "CHA", "MIA", "ORL", "WAS",  # Southeast Division
    "DEN", "MIN", "OKC", "POR", "UTA",  # Northwest Division
    "GSW", "LAC", "LAL", "PHX", "SAC",  # Pacific Division
    "DAL", "HOU", "MEM", "NOP", "SAS"   # Southwest Division
]


# Get all NBA teams and create a mapping of abbreviations to team IDs
nba_teams = teams.get_teams()
team_id_map = {team['abbreviation']: team['id'] for team in nba_teams}

# Dictionary to store team rosters
team_rosters = {}

# Loop through each team
for team_abbr in team_abbreviations:
    team_id = team_id_map[team_abbr]

    # Specify the season in 'YYYY-YY' format
    season = '2024-25'

    # Retrieve the team's roster
    roster = commonteamroster.CommonTeamRoster(team_id=team_id, season=season)

    # Convert the roster data to a pandas DataFrame
    roster_df = roster.get_data_frames()[0]

    # Normalize player names by removing accents
    roster_df['PLAYER_uni'] = roster_df['PLAYER'].apply(unidecode)


    roster_df['api_team_name'] = team_abbr

    # Store the roster for the team
    team_rosters[team_abbr] = roster_df

In [43]:
# Display rosters
import pandas as pd
import os
for team_abbr, roster_df in team_rosters.items():
    print(f"\n{team_abbr} Roster:")
    display(roster_df[['PLAYER_uni','POSITION','api_team_name']])
    # roster = roster.DataFrame(ri)
    directory = "D:/roster_folder/2024"
    os.makedirs(directory, exist_ok=True)
    roster_df.to_csv(fr"{directory}/{team_abbr}_roster_file.csv", index=False)

BOS Roster:

            PLAYER_uni POSITION api_team_name
0         Jayson Tatum      F-G           BOS
1         Miles Norris        F           BOS
2         Jrue Holiday        G           BOS
3         Jaylen Brown      G-F           BOS
4   Kristaps Porzingis      F-C           BOS
5        Derrick White        G           BOS
6     Payton Pritchard        G           BOS
7         Torrey Craig        F           BOS
8        Drew Peterson        F           BOS
9           JD Davison        G           BOS
10      Xavier Tillman        F           BOS
11        Jordan Walsh        G           BOS
12          Sam Hauser        F           BOS
13         Luke Kornet      C-F           BOS
14          Al Horford      C-F           BOS
15   Baylor Scheierman        G           BOS
16       Neemias Queta        C           BOS

BKN Roster:

           PLAYER_uni POSITION api_team_name
0     Dariq Whitehead      G-F           BKN
1    D'Angelo Russell        G           BKN
2     Cameron Johnson        F           BKN
3       Reece Beekman        G           BKN
4     Ziaire Williams        F           BKN
5     Trendon Watford      G-F           BKN
6       Tyson Etienne        G           BKN
7     Tosan Evbuomwan        F           BKN
8       Tyrese Martin        F           BKN
9   De'Anthony Melton        G           BKN
10     Day'Ron Sharpe        C           BKN
11       Noah Clowney      F-C           BKN
12       Jalen Wilson        F           BKN
13         Cam Thomas        G           BKN
14         Drew Timme        F           BKN
15      Maxwell Lewis        F           BKN
16        Nic Claxton        C           BKN
17       Keon Johnson        G           BKN

NYK Roster:

            PLAYER_uni POSITION api_team_name
0         Delon Wright        G           NYK
1     MarJon Beauchamp        F           NYK
2          P.J. Tucker        F           NYK
3        Cameron Payne        G           NYK
4        Miles McBride        G           NYK
5            Josh Hart        G           NYK
6        Pacome Dadiet        F           NYK
7     Precious Achiuwa        F           NYK
8           OG Anunoby      F-G           NYK
9   Kevin McCullar Jr.        G           NYK
10       Jalen Brunson        G           NYK
11         Tyler Kolek        G           NYK
12   Mitchell Robinson      C-F           NYK
13       Mikal Bridges      G-F           NYK
14        Anton Watson        F           NYK
15  Karl-Anthony Towns      C-F           NYK
16       Landry Shamet        G           NYK
17      Ariel Hukporti        C           NYK

PHI Roster:

             PLAYER_uni POSITION api_team_name
0       Phillip Wheeler        F           PHI
1          Tyrese Maxey        G           PHI
2        Andre Drummond        C           PHI
3        Quentin Grimes        G           PHI
4            Kyle Lowry        G           PHI
5           Paul George        F           PHI
6       Kelly Oubre Jr.      F-G           PHI
7       Jeff Dowtin Jr.        G           PHI
8          Jared Butler        G           PHI
9      Ricky Council IV        G           PHI
10     Lonnie Walker IV      G-F           PHI
11  Jalen Hood-Schifino        G           PHI
12       Justin Edwards        F           PHI
13         Jared McCain        G           PHI
14          Joel Embiid      C-F           PHI
15          Eric Gordon        G           PHI
16   Guerschon Yabusele        F           PHI
17            Adem Bona        F           PHI
18           Alex Reese      F-C           PHI

TOR Roster:

           PLAYER_uni POSITION api_team_name
0         A.J. Lawson        G           TOR
1         Gradey Dick      G-F           TOR
2      Jonathan Mogbo        F           TOR
3      Brandon Ingram        F           TOR
4      Scottie Barnes      F-G           TOR
5   Immanuel Quickley        G           TOR
6        Jared Rhoden        G           TOR
7          RJ Barrett      F-G           TOR
8         Cole Swider        F           TOR
9      Ja'Kobe Walter        G           TOR
10     Garrett Temple      G-F           TOR
11       Jakob Poeltl        C           TOR
12   Orlando Robinson        C           TOR
13     Ulrich Chomche        C           TOR
14        Jamal Shead        G           TOR
15      Chris Boucher        F           TOR
16       Ochai Agbaji        G           TOR
17     Jamison Battle        F           TOR

CHI Roster:

             PLAYER_uni POSITION api_team_name
0            Coby White        G           CHI
1            Lonzo Ball        G           CHI
2           Josh Giddey        G           CHI
3          Jevon Carter        G           CHI
4           Jalen Smith      F-C           CHI
5        Nikola Vucevic        C           CHI
6           Ayo Dosunmu        G           CHI
7          Jahmir Young        G           CHI
8          Zach Collins      F-C           CHI
9         Kevin Huerter      G-F           CHI
10        Matas Buzelis        F           CHI
11      Julian Phillips        F           CHI
12       Emanuel Miller        F           CHI
13  Talen Horton-Tucker        G           CHI
14          Dalen Terry        F           CHI
15            Tre Jones        G           CHI
16         E.J. Liddell        F           CHI
17     Patrick Williams        F           CHI

CLE Roster:

          PLAYER_uni POSITION api_team_name
0          Max Strus      G-F           CLE
1          Ty Jerome      G-F           CLE
2        Evan Mobley        C           CLE
3        Sam Merrill        G           CLE
4      Javonte Green        G           CLE
5   Craig Porter Jr.        G           CLE
6     Darius Garland        G           CLE
7    De'Andre Hunter      F-G           CLE
8   Tristan Thompson      C-F           CLE
9        Emoni Bates        F           CLE
10      Jaylon Tyson      G-F           CLE
11   Nae'Qwan Tomlin        F           CLE
12     Jarrett Allen        C           CLE
13         Dean Wade      F-C           CLE
14      Luke Travers        F           CLE
15       Isaac Okoro      F-G           CLE
16  Donovan Mitchell        G           CLE

DET Roster:

           PLAYER_uni POSITION api_team_name
0         Jalen Duren        C           DET
1   Ronald Holland II        F           DET
2     Cade Cunningham        G           DET
3       Malik Beasley        G           DET
4           Paul Reed        F           DET
5    Tim Hardaway Jr.      G-F           DET
6      Ausar Thompson      G-F           DET
7       Tobias Harris        F           DET
8      Ron Harper Jr.      G-F           DET
9     Dennis Schroder        G           DET
10  Simone Fontecchio        F           DET
11         Jaden Ivey        G           DET
12     Daniss Jenkins        G           DET
13      Marcus Sasser        G           DET
14     Isaiah Stewart      F-C           DET
15      Bobi Klintman        F           DET
16         Tolu Smith        F           DET
17   Lindy Waters III        F           DET

IND Roster:

            PLAYER_uni POSITION api_team_name
0    Tyrese Haliburton        G           IND
1   Bennedict Mathurin      G-F           IND
2           Obi Toppin        F           IND
3      Andrew Nembhard      G-F           IND
4        Thomas Bryant      C-F           IND
5        Jarace Walker        F           IND
6      Enrique Freeman        F           IND
7       T.J. McConnell        G           IND
8          RayJ Dennis        G           IND
9        Johnny Furphy        G           IND
10        Tony Bradley      C-F           IND
11       James Johnson        F           IND
12      Isaiah Jackson        F           IND
13       Aaron Nesmith      G-F           IND
14        Ben Sheppard        G           IND
15     Quenton Jackson        G           IND
16        Myles Turner      C-F           IND
17       Pascal Siakam        F           IND

MIL Roster:

               PLAYER_uni POSITION api_team_name
0          Damian Lillard        G           MIL
1            Jericho Sims        C           MIL
2        Kevin Porter Jr.      G-F           MIL
3          Gary Trent Jr.        G           MIL
4        Chris Livingston        F           MIL
5            Bobby Portis        F           MIL
6             Brook Lopez        C           MIL
7          Taurean Prince        F           MIL
8            Ryan Rollins        G           MIL
9          Jamaree Bouyea        G           MIL
10          Stanley Umude        G           MIL
11             Kyle Kuzma        F           MIL
12               AJ Green        G           MIL
13            Tyler Smith        F           MIL
14        Pat Connaughton        G           MIL
15  Giannis Antetokounmpo        F           MIL
16             Pete Nance        F           MIL
17      Andre Jackson Jr.        G           MIL

ATL Roster:

            PLAYER_uni POSITION api_team_name
0         Jacob Toppin        F           ATL
1        Jalen Johnson        F           ATL
2       Keaton Wallace        G           ATL
3         Caris LeVert        G           ATL
4          Kobe Bufkin        G           ATL
5        Dyson Daniels        G           ATL
6   Zaccharie Risacher        F           ATL
7           Trae Young        G           ATL
8         Terance Mann      G-F           ATL
9         Clint Capela        C           ATL
10      Onyeka Okongwu      F-C           ATL
11      Mouhamed Gueye        F           ATL
12       Georges Niang        F           ATL
13     Larry Nance Jr.      F-C           ATL
14    Garrison Mathews        G           ATL
15     Dominick Barlow        F           ATL
16          Vit Krejci        G           ATL
17     Daeqwon Plowden      G-F           ATL

CHA Roster:

           PLAYER_uni POSITION api_team_name
0       Miles Bridges        F           CHA
1         LaMelo Ball        G           CHA
2      Grant Williams        F           CHA
3     DaQuan Jeffries      G-F           CHA
4       Mark Williams        C           CHA
5        Damion Baugh        G           CHA
6      Nick Smith Jr.        G           CHA
7   Wendell Moore Jr.        G           CHA
8          Josh Green        G           CHA
9        Jusuf Nurkic        C           CHA
10        Josh Okogie        G           CHA
11     Moussa Diabate        F           CHA
12           Tre Mann        G           CHA
13     Brandon Miller        F           CHA
14         KJ Simpson        G           CHA
15         Seth Curry        G           CHA
16     Tidjane Salaun        F           CHA
17         Taj Gibson        F           CHA

MIA Roster:

           PLAYER_uni POSITION api_team_name
0      Isaiah Stevens        G           MIA
1        Terry Rozier        G           MIA
2        Nikola Jovic        F           MIA
3         Kel'el Ware        C           MIA
4    Josh Christopher        G           MIA
5       Pelle Larsson        G           MIA
6    Jaime Jaquez Jr.        G           MIA
7           Dru Smith        G           MIA
8         Bam Adebayo      C-F           MIA
9         Tyler Herro        G           MIA
10     Keshad Johnson        F           MIA
11         Alec Burks        G           MIA
12      Kyle Anderson      F-G           MIA
13     Andrew Wiggins        F           MIA
14  Haywood Highsmith        F           MIA
15         Kevin Love      F-C           MIA
16    Davion Mitchell        G           MIA
17    Duncan Robinson        F           MIA

ORL Roster:

                  PLAYER_uni POSITION api_team_name
0              Anthony Black        G           ORL
1             Jonathan Isaac        F           ORL
2              Caleb Houstan        G           ORL
3   Kentavious Caldwell-Pope        G           ORL
4                Jalen Suggs        G           ORL
5             Paolo Banchero        F           ORL
6                Mac McClung        G           ORL
7                Cory Joseph        G           ORL
8             Trevelin Queen        G           ORL
9                Jett Howard        G           ORL
10               Gary Harris        G           ORL
11             Moritz Wagner      F-C           ORL
12              Franz Wagner        F           ORL
13          Tristan da Silva        F           ORL
14        Wendell Carter Jr.      C-F           ORL
15              Goga Bitadze      C-F           ORL
16              Cole Anthony        G           ORL
17            Ethan Thompson        G           ORL

WAS Roster:

           PLAYER_uni POSITION api_team_name
0     Bilal Coulibaly        G           WAS
1    Tristan Vukcevic        F           WAS
2         Colby Jones        G           WAS
3       Jaylen Martin        G           WAS
4          AJ Johnson        G           WAS
5      Bub Carrington        G           WAS
6   Justin Champagnie      G-F           WAS
7        Jordan Poole        G           WAS
8          Saddiq Bey      G-F           WAS
9     Malcolm Brogdon        G           WAS
10       Anthony Gill        F           WAS
11     Kyshawn George        F           WAS
12          Alex Sarr        C           WAS
13            JT Thor        F           WAS
14     Richaun Holmes        F           WAS
15      Corey Kispert        F           WAS
16    Khris Middleton        F           WAS
17       Marcus Smart        G           WAS

DEN Roster:

            PLAYER_uni POSITION api_team_name
0      Christian Braun        G           DEN
1   Michael Porter Jr.        F           DEN
2     Julian Strawther        G           DEN
3    Russell Westbrook        G           DEN
4         Hunter Tyson        F           DEN
5       DeAndre Jordan        C           DEN
6        Peyton Watson        G           DEN
7          Dario Saric      F-C           DEN
8              PJ Hall        C           DEN
9      DaRon Holmes II        F           DEN
10        Nikola Jokic        C           DEN
11       Spencer Jones        F           DEN
12          Zeke Nnaji      F-C           DEN
13      Trey Alexander        G           DEN
14       Jalen Pickett        G           DEN
15        Jamal Murray        G           DEN
16       Vlatko Cancar        F           DEN
17        Aaron Gordon        F           DEN

MIN Roster:

                  PLAYER_uni POSITION api_team_name
0       Terrence Shannon Jr.      G-F           MIN
1           Donte DiVincenzo        G           MIN
2            Jaden McDaniels        F           MIN
3             Rob Dillingham        G           MIN
4            Anthony Edwards        G           MIN
5                 Joe Ingles      F-G           MIN
6                Josh Minott        F           MIN
7   Nickeil Alexander-Walker        G           MIN
8                Mike Conley        G           MIN
9                   Naz Reid      C-F           MIN
10            Tristen Newton        G           MIN
11             Jesse Edwards        C           MIN
12              Jaylen Clark        G           MIN
13               Rudy Gobert        C           MIN
14             Julius Randle      F-C           MIN
15            Leonard Miller        F           MIN
16                Luka Garza        C           MIN
17              Bones Hyland        G           MIN

OKC Roster:

                 PLAYER_uni POSITION api_team_name
0   Shai Gilgeous-Alexander        G           OKC
1              Dillon Jones        F           OKC
2             Luguentz Dort        G           OKC
3           Jaylin Williams        F           OKC
4             Chet Holmgren      C-F           OKC
5            Jalen Williams      G-F           OKC
6               Alex Caruso        G           OKC
7                Isaiah Joe        G           OKC
8             Ousmane Dieng        F           OKC
9              Adam Flagler        G           OKC
10          Branden Carlson        C           OKC
11            Aaron Wiggins        G           OKC
12            Cason Wallace        G           OKC
13            Ajay Mitchell        G           OKC
14         Kenrich Williams      G-F           OKC
15             Nikola Topic        G           OKC
16       Isaiah Hartenstein      C-F           OKC
17               Alex Ducas        G           OKC

POR Roster:

             PLAYER_uni POSITION api_team_name
0       Scoot Henderson        G           POR
1       Anfernee Simons        G           POR
2         Deandre Ayton        C           POR
3      Matisse Thybulle      G-F           POR
4         Dalano Banton        F           POR
5           Deni Avdija        F           POR
6          Jerami Grant        F           POR
7         Justin Minaya        F           POR
8        Bryce McGowens        G           POR
9        Shaedon Sharpe        G           POR
10         Rayan Rupert      G-F           POR
11      Donovan Clingan        C           POR
12          Kris Murray        F           POR
13         Sidy Cissoko        G           POR
14           Duop Reath        C           POR
15       Toumani Camara        F           POR
16        Jabari Walker        F           POR
17  Robert Williams III      C-F           POR

UTA Roster:

          PLAYER_uni POSITION api_team_name
0    Jordan Clarkson        G           UTA
1   Taylor Hendricks        F           UTA
2      Collin Sexton        G           UTA
3     Keyonte George        G           UTA
4      Cody Williams        F           UTA
5     Jaden Springer        G           UTA
6     Isaiah Collier        G           UTA
7    Elijah Harkless        G           UTA
8     Svi Mykhailiuk      G-F           UTA
9       John Collins      F-C           UTA
10   Kyle Filipowski        C           UTA
11   Lauri Markkanen      F-C           UTA
12    Walker Kessler        C           UTA
13      Micah Potter        C           UTA
14  Brice Sensabaugh        F           UTA
15     Johnny Juzang        G           UTA
16    Oscar Tshiebwe      F-C           UTA
17         KJ Martin        F           UTA

GSW Roster:

              PLAYER_uni POSITION api_team_name
0         Gary Payton II        G           GSW
1       Jonathan Kuminga        F           GSW
2        Taran Armstrong        G           GSW
3     Brandin Podziemski        G           GSW
4            Moses Moody        G           GSW
5           Kevon Looney        F           GSW
6            Buddy Hield        G           GSW
7       Jimmy Butler III        F           GSW
8            Braxton Key        F           GSW
9             Gui Santos        F           GSW
10          Quinten Post        C           GSW
11        Draymond Green        F           GSW
12         Stephen Curry        G           GSW
13         Kevin Knox II        F           GSW
14  Trayce Jackson-Davis        F           GSW
15          Jackson Rowe        F           GSW
16           Pat Spencer        G           GSW

LAC Roster:

             PLAYER_uni POSITION api_team_name
0          James Harden        G           LAC
1         Kawhi Leonard        F           LAC
2            Seth Lundy      G-F           LAC
3           Amir Coffey      G-F           LAC
4             Kris Dunn        G           LAC
5       Trentyn Flowers        F           LAC
6     Bogdan Bogdanovic        G           LAC
7         Jordan Miller        G           LAC
8          Cam Christie        G           LAC
9          Drew Eubanks      F-C           LAC
10           Kobe Brown        F           LAC
11  Patrick Baldwin Jr.        F           LAC
12        Norman Powell        G           LAC
13          Ben Simmons      G-F           LAC
14        Nicolas Batum      G-F           LAC
15          Ivica Zubac        C           LAC
16    Derrick Jones Jr.        F           LAC
17          Patty Mills        G           LAC

LAL Roster:

             PLAYER_uni POSITION api_team_name
0     Jarred Vanderbilt        F           LAL
1         Dalton Knecht        F           LAL
2          Gabe Vincent        G           LAL
3          Bronny James        G           LAL
4      Christian Koloko        C           LAL
5          Jaxson Hayes      C-F           LAL
6           Maxi Kleber        F           LAL
7         Austin Reaves        G           LAL
8   Dorian Finney-Smith        F           LAL
9          Shake Milton        G           LAL
10         LeBron James        F           LAL
11             Alex Len        C           LAL
12        Rui Hachimura        F           LAL
13       Jordan Goodwin        G           LAL
14     Trey Jemison III        C           LAL
15          Luka Doncic      F-G           LAL
16      Markieff Morris        F           LAL

PHX Roster:

             PLAYER_uni POSITION api_team_name
0         Royce O'Neale        F           PHX
1             Ryan Dunn        F           PHX
2          Devin Booker        G           PHX
3         Nick Richards        C           PHX
4          Bradley Beal        G           PHX
5          Oso Ighodaro        F           PHX
6         Grayson Allen        G           PHX
7            Damion Lee      G-F           PHX
8               Bol Bol      C-F           PHX
9      Collin Gillespie        G           PHX
10  TyTy Washington Jr.        G           PHX
11        Jalen Bridges        F           PHX
12          Cody Martin        F           PHX
13       Vasilije Micic        G           PHX
14           Tyus Jones        G           PHX
15        Mason Plumlee      F-C           PHX
16         Monte Morris        G           PHX
17         Kevin Durant        F           PHX

SAC Roster:

           PLAYER_uni POSITION api_team_name
0          Malik Monk        G           SAC
1         Isaac Jones        F           SAC
2      Doug McDermott        F           SAC
3         Zach LaVine        G           SAC
4       DeMar DeRozan      G-F           SAC
5    Domantas Sabonis      F-C           SAC
6       Keegan Murray        F           SAC
7         Mason Jones        G           SAC
8   Jonas Valanciunas        C           SAC
9      Markelle Fultz        G           SAC
10       Devin Carter        G           SAC
11         Keon Ellis        G           SAC
12    Isaiah Crawford        F           SAC
13       Jake LaRavia        F           SAC
14         Trey Lyles        F           SAC
15        Jae Crowder        F           SAC

DAL Roster:

                 PLAYER_uni POSITION api_team_name
0                Dante Exum        G           DAL
1              Max Christie        G           DAL
2               Jaden Hardy        G           DAL
3          Dereck Lively II        C           DAL
4             Anthony Davis      F-C           DAL
5             Dwight Powell      F-C           DAL
6   Olivier-Maxence Prosper        F           DAL
7          Brandon Williams        G           DAL
8              Kyrie Irving        G           DAL
9             Naji Marshall        F           DAL
10             Caleb Martin        F           DAL
11          Kessler Edwards        F           DAL
12           Daniel Gafford      F-C           DAL
13                Kai Jones      C-F           DAL
14          P.J. Washington        F           DAL
15        Spencer Dinwiddie        G           DAL
16            Klay Thompson        G           DAL

HOU Roster:

          PLAYER_uni POSITION api_team_name
0      Aaron Holiday        G           HOU
1      Amen Thompson      G-F           HOU
2       Jock Landale        C           HOU
3       N'Faly Dante        C           HOU
4        Jalen Green        G           HOU
5      Fred VanVleet        G           HOU
6       Cam Whitmore        F           HOU
7      Jae'Sean Tate        F           HOU
8      Dillon Brooks      G-F           HOU
9   Jabari Smith Jr.        F           HOU
10      Steven Adams        C           HOU
11     Reed Sheppard        G           HOU
12        Tari Eason        F           HOU
13     Nate Williams        G           HOU
14    Alperen Sengun        C           HOU
15        Jeff Green        F           HOU
16       David Roddy        F           HOU
17      Jack McVeigh      G-F           HOU

MEM Roster:

            PLAYER_uni POSITION api_team_name
0          Zyon Pullin        G           MEM
1         Jaylen Wells        F           MEM
2    Scotty Pippen Jr.        G           MEM
3   Vince Williams Jr.        G           MEM
4         Santi Aldama      F-C           MEM
5        Lamar Stevens        F           MEM
6         Luke Kennard        G           MEM
7            Ja Morant        G           MEM
8    Jaren Jackson Jr.      F-C           MEM
9            Zach Edey        C           MEM
10      Brandon Clarke        F           MEM
11       Yuki Kawamura        G           MEM
12        Desmond Bane        G           MEM
13         Cam Spencer        G           MEM
14            Jay Huff        C           MEM
15   Marvin Bagley III        F           MEM
16          GG Jackson        F           MEM
17        John Konchar        G           MEM

NOP Roster:

                PLAYER_uni POSITION api_team_name
0         Keion Brooks Jr.        F           NOP
1              Bruce Brown      G-F           NOP
2          Zion Williamson        F           NOP
3            Herbert Jones        F           NOP
4              CJ McCollum        G           NOP
5            Elfrid Payton        G           NOP
6          Dejounte Murray        G           NOP
7               Jamal Cain        F           NOP
8           Brandon Boston        G           NOP
9           Antonio Reeves        G           NOP
10            Kelly Olynyk      F-C           NOP
11           Jose Alvarado        G           NOP
12          Karlo Matkovic      F-C           NOP
13              Yves Missi        C           NOP
14         Lester Quinones        G           NOP
15          Jordan Hawkins        G           NOP
16         Trey Murphy III        F           NOP
17  Jeremiah Robinson-Earl        F           NOP

SAS Roster:

               PLAYER_uni POSITION api_team_name
0          Keldon Johnson      F-G           SAS
1       Victor Wembanyama      F-C           SAS
2              Chris Paul        G           SAS
3            De'Aaron Fox        G           SAS
4          Stephon Castle        G           SAS
5          David Duke Jr.        G           SAS
6           Jeremy Sochan        F           SAS
7       Jordan McLaughlin        G           SAS
8            Blake Wesley        G           SAS
9         Bismack Biyombo        C           SAS
10         Malaki Branham        F           SAS
11          Devin Vassell      G-F           SAS
12            Riley Minix        F           SAS
13         Charles Bassey      C-F           SAS
14      Julian Champagnie        F           SAS
15        Harrison Barnes        F           SAS
16  Sandro Mamukelashvili      F-C           SAS
17        Harrison Ingram        F           SAS

In [ ]:


matched_players_list = []
for team_abbr, roster_df in team_rosters.items():
    # print(f"\n{team_abbr} Roster:")
    df_roster = roster_df[['PLAYER', 'PLAYER_uni']]

    if team_abbr in results_pts['team'].values:
        matched_players = df_roster[df_roster['PLAYER_uni'].isin(results_pts['Player'])]
        
        if not matched_players.empty:
            matched_players = matched_players['PLAYER']
            matched_players_list.append(matched_players)
            # display(matched_players)
            # print(matched_players)

# Combine all matched players into a single DataFrame
if matched_players_list:
    final_matched_df = pd.concat(matched_players_list, ignore_index=True)
    display(final_matched_df)  # Display the final combined DataFrame
else:
    print("No matches found.")


from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players

# Retrieve player ID (e.g., LeBron James)
player_list = final_matched_df.tolist()
for basketball_players in player_list:
    found_players = players.find_players_by_full_name(basketball_players)

    if found_players:
        a_player = found_players[0]
        player_id = a_player['id']

        # Fetch game log
        gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')
        games = gamelog.get_data_frames()[0]  # Extract DataFrame
        
        if not games.empty:
            latest_game = games.iloc[0]  # Get the most recent game
            print(f"{basketball_players}: {latest_game['PTS']} points")
        else:
            print(f"{basketball_players}: No game data available")

    else:
        print(f"Player not found: {basketball_players}")

In [ ]:

# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

# results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != 100.00]
# df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
#     .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
#     .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))

# df_merged = df_merged[df_merged["Player"] != 'Tyrese Haliburton']


# print(df_merged.columns)


# df_merged['middlebet_PTS+REB'] = 0000

# df_merged['PTS+REB'] = df_merged[['middlebet_PTS', 'middlebet_REB']].sum(axis=1)
# df_merged['confidence_level_PTS+REB']=  round(df_merged[['confidence_level_PTS','confidence_level_REB']].sum(axis=1)/2,2)
# df_merged = df_merged.rename(columns={'FGA': 'PTS'})
# display(df_merged)
# display(df_merged[['Player','confidence_level_PTS+REB']])


from parlay_picker import create_parlays, create_parlays_high

num_groups = 10  # Number of parlays you want to generate
players_per_group = 40  # Number of players in each parlay
min_confidence = 20

parlays_df, group_confidence_scores = create_parlays_high(df_merged, num_groups, players_per_group,min_confidence, 70)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")

In [ ]:
# Gets you player names
import pandas as pd

target = ["BOS","MEM", "CHI", "OKC", "BKN", "DAL", "HOU", "LAL"]
df_list = []  # List to store dataframes
for team in target:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path



    # Iterate through all files in the directory
    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Append DataFrame to the list




        # Concatenate all the box score dataframes into one
        df= pd.concat(df_list, ignore_index=True)
        


        df =df['PLAYER_uni'].tolist()

list_of_names = df
print(list_of_names)

In [ ]:
# checks if player from roster is in history
import os

target = ["BOS","MEM", "CHI", "OKC", "BKN", "DAL", "HOU", "LAL"]
df_list = []  # List to store dataframes
for team in target:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path



    # Iterate through all files in the directory
    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Append DataFrame to the list




        # Concatenate all the box score dataframes into one
        df= pd.concat(df_list, ignore_index=True)
        


        df =df['PLAYER_uni'].tolist()


list_of_names = df




unavaliable_names = []
for name in list_of_names:
    file_path = f"D:/nba_player_historic/nba_html_2023-24/{name}_content.html"
    # print(file_path)

    if os.path.exists(file_path):
        print("File exists! ")
    else:
        print("File does not exist.")
        unavaliable_names.append(name)

print(unavaliable_names)

In [ ]:
# this gets player and their team and put into a dictionary 
import os
import pandas as pd

# List of target teams
target = ["BOS", "MEM", "CHI", "OKC", "BKN", "DAL", "HOU", "LAL"]
df_list = []  # List to store DataFrames

# Loop through each team's roster file
for team in target:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path

    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Store DataFrame in list
    else:
        print(f"File not found: {roster_path}")  # Debugging message

# Combine all DataFrames if any were found
if df_list:
    df_combined = pd.concat(df_list, ignore_index=True)

    # Extract two columns as a dictionary
    player_dict = dict(zip(df_combined['PLAYER_uni'], df_combined['api_team_name']))

    print(player_dict)  # Display dictionary
else:
    print("No valid roster files found.")