In [7]:
from prediction import prediction

players_teams = {
    "Miles McBride": "NYK",
    "Mikal Bridges": "NYK",
    "Josh Hart": "NYK",
    "O.G. Anunoby": "NYK",
    "Karl-Anthony Towns": "NYK",
    "Josh Green": "CHA",
    "DaQuan Jeffries": "CHA",
    "LaMelo Ball": "CHA",
    "Miles Bridges": "CHA",
    "Mark Williams": "CHA",
    "Keon Johnson": "BKN",
    "Ziaire Williams": "BKN",
    "D'Angelo Russell": "BKN",
    "Jalen Wilson": "BKN",
    "Nic Claxton": "BKN",
    "Andrew Nembhard": "IND",
    "Aaron Nesmith": "IND",
    "Tyrese Haliburton": "IND",
    "Pascal Siakam": "IND",
    "Myles Turner": "IND",
    "Jamison Battle": "TOR",
    "Scottie Barnes": "TOR",
    "Immanuel Quickley": "TOR",
    "Jonathan Mogbo": "TOR",
    "Jakob Poeltl": "TOR",
    "Brandin Podziemski": "GSW",
    "Moses Moody": "GSW",
    "Stephen Curry": "GSW",
    "Jimmy Butler III": "GSW",
    "Draymond Green": "GSW",
    "Coby White": "CHI",
    "Kevin Huerter": "CHI",
    "Tre Jones": "CHI",
    "Matas Buzelis": "CHI",
    "Nikola Vucevic": "CHI",
    "Zach LaVine": "SAC",
    "DeMar DeRozan": "SAC",
    "Malik Monk": "SAC",
    "Keegan Murray": "SAC",
    "Jonas Valanciunas": "SAC",
    "Taurean Prince": "MIL",
    "Kyle Kuzma": "MIL",
    "Damian Lillard": "MIL",
    "Giannis Antetokounmpo": "MIL",
    "Brook Lopez": "MIL",
    "Gabe Vincent": "LAL",
    "Jordan Goodwin": "LAL",
    "Shake Milton": "LAL",
    "Dalton Knecht": "LAL",
    "Jaxson Hayes": "LAL"
}









# remember to run mover
# remember to check schedule csv
import pandas as pd
date_list = ["2022-23","2023-24","2024-25"]
stats_path = {
    'usage_path':'D:/nba_usage_csv_historic/usage_csv_{date}/{date}_content.csv',
    'catch_shoot':"D:/nba_tracking_data_csv/nba_csv_{date}/catch_shoot_content.csv",
    'drives':"D:/nba_tracking_data_csv/nba_csv_{date}/drives_content.csv",
    'elbow_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/elbow_touch_content.csv",
    'paint_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/paint_touch_content.csv",
    'passing':"D:/nba_tracking_data_csv/nba_csv_{date}/passing_content.csv",
    'pullup':"D:/nba_tracking_data_csv/nba_csv_{date}/pullup_content.csv",
    'shooting_efficiency':"D:/nba_tracking_data_csv/nba_csv_{date}/shooting_efficiency_content.csv",
    'touches':"D:/nba_tracking_data_csv/nba_csv_{date}/touches_content.csv",
    'tracking_post_ups_content':"D:/nba_tracking_data_csv/nba_csv_{date}/tracking_post_ups_content.csv"
}
schedule_base_path = "D:/nba_scheduled_csv/schedule_csv_2025/{schedule_team}_schedule_content.csv"
player_base_path = "D:/nba_player_csv_historic/season_{date}/all_quarters/{player}_content.csv"
defense_base_path = "D:/nba_defense_history_csv/defense_csv_{date}/all_quarter_defense_content.csv"

results_reb = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'REB','REB')
results_ast = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'AST','AST')
results_pts = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'PTS','PTS')
results_3pm = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'3PM','3PM')
results_pts = results_pts.rename(columns={'FGA': 'PTS'})



# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

Player data missing for O.G. Anunoby on 2022-23, skipping.
Skipping merge for O.G. Anunoby on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for DaQuan Jeffries on 2022-23, skipping.
Skipping merge for DaQuan Jeffries on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Miles Bridges on 2022-23, skipping.
Skipping merge for Miles Bridges on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jalen Wilson on 2022-23, skipping.
Skipping merge for Jalen Wilson on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2022-23, skipping.
Skipping merge for Jamison Battle on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2022-23, skipping.
Skipping merge for Jonathan Mogbo on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2023-24, skipping.
Skipping merge for Jonathan Mogbo on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandin Podziemski on 2022-23, skipping.
Skipping merge for Brandin Podziemski on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Shake Milton on 2022-23, skipping.
Skipping merge for Shake Milton on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2022-23, skipping.
Skipping merge for Dalton Knecht on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2023-24, skipping.
Skipping merge for Dalton Knecht on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for O.G. Anunoby on 2022-23, skipping.
Skipping merge for O.G. Anunoby on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for DaQuan Jeffries on 2022-23, skipping.
Skipping merge for DaQuan Jeffries on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Miles Bridges on 2022-23, skipping.
Skipping merge for Miles Bridges on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jalen Wilson on 2022-23, skipping.
Skipping merge for Jalen Wilson on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2022-23, skipping.
Skipping merge for Jamison Battle on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2022-23, skipping.
Skipping merge for Jonathan Mogbo on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2023-24, skipping.
Skipping merge for Jonathan Mogbo on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandin Podziemski on 2022-23, skipping.
Skipping merge for Brandin Podziemski on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Shake Milton on 2022-23, skipping.
Skipping merge for Shake Milton on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2022-23, skipping.
Skipping merge for Dalton Knecht on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2023-24, skipping.
Skipping merge for Dalton Knecht on 2023-24 due to missing data.
defense data skipping defense merge
No rows found for TEAM: GSW for Jamison Battle using last game features
No rows found for TEAM: GSW for Jonathan Mogbo using last game features
No rows found for TEAM: SAC for Kevin Huerter using last game features
No rows found for TEAM: CHI for Zach LaVine using last game features
Player data missing for O.G. Anunoby on 2022-23, skipping.
Skipping merge for O.G. Anunoby on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for DaQuan Jeffries on 2022-23, skipping.
Skipping merge for DaQuan Jeffries on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Miles Bridges on 2022-23, skipping.
Skipping merge for Miles Bridges on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jalen Wilson on 2022-23, skipping.
Skipping merge for Jalen Wilson on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2022-23, skipping.
Skipping merge for Jamison Battle on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2022-23, skipping.
Skipping merge for Jonathan Mogbo on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2023-24, skipping.
Skipping merge for Jonathan Mogbo on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandin Podziemski on 2022-23, skipping.
Skipping merge for Brandin Podziemski on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Shake Milton on 2022-23, skipping.
Skipping merge for Shake Milton on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2022-23, skipping.
Skipping merge for Dalton Knecht on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2023-24, skipping.
Skipping merge for Dalton Knecht on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for O.G. Anunoby on 2022-23, skipping.
Skipping merge for O.G. Anunoby on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for DaQuan Jeffries on 2022-23, skipping.
Skipping merge for DaQuan Jeffries on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Miles Bridges on 2022-23, skipping.
Skipping merge for Miles Bridges on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jalen Wilson on 2022-23, skipping.
Skipping merge for Jalen Wilson on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2022-23, skipping.
Skipping merge for Jamison Battle on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2022-23, skipping.
Skipping merge for Jonathan Mogbo on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2023-24, skipping.
Skipping merge for Jonathan Mogbo on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandin Podziemski on 2022-23, skipping.
Skipping merge for Brandin Podziemski on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Shake Milton on 2022-23, skipping.
Skipping merge for Shake Milton on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2022-23, skipping.
Skipping merge for Dalton Knecht on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2023-24, skipping.
Skipping merge for Dalton Knecht on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.105e-02, tolerance: 1.918e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.405e-02, tolerance: 1.889e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.393e+01, tolerance: 7.420e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.408e+01, tolerance: 7.216e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.822e+01, tolerance: 7.756e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.059e+00, tolerance: 2.013e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.688e-01, tolerance: 6.942e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.813e+00, tolerance: 9.346e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.773e-02, tolerance: 4.088e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.983e-02, tolerance: 3.139e-02
  model = cd_fast.enet_coordinate_descent(

No rows found for TEAM: GSW for Jamison Battle using last game features
No rows found for TEAM: GSW for Jonathan Mogbo using last game features
No rows found for TEAM: SAC for Kevin Huerter using last game features
No rows found for TEAM: CHI for Zach LaVine using last game features
Player data missing for O.G. Anunoby on 2022-23, skipping.
Skipping merge for O.G. Anunoby on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for DaQuan Jeffries on 2022-23, skipping.
Skipping merge for DaQuan Jeffries on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Miles Bridges on 2022-23, skipping.
Skipping merge for Miles Bridges on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jalen Wilson on 2022-23, skipping.
Skipping merge for Jalen Wilson on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2022-23, skipping.
Skipping merge for Jamison Battle on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2022-23, skipping.
Skipping merge for Jonathan Mogbo on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2023-24, skipping.
Skipping merge for Jonathan Mogbo on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandin Podziemski on 2022-23, skipping.
Skipping merge for Brandin Podziemski on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Shake Milton on 2022-23, skipping.
Skipping merge for Shake Milton on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2022-23, skipping.
Skipping merge for Dalton Knecht on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2023-24, skipping.
Skipping merge for Dalton Knecht on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for O.G. Anunoby on 2022-23, skipping.
Skipping merge for O.G. Anunoby on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for DaQuan Jeffries on 2022-23, skipping.
Skipping merge for DaQuan Jeffries on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Miles Bridges on 2022-23, skipping.
Skipping merge for Miles Bridges on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jalen Wilson on 2022-23, skipping.
Skipping merge for Jalen Wilson on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2022-23, skipping.
Skipping merge for Jamison Battle on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2022-23, skipping.
Skipping merge for Jonathan Mogbo on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2023-24, skipping.
Skipping merge for Jonathan Mogbo on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandin Podziemski on 2022-23, skipping.
Skipping merge for Brandin Podziemski on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Shake Milton on 2022-23, skipping.
Skipping merge for Shake Milton on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2022-23, skipping.
Skipping merge for Dalton Knecht on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2023-24, skipping.
Skipping merge for Dalton Knecht on 2023-24 due to missing data.
defense data skipping defense merge
No rows found for TEAM: GSW for Jamison Battle using last game features
No rows found for TEAM: GSW for Jonathan Mogbo using last game features
No rows found for TEAM: SAC for Kevin Huerter using last game features
No rows found for TEAM: CHI for Zach LaVine using last game features
Player data missing for O.G. Anunoby on 2022-23, skipping.
Skipping merge for O.G. Anunoby on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for DaQuan Jeffries on 2022-23, skipping.
Skipping merge for DaQuan Jeffries on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Miles Bridges on 2022-23, skipping.
Skipping merge for Miles Bridges on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jalen Wilson on 2022-23, skipping.
Skipping merge for Jalen Wilson on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2022-23, skipping.
Skipping merge for Jamison Battle on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2022-23, skipping.
Skipping merge for Jonathan Mogbo on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2023-24, skipping.
Skipping merge for Jonathan Mogbo on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandin Podziemski on 2022-23, skipping.
Skipping merge for Brandin Podziemski on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Shake Milton on 2022-23, skipping.
Skipping merge for Shake Milton on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2022-23, skipping.
Skipping merge for Dalton Knecht on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2023-24, skipping.
Skipping merge for Dalton Knecht on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for O.G. Anunoby on 2022-23, skipping.
Skipping merge for O.G. Anunoby on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for DaQuan Jeffries on 2022-23, skipping.
Skipping merge for DaQuan Jeffries on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Miles Bridges on 2022-23, skipping.
Skipping merge for Miles Bridges on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jalen Wilson on 2022-23, skipping.
Skipping merge for Jalen Wilson on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2022-23, skipping.
Skipping merge for Jamison Battle on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2022-23, skipping.
Skipping merge for Jonathan Mogbo on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jonathan Mogbo on 2023-24, skipping.
Skipping merge for Jonathan Mogbo on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Brandin Podziemski on 2022-23, skipping.
Skipping merge for Brandin Podziemski on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Shake Milton on 2022-23, skipping.
Skipping merge for Shake Milton on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2022-23, skipping.
Skipping merge for Dalton Knecht on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Dalton Knecht on 2023-24, skipping.
Skipping merge for Dalton Knecht on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:215: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:215: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

No rows found for TEAM: GSW for Jamison Battle using last game features
No rows found for TEAM: GSW for Jonathan Mogbo using last game features

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:215: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

No rows found for TEAM: SAC for Kevin Huerter using last game features
No rows found for TEAM: CHI for Zach LaVine using last game features

In [ ]:

# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != '100.00']
df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
    .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
    .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))

results_3pm = results_3pm[results_3pm["Player"] != 'Tyrese Haliburton']



# print(df_merged.columns)


# df_merged['middlebet_PTS+REB'] = 0000

# df_merged['PTS+REB'] = df_merged[['middlebet_PTS', 'middlebet_REB']].sum(axis=1)
# df_merged['confidence_level_PTS+REB']=  round(df_merged[['confidence_level_PTS','confidence_level_REB']].sum(axis=1)/2,2)
# df_merged = df_merged.rename(columns={'FGA': 'PTS'})
# display(df_merged)
# display(df_merged[['Player','confidence_level_PTS+REB']])


from parlay_picker import create_parlays

num_groups = 10  # Number of parlays you want to generate
players_per_group = 7 # Number of players in each parlay
min_confidence = 50
threepm_confidence = 40

parlays_df, group_confidence_scores = create_parlays(df_merged, num_groups, players_per_group,min_confidence)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")

Confidence scores for each group:
Parlay 1: 57.70
Parlay 2: 64.63
Parlay 3: 60.11
Parlay 4: 62.27
Parlay 5: 56.73
Parlay 6: 64.87
Parlay 7: 65.20


Parlay 1: total confidence score: 57.70

               Player team Stat    Stat Range  Confidence                               recentgames
0  Karl-Anthony Towns  NYK  REB  10 - 16 - 21       62.69       [9, 7, 12, 7, 9, 10, 14, 16, 7, 18]
1  Karl-Anthony Towns  NYK  PTS  16 - 27 - 37       59.88  [32, 23, 29, 21, 26, 23, 12, 19, 11, 24]
2           Josh Hart  NYK  REB   5 - 10 - 14       59.25        [7, 13, 7, 11, 6, 20, 10, 8, 7, 4]
3        O.G. Anunoby  NYK  PTS  14 - 24 - 33       59.10   [14, 9, 23, 23, 24, 11, 20, 29, 23, 19]
4           Josh Hart  NYK  AST     3 - 6 - 8       55.04           [7, 11, 7, 9, 3, 6, 2, 3, 3, 6]
5       Mikal Bridges  NYK  PTS  10 - 19 - 27       54.04    [14, 28, 19, 33, 15, 22, 6, 15, 5, 15]
6       Mikal Bridges  NYK  AST     2 - 4 - 5       53.93            [7, 3, 3, 4, 8, 5, 3, 4, 8, 3]

Parlay 2: total confidence score: 64.63

          Player team Stat    Stat Range  Confidence                              recentgames
0  Mark Williams  CHA  3PM     0 - 0 - 0      100.00           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
1  Miles Bridges  CHA  REB   6 - 10 - 13       65.80        [4, 7, 11, 5, 12, 8, 9, 9, 7, 12]
2  Mark Williams  CHA  REB     2 - 4 - 5       64.71   [5, 15, 10, 14, 10, 8, 13, 12, 16, 12]
3    LaMelo Ball  CHA  PTS  20 - 34 - 47       61.18  [16, 27, 25, 15, 13, 28, 25, 20, 13, 5]
4  Miles Bridges  CHA  PTS  11 - 20 - 28       56.50  [7, 21, 31, 35, 26, 46, 23, 35, 18, 20]
5    LaMelo Ball  CHA  AST    4 - 8 - 11       53.04         [5, 15, 9, 10, 7, 6, 7, 3, 9, 2]
6  Mark Williams  CHA  PTS     3 - 6 - 8       51.18  [4, 18, 14, 14, 24, 12, 12, 24, 26, 12]

Parlay 3: total confidence score: 60.11

              Player team Stat    Stat Range  Confidence                               recentgames
0      Pascal Siakam  IND  PTS  12 - 19 - 25       68.05  [29, 26, 27, 25, 13, 23, 35, 18, 20, 36]
1  Tyrese Haliburton  IND  AST    5 - 8 - 10       67.69   [15, 10, 10, 15, 12, 10, 11, 15, 12, 9]
2       Myles Turner  IND  PTS   6 - 10 - 13       65.38   [9, 14, 18, 13, 15, 14, 17, 16, 16, 22]
3  Tyrese Haliburton  IND  PTS  13 - 22 - 30       61.48  [24, 14, 14, 28, 17, 19, 33, 19, 29, 22]
4      Pascal Siakam  IND  AST     1 - 2 - 2       55.36            [5, 2, 4, 5, 4, 3, 3, 2, 4, 2]
5      Pascal Siakam  IND  REB     3 - 6 - 8       51.48           [1, 7, 7, 12, 1, 7, 9, 2, 6, 6]
6  Tyrese Haliburton  IND  3PM     2 - 4 - 5       51.31            [2, 2, 2, 5, 2, 3, 7, 5, 4, 4]

Parlay 4: total confidence score: 62.27

             Player team Stat    Stat Range  Confidence                               recentgames
0    Draymond Green  GSW  AST     4 - 7 - 9       68.21           [4, 5, 3, 4, 7, 7, 10, 8, 7, 8]
1  Jimmy Butler III  GSW  AST     3 - 5 - 6       66.74          [10, 6, 7, 7, 10, 5, 6, 4, 4, 7]
2     Stephen Curry  GSW  PTS  17 - 26 - 34       65.41  [20, 28, 11, 24, 32, 40, 28, 21, 29, 56]
3       Moses Moody  GSW  PTS     0 - 1 - 1       61.51      [7, 9, 18, 17, 20, 12, 10, 9, 5, 10]
4  Jimmy Butler III  GSW  PTS   6 - 11 - 15       59.36    [24, 23, 11, 6, 15, 26, 25, 19, 13, 5]
5    Draymond Green  GSW  REB   7 - 13 - 18       58.13          [10, 6, 4, 4, 4, 9, 7, 9, 12, 8]
6     Stephen Curry  GSW  AST     3 - 6 - 8       56.56          [7, 5, 5, 3, 4, 4, 9, 10, 13, 3]

Parlay 5: total confidence score: 56.73

           Player team Stat    Stat Range  Confidence                               recentgames
0  Nikola Vucevic  CHI  REB     4 - 6 - 7       68.65        [6, 10, 7, 3, 11, 11, 9, 14, 7, 4]
1      Coby White  CHI  PTS  22 - 36 - 49       61.20  [24, 26, 23, 31, 29, 21, 44, 25, 26, 24]
2  Nikola Vucevic  CHI  PTS  10 - 18 - 25       61.07    [24, 10, 15, 7, 11, 16, 21, 21, 8, 10]
3   Matas Buzelis  CHI  PTS     2 - 5 - 7       58.62     [5, 17, 10, 6, 8, 13, 11, 17, 18, 10]
4      Coby White  CHI  AST     3 - 6 - 8       53.25            [5, 4, 4, 4, 4, 3, 1, 7, 1, 3]
5      Coby White  CHI  REB     2 - 5 - 7       51.28            [6, 3, 7, 7, 7, 3, 5, 4, 7, 4]
6       Tre Jones  CHI  3PM     0 - 0 - 0       43.01            [0, 1, 2, 1, 0, 1, 1, 1, 0, 0]

Parlay 6: total confidence score: 64.87

          Player team Stat    Stat Range  Confidence                               recentgames
0     Malik Monk  SAC  PTS  11 - 17 - 22       68.89   [22, 28, 18, 7, 21, 13, 16, 13, 13, 13]
1  Keegan Murray  SAC  REB     3 - 5 - 6       67.52            [4, 9, 8, 4, 2, 6, 9, 3, 5, 5]
2    Zach LaVine  SAC  PTS  14 - 21 - 27       67.39  [23, 21, 14, 17, 30, 36, 20, 22, 20, 22]
3  DeMar DeRozan  SAC  PTS  13 - 20 - 26       67.20  [27, 22, 23, 23, 11, 31, 22, 35, 20, 21]
4     Malik Monk  SAC  AST     3 - 6 - 8       65.62           [8, 7, 5, 6, 3, 8, 4, 6, 10, 4]
5  Keegan Murray  SAC  PTS   8 - 14 - 19       58.84     [13, 16, 14, 6, 9, 15, 19, 6, 18, 13]
6  DeMar DeRozan  SAC  AST     2 - 4 - 5       58.63           [4, 8, 1, 7, 5, 10, 7, 5, 4, 6]

Parlay 7: total confidence score: 65.20

                  Player team Stat    Stat Range  Confidence                               recentgames
0  Giannis Antetokounmpo  MIL  PTS  18 - 24 - 29       77.24  [20, 21, 34, 24, 19, 30, 37, 32, 26, 29]
1  Giannis Antetokounmpo  MIL  REB   8 - 12 - 15       71.45     [9, 12, 10, 12, 17, 9, 11, 15, 12, 9]
2         Damian Lillard  MIL  PTS  15 - 22 - 28       68.66  [16, 19, 25, 22, 15, 22, 26, 34, 23, 28]
3             Kyle Kuzma  MIL  PTS     2 - 4 - 5       64.98     [22, 10, 8, 5, 9, 14, 11, 17, 17, 10]
4  Giannis Antetokounmpo  MIL  AST     3 - 5 - 6       60.43          [7, 10, 7, 9, 7, 3, 4, 4, 10, 9]
5         Damian Lillard  MIL  AST    3 - 7 - 10       57.11          [4, 2, 8, 10, 11, 4, 4, 5, 4, 6]
6            Brook Lopez  MIL  PTS  12 - 22 - 31       56.55      [16, 8, 10, 23, 23, 7, 8, 2, 13, 13]

:

In [5]:

# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != '100.00']
df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
    .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
    .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))

df_merged = df_merged[df_merged["Player"] != 'Tyrese Haliburton']


# print(df_merged.columns)


# df_merged['middlebet_PTS+REB'] = 0000

# df_merged['PTS+REB'] = df_merged[['middlebet_PTS', 'middlebet_REB']].sum(axis=1)
# df_merged['confidence_level_PTS+REB']=  round(df_merged[['confidence_level_PTS','confidence_level_REB']].sum(axis=1)/2,2)
# df_merged = df_merged.rename(columns={'FGA': 'PTS'})
# display(df_merged)
# display(df_merged[['Player','confidence_level_PTS+REB']])


from parlay_picker import create_parlays, create_parlays_high

num_groups = 10  # Number of parlays you want to generate
players_per_group = 7  # Number of players in each parlay
min_confidence = 70

parlays_df, group_confidence_scores = create_parlays_high(df_merged, num_groups, players_per_group,min_confidence)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")

Confidence scores for each group:
Parlay 1: 79.96
Parlay 2: 71.65
Parlay 3: 71.01
Parlay 4: 70.73


Parlay 1: total confidence score: 79.96

                  Player Team Stat    Stat Range  Confidence                              Recent Games
0           Jakob Poeltl  TOR  PTS   9 - 10 - 10       93.71     [19, 9, 21, 17, 16, 10, 10, 5, 10, 8]
1           Gabe Vincent  LAL  PTS   9 - 10 - 10       90.65        [12, 11, 9, 6, 24, 2, 12, 2, 9, 7]
2           Jaxson Hayes  LAL  3PM     0 - 0 - 0      100.00            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
3          Matas Buzelis  CHI  PTS     1 - 2 - 2       72.67     [5, 17, 10, 6, 8, 13, 11, 17, 18, 10]
4  Giannis Antetokounmpo  MIL  PTS  11 - 15 - 18       77.51  [20, 21, 34, 24, 19, 30, 37, 32, 26, 29]
5             Malik Monk  SAC  PTS  10 - 14 - 17       75.69   [22, 28, 18, 7, 21, 13, 16, 13, 13, 13]
6           O.G. Anunoby  NYK  3PM     1 - 3 - 4       49.47            [2, 1, 2, 3, 3, 2, 4, 4, 4, 4]

Parlay 2: total confidence score: 71.65

          Player Team Stat    Stat Range  Confidence                              Recent Games
0    Nic Claxton  BKN  3PM     0 - 0 - 0      100.00            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
1  Mikal Bridges  NYK  PTS  10 - 15 - 19       72.20    [14, 28, 19, 33, 15, 22, 6, 15, 5, 15]
2    Zach LaVine  SAC  PTS  11 - 16 - 20       70.48  [23, 21, 14, 17, 30, 36, 20, 22, 20, 22]
3    LaMelo Ball  CHA  PTS  18 - 21 - 23       86.80   [16, 27, 25, 15, 13, 28, 25, 20, 13, 5]
4  Stephen Curry  GSW  3PM     1 - 3 - 4       51.63           [4, 4, 2, 5, 4, 7, 5, 3, 5, 12]
5  Keegan Murray  SAC  3PM     0 - 2 - 3       48.26            [3, 3, 2, 2, 1, 3, 3, 0, 4, 2]
6  Miles Bridges  CHA  PTS  13 - 19 - 24       72.18   [7, 21, 31, 35, 26, 46, 23, 35, 18, 20]

Parlay 3: total confidence score: 71.01

                  Player Team Stat    Stat Range  Confidence                              Recent Games
0             Coby White  CHI  PTS  17 - 24 - 30       73.56  [24, 26, 23, 31, 29, 21, 44, 25, 26, 24]
1           O.G. Anunoby  NYK  PTS  16 - 18 - 19       93.71   [14, 9, 23, 23, 24, 11, 20, 29, 23, 19]
2            Moses Moody  GSW  PTS     2 - 4 - 5       73.82      [7, 9, 18, 17, 20, 12, 10, 9, 5, 10]
3  Giannis Antetokounmpo  MIL  REB   8 - 12 - 15       71.45     [9, 12, 10, 12, 17, 9, 11, 15, 12, 9]
4  Giannis Antetokounmpo  MIL  3PM     0 - 0 - 0       41.51            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
5              Tre Jones  CHI  3PM     0 - 0 - 0       43.01            [0, 1, 2, 1, 0, 1, 1, 1, 0, 0]
6          Mark Williams  CHA  3PM     0 - 0 - 0      100.00            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Parlay 4: total confidence score: 70.73

           Player Team Stat    Stat Range  Confidence                              Recent Games
0  Jordan Goodwin  LAL  3PM     0 - 0 - 0       46.86            [0, 3, 0, 2, 0, 5, 2, 0, 1, 0]
1      Kyle Kuzma  MIL  PTS    5 - 8 - 10       71.31     [22, 10, 8, 5, 9, 14, 11, 17, 17, 10]
2   Keegan Murray  SAC  PTS   7 - 10 - 12       74.23     [13, 16, 14, 6, 9, 15, 19, 6, 18, 13]
3  Damian Lillard  MIL  PTS  12 - 16 - 19       75.10  [16, 19, 25, 22, 15, 22, 26, 34, 23, 28]
4   Pascal Siakam  IND  PTS  12 - 15 - 17       81.29  [29, 26, 27, 25, 13, 23, 35, 18, 20, 36]
5  Scottie Barnes  TOR  PTS  20 - 21 - 21       96.92  [16, 16, 20, 14, 18, 22, 17, 10, 24, 21]
6  Damian Lillard  MIL  3PM     0 - 2 - 3       49.42            [2, 2, 6, 2, 2, 1, 4, 5, 2, 4]