In [99]:
from prediction import prediction

import os
import pandas as pd

# List of target teams
matchup = ["SAC","WAS", "CHA", "IND", "NYK", "CLE", "MIA", 
            "BOS", "UTA", "HOU", "ATL", "DAL", "SAS","DEN",
            "DET", "OKC", "NOP", "LAC"]
df_list = []  # List to store DataFrames

# Loop through each team's roster file
for team in matchup:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path

    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Store DataFrame in list
    else:
        print(f"File not found: {roster_path}")  # Debugging message

# Combine all DataFrames if any were found
if df_list:
    df_combined = pd.concat(df_list, ignore_index=True)

    # Extract two columns as a dictionary
    player_dict = dict(zip(df_combined['PLAYER_uni'], df_combined['api_team_name']))

    print(player_dict)  # Display dictionary
else:
    print("No valid roster files found.")





# remember to run mover
# remember to check schedule csv
import pandas as pd
date_list = ["2023-24","2024-25"]
stats_path = {
    'usage_path':'D:/nba_usage_csv_historic/usage_csv_{date}/{date}_content.csv',
    'catch_shoot':"D:/nba_tracking_data_csv/nba_csv_{date}/catch_shoot_content.csv",
    'drives':"D:/nba_tracking_data_csv/nba_csv_{date}/drives_content.csv",
    'elbow_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/elbow_touch_content.csv",
    'paint_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/paint_touch_content.csv",
    'passing':"D:/nba_tracking_data_csv/nba_csv_{date}/passing_content.csv",
    'pullup':"D:/nba_tracking_data_csv/nba_csv_{date}/pullup_content.csv",
    'shooting_efficiency':"D:/nba_tracking_data_csv/nba_csv_{date}/shooting_efficiency_content.csv",
    'touches':"D:/nba_tracking_data_csv/nba_csv_{date}/touches_content.csv",
    'tracking_post_ups_content':"D:/nba_tracking_data_csv/nba_csv_{date}/tracking_post_ups_content.csv"
}
schedule_base_path = "D:/nba_scheduled_csv/schedule_csv_2025/{schedule_team}_schedule_content.csv"
player_base_path = "D:/nba_player_csv_historic/season_{date}/all_quarters/{player}_content.csv"
defense_base_path = "D:/nba_defense_history_csv/defense_csv_{date}/all_quarter_defense_content.csv"

results_reb = prediction(player_dict, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'REB','REB')
results_ast = prediction(player_dict, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'AST','AST')
results_pts = prediction(player_dict, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'PTS','PTS')
results_3pm = prediction(player_dict, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'3PM','3PM')
results_pts = results_pts.rename(columns={'FGA': 'PTS'})



# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

{'Malik Monk': 'SAC', 'Isaac Jones': 'SAC', 'Doug McDermott': 'SAC', 'Zach LaVine': 'SAC', 'DeMar DeRozan': 'SAC', 'Domantas Sabonis': 'SAC', 'Keegan Murray': 'SAC', 'Mason Jones': 'SAC', 'Jonas Valanciunas': 'SAC', 'Markelle Fultz': 'SAC', 'Devin Carter': 'SAC', 'Keon Ellis': 'SAC', 'Isaiah Crawford': 'SAC', 'Jake LaRavia': 'SAC', 'Trey Lyles': 'SAC', 'Jae Crowder': 'SAC', 'Bilal Coulibaly': 'WAS', 'Tristan Vukcevic': 'WAS', 'Colby Jones': 'WAS', 'Jaylen Martin': 'WAS', 'AJ Johnson': 'WAS', 'Bub Carrington': 'WAS', 'Justin Champagnie': 'WAS', 'Jordan Poole': 'WAS', 'Saddiq Bey': 'WAS', 'Malcolm Brogdon': 'WAS', 'Anthony Gill': 'WAS', 'Kyshawn George': 'WAS', 'Alex Sarr': 'WAS', 'JT Thor': 'WAS', 'Richaun Holmes': 'WAS', 'Corey Kispert': 'WAS', 'Khris Middleton': 'WAS', 'Marcus Smart': 'WAS', 'Miles Bridges': 'CHA', 'LaMelo Ball': 'CHA', 'Grant Williams': 'CHA', 'DaQuan Jeffries': 'CHA', 'Mark Williams': 'CHA', 'Damion Baugh': 'CHA', 'Nick Smith Jr.': 'CHA', 'Wendell Moore Jr.': 'CHA', 'Josh Green': 'CHA', 'Jusuf Nurkic': 'CHA', 'Josh Okogie': 'CHA', 'Moussa Diabate': 'CHA', 'Tre Mann': 'CHA', 'Brandon Miller': 'CHA', 'KJ Simpson': 'CHA', 'Seth Curry': 'CHA', 'Tidjane Salaun': 'CHA', 'Taj Gibson': 'CHA', 'Tyrese Haliburton': 'IND', 'Bennedict Mathurin': 'IND', 'Obi Toppin': 'IND', 'Andrew Nembhard': 'IND', 'Thomas Bryant': 'IND', 'Jarace Walker': 'IND', 'Enrique Freeman': 'IND', 'T.J. McConnell': 'IND', 'RayJ Dennis': 'IND', 'Johnny Furphy': 'IND', 'Tony Bradley': 'IND', 'James Johnson': 'IND', 'Isaiah Jackson': 'IND', 'Aaron Nesmith': 'IND', 'Ben Sheppard': 'IND', 'Quenton Jackson': 'IND', 'Myles Turner': 'IND', 'Pascal Siakam': 'IND', 'Delon Wright': 'NYK', 'MarJon Beauchamp': 'NYK', 'P.J. Tucker': 'NYK', 'Cameron Payne': 'NYK', 'Miles McBride': 'NYK', 'Josh Hart': 'NYK', 'Pacome Dadiet': 'NYK', 'Precious Achiuwa': 'NYK', 'OG Anunoby': 'NYK', 'Kevin McCullar Jr.': 'NYK', 'Jalen Brunson': 'NYK', 'Tyler Kolek': 'NYK', 'Mitchell Robinson': 'NYK', 'Mikal Bridges': 'NYK', 'Anton Watson': 'NYK', 'Karl-Anthony Towns': 'NYK', 'Landry Shamet': 'NYK', 'Ariel Hukporti': 'NYK', 'Max Strus': 'CLE', 'Ty Jerome': 'CLE', 'Evan Mobley': 'CLE', 'Sam Merrill': 'CLE', 'Javonte Green': 'CLE', 'Craig Porter Jr.': 'CLE', 'Darius Garland': 'CLE', "De'Andre Hunter": 'CLE', 'Tristan Thompson': 'CLE', 'Emoni Bates': 'CLE', 'Jaylon Tyson': 'CLE', "Nae'Qwan Tomlin": 'CLE', 'Jarrett Allen': 'CLE', 'Dean Wade': 'CLE', 'Luke Travers': 'CLE', 'Isaac Okoro': 'CLE', 'Donovan Mitchell': 'CLE', 'Isaiah Stevens': 'MIA', 'Terry Rozier': 'MIA', 'Nikola Jovic': 'MIA', "Kel'el Ware": 'MIA', 'Josh Christopher': 'MIA', 'Pelle Larsson': 'MIA', 'Jaime Jaquez Jr.': 'MIA', 'Dru Smith': 'MIA', 'Bam Adebayo': 'MIA', 'Tyler Herro': 'MIA', 'Keshad Johnson': 'MIA', 'Alec Burks': 'MIA', 'Kyle Anderson': 'MIA', 'Andrew Wiggins': 'MIA', 'Haywood Highsmith': 'MIA', 'Kevin Love': 'MIA', 'Davion Mitchell': 'MIA', 'Duncan Robinson': 'MIA', 'Jayson Tatum': 'BOS', 'Miles Norris': 'BOS', 'Jrue Holiday': 'BOS', 'Jaylen Brown': 'BOS', 'Kristaps Porzingis': 'BOS', 'Derrick White': 'BOS', 'Payton Pritchard': 'BOS', 'Torrey Craig': 'BOS', 'Drew Peterson': 'BOS', 'JD Davison': 'BOS', 'Xavier Tillman': 'BOS', 'Jordan Walsh': 'BOS', 'Sam Hauser': 'BOS', 'Luke Kornet': 'BOS', 'Al Horford': 'BOS', 'Baylor Scheierman': 'BOS', 'Neemias Queta': 'BOS', 'Jordan Clarkson': 'UTA', 'Taylor Hendricks': 'UTA', 'Collin Sexton': 'UTA', 'Keyonte George': 'UTA', 'Cody Williams': 'UTA', 'Jaden Springer': 'UTA', 'Isaiah Collier': 'UTA', 'Elijah Harkless': 'UTA', 'Svi Mykhailiuk': 'UTA', 'John Collins': 'UTA', 'Kyle Filipowski': 'UTA', 'Lauri Markkanen': 'UTA', 'Walker Kessler': 'UTA', 'Micah Potter': 'UTA', 'Brice Sensabaugh': 'UTA', 'Johnny Juzang': 'UTA', 'Oscar Tshiebwe': 'UTA', 'KJ Martin': 'UTA', 'Aaron Holiday': 'HOU', 'Amen Thompson': 'HOU', 'Jock Landale': 'HOU', "N'Faly Dante": 'HOU', 'Jalen Green': 'HOU', 'Fred VanVleet': 'HOU', 'Cam Whitmore': 'HOU', "Jae'Sean Tate": 'HOU', 'Dillon Brooks': 'HOU', 'Jabari Smith Jr.': 'HOU', 'Steven Adams': 'HOU', 'Reed Sheppard': 'HOU', 'Tari Eason': 'HOU', 'Nate Williams': 'HOU', 'Alperen Sengun': 'HOU', 'Jeff Green': 'HOU', 'David Roddy': 'HOU', 'Jack McVeigh': 'HOU', 'Jacob Toppin': 'ATL', 'Jalen Johnson': 'ATL', 'Keaton Wallace': 'ATL', 'Caris LeVert': 'ATL', 'Kobe Bufkin': 'ATL', 'Dyson Daniels': 'ATL', 'Zaccharie Risacher': 'ATL', 'Trae Young': 'ATL', 'Terance Mann': 'ATL', 'Clint Capela': 'ATL', 'Onyeka Okongwu': 'ATL', 'Mouhamed Gueye': 'ATL', 'Georges Niang': 'ATL', 'Larry Nance Jr.': 'ATL', 'Garrison Mathews': 'ATL', 'Dominick Barlow': 'ATL', 'Vit Krejci': 'ATL', 'Daeqwon Plowden': 'ATL', 'Dante Exum': 'DAL', 'Max Christie': 'DAL', 'Jaden Hardy': 'DAL', 'Dereck Lively II': 'DAL', 'Anthony Davis': 'DAL', 'Dwight Powell': 'DAL', 'Olivier-Maxence Prosper': 'DAL', 'Brandon Williams': 'DAL', 'Kyrie Irving': 'DAL', 'Naji Marshall': 'DAL', 'Caleb Martin': 'DAL', 'Kessler Edwards': 'DAL', 'Daniel Gafford': 'DAL', 'Kai Jones': 'DAL', 'P.J. Washington': 'DAL', 'Spencer Dinwiddie': 'DAL', 'Klay Thompson': 'DAL', 'Keldon Johnson': 'SAS', 'Victor Wembanyama': 'SAS', 'Chris Paul': 'SAS', "De'Aaron Fox": 'SAS', 'Stephon Castle': 'SAS', 'David Duke Jr.': 'SAS', 'Jeremy Sochan': 'SAS', 'Jordan McLaughlin': 'SAS', 'Blake Wesley': 'SAS', 'Bismack Biyombo': 'SAS', 'Malaki Branham': 'SAS', 'Devin Vassell': 'SAS', 'Riley Minix': 'SAS', 'Charles Bassey': 'SAS', 'Julian Champagnie': 'SAS', 'Harrison Barnes': 'SAS', 'Sandro Mamukelashvili': 'SAS', 'Harrison Ingram': 'SAS', 'Christian Braun': 'DEN', 'Michael Porter Jr.': 'DEN', 'Julian Strawther': 'DEN', 'Russell Westbrook': 'DEN', 'Hunter Tyson': 'DEN', 'DeAndre Jordan': 'DEN', 'Peyton Watson': 'DEN', 'Dario Saric': 'DEN', 'PJ Hall': 'DEN', 'DaRon Holmes II': 'DEN', 'Nikola Jokic': 'DEN', 'Spencer Jones': 'DEN', 'Zeke Nnaji': 'DEN', 'Trey Alexander': 'DEN', 'Jalen Pickett': 'DEN', 'Jamal Murray': 'DEN', 'Vlatko Cancar': 'DEN', 'Aaron Gordon': 'DEN', 'Jalen Duren': 'DET', 'Ronald Holland II': 'DET', 'Cade Cunningham': 'DET', 'Malik Beasley': 'DET', 'Paul Reed': 'DET', 'Tim Hardaway Jr.': 'DET', 'Ausar Thompson': 'DET', 'Tobias Harris': 'DET', 'Ron Harper Jr.': 'DET', 'Dennis Schroder': 'DET', 'Simone Fontecchio': 'DET', 'Jaden Ivey': 'DET', 'Daniss Jenkins': 'DET', 'Marcus Sasser': 'DET', 'Isaiah Stewart': 'DET', 'Bobi Klintman': 'DET', 'Tolu Smith': 'DET', 'Lindy Waters III': 'DET', 'Shai Gilgeous-Alexander': 'OKC', 'Dillon Jones': 'OKC', 'Luguentz Dort': 'OKC', 'Jaylin Williams': 'OKC', 'Chet Holmgren': 'OKC', 'Jalen Williams': 'OKC', 'Alex Caruso': 'OKC', 'Isaiah Joe': 'OKC', 'Ousmane Dieng': 'OKC', 'Adam Flagler': 'OKC', 'Branden Carlson': 'OKC', 'Aaron Wiggins': 'OKC', 'Cason Wallace': 'OKC', 'Ajay Mitchell': 'OKC', 'Kenrich Williams': 'OKC', 'Nikola Topic': 'OKC', 'Isaiah Hartenstein': 'OKC', 'Alex Ducas': 'OKC', 'Keion Brooks Jr.': 'NOP', 'Bruce Brown': 'NOP', 'Zion Williamson': 'NOP', 'Herbert Jones': 'NOP', 'CJ McCollum': 'NOP', 'Elfrid Payton': 'NOP', 'Dejounte Murray': 'NOP', 'Jamal Cain': 'NOP', 'Brandon Boston': 'NOP', 'Antonio Reeves': 'NOP', 'Kelly Olynyk': 'NOP', 'Jose Alvarado': 'NOP', 'Karlo Matkovic': 'NOP', 'Yves Missi': 'NOP', 'Lester Quinones': 'NOP', 'Jordan Hawkins': 'NOP', 'Trey Murphy III': 'NOP', 'Jeremiah Robinson-Earl': 'NOP', 'James Harden': 'LAC', 'Kawhi Leonard': 'LAC', 'Seth Lundy': 'LAC', 'Amir Coffey': 'LAC', 'Kris Dunn': 'LAC', 'Trentyn Flowers': 'LAC', 'Bogdan Bogdanovic': 'LAC', 'Jordan Miller': 'LAC', 'Cam Christie': 'LAC', 'Drew Eubanks': 'LAC', 'Kobe Brown': 'LAC', 'Patrick Baldwin Jr.': 'LAC', 'Norman Powell': 'LAC', 'Ben Simmons': 'LAC', 'Nicolas Batum': 'LAC', 'Ivica Zubac': 'LAC', 'Derrick Jones Jr.': 'LAC', 'Patty Mills': 'LAC'}
Player data missing for Isaac Jones on 2023-24, skipping.
Skipping merge for Isaac Jones on 2023-24 due to missing data.
defense data skipping defense merge

KeyboardInterrupt:

In [84]:

# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != 100.00]
df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
    .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
    .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))


players_to_remove = [
    # "Jordan Poole",
    # "Bub Carrington",
    # "A.J. Johnson",
    # "Justin Champagnie",
    # "Alex Sarr",
    # "Quentin Grimes",
    # "Justin Edwards",
    # "Jared Butler",
    # "Ricky Council IV",
    # "Guerschon Yabusele",
    # "Austin Reaves",
    # "LeBron James",
    # "Luka Doncic",
    # "Dorian Finney-Smith",
    # "Jaxson Hayes",
    # "Andrew Nembhard",
    # "Aaron Nesmith",
    # "Tyrese Haliburton",
    # "Pascal Siakam",
    # "Myles Turner",
    # "Kris Dunn",
    # "Norman Powell",
    # "James Harden",
    # "Kawhi Leonard",
    # "Ivica Zubac",
    # "Mikal Bridges",
    # "Josh Hart",
    # "Cameron Payne",
    # "OG Anunoby",
    # "Karl-Anthony Towns",
    # "RJ Barrett",
    # "Ochai Agbaji",
    # "Jamal Shead",
    # "Scottie Barnes",
    # "Orlando Robinson",
    # "Keon Johnson",
    # "Ziaire Williams",
    # "D'Angelo Russell",
    # "Jalen Wilson",
    # "Nic Claxton",
    # "Gary Trent Jr.",
    # "Taurean Prince",
    # "Ryan Rollins",
    # "Kyle Kuzma",
    # "Brook Lopez",
    # "Christian Braun",
    # "Michael Porter Jr.",
    # "Jamal Murray",
    # "Aaron Gordon",
    # "Nikola Jokic",
    # "Jrue Holiday",
    # "Jaylen Brown",
    # "Derrick White",
    # "Jayson Tatum",
    # "Kristaps Porzingis"
    # "Devin Booker",
    # "Ryan Dunn",
    # "Collin Gillespie",
    # "Kevin Durant",
    # "Nick Richards"
    ]

# players_to_remove = ['Tyrese Haliburton', 'Player1', 'Player2', 'Player3']


matchup = [
    "LAL"
]

df_list = []  # List to store dataframes
for team in matchup:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path



    # Iterate through all files in the directory
    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Append DataFrame to the list




        # Concatenate all the box score dataframes into one
        df= pd.concat(df_list, ignore_index=True)
        


        df =df['PLAYER_uni'].tolist()

list_of_names = df

print(list_of_names) # check history for all comments on what this is doing

players = list_of_names




Team_to_remove = [
"MIL", "PHI", "BOS"
# "BOS", "UTA", "HOU", "ATL", "DAL", "SAS","DEN",
# "DET", "OKC", "NOP", "LAC"
               ]
# Team_to_remove = ["PHX","MIL", "PHI", "NYK", "POR", "ATL", "GSW","GSW", "MEM", "TOR", "CHI",]

# df_merged = df_merged[~df_merged["team"].isin(Team_to_remove)]

find_player = players

df_merged = df_merged[df_merged["Player"].isin(find_player)]


display(df_merged)



from parlay_picker import create_parlays

num_groups = 25  # Number of parlays you want to generate
players_per_group = 20 # Number of players in each parlay
min_confidence = 20
threepm_confidence = 20

parlays_df, group_confidence_scores = create_parlays(df_merged, num_groups, players_per_group,min_confidence,threepm_confidence)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")

['Jarred Vanderbilt', 'Dalton Knecht', 'Gabe Vincent', 'Bronny James', 'Christian Koloko', 'Jaxson Hayes', 'Maxi Kleber', 'Austin Reaves', 'Dorian Finney-Smith', 'Shake Milton', 'LeBron James', 'Alex Len', 'Rui Hachimura', 'Jordan Goodwin', 'Trey Jemison III', 'Luka Doncic', 'Markieff Morris']

                  Player team          REB  confidence_level_REB                    recentgames_REB         AST  confidence_level_AST                  recentgames_AST           PTS  confidence_level_PTS                           recentgames_PTS        3PM  confidence_level_3PM                 recentgames_3PM
169    Jarred Vanderbilt  LAL   4 - 9 - 13                 46.77     [6, 4, 5, 6, 4, 2, 2, 1, 3, 7]   1 - 1 - 2                  9.79   [0, 1, 1, 3, 1, 0, 1, 1, 0, 7]     1 - 3 - 5                 19.81           [2, 6, 7, 0, 1, 0, 10, 2, 0, 9]  0 - 0 - 0                 21.52  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
170        Dalton Knecht  LAL    1 - 4 - 6                 29.24     [0, 1, 3, 1, 0, 1, 4, 3, 3, 2]   1 - 1 - 2                 32.22   [0, 2, 1, 0, 0, 1, 3, 1, 3, 0]   1 - 13 - 24                 11.83         [0, 2, 0, 3, 3, 6, 17, 12, 13, 3]  0 - 1 - 1                 19.11  [0, 0, 0, 1, 1, 2, 3, 3, 2, 1]
171         Gabe Vincent  LAL    0 - 0 - 0                 15.80     [4, 2, 2, 1, 1, 3, 2, 0, 2, 1]   1 - 1 - 1                  0.29   [1, 1, 0, 0, 0, 0, 4, 1, 1, 1]   3 - 11 - 18                 30.81        [20, 15, 8, 6, 4, 6, 9, 12, 11, 9]  0 - 2 - 3                  9.11  [6, 4, 2, 2, 0, 2, 2, 4, 3, 3]
172         Bronny James  LAL    1 - 1 - 2                 11.53     [0, 3, 0, 0, 2, 1, 0, 0, 0, 2]   2 - 3 - 8                  8.59   [1, 5, 0, 0, 0, 0, 1, 1, 0, 2]    5 - 9 - 23                  4.84           [2, 17, 0, 3, 5, 2, 9, 3, 2, 5]  0 - 1 - 2                 12.90  [0, 2, 0, 1, 1, 0, 2, 1, 0, 0]
173          Maxi Kleber  LAL    1 - 1 - 1                 19.48     [1, 3, 2, 2, 2, 0, 1, 3, 2, 2]   0 - 0 - 0                 10.03   [1, 4, 1, 2, 4, 1, 3, 0, 1, 1]     0 - 0 - 0                 28.33          [1, 3, 10, 0, 7, 0, 10, 6, 2, 4]  0 - 0 - 0                 32.92  [0, 1, 1, 0, 0, 0, 2, 2, 0, 0]
174        Austin Reaves  LAL    1 - 4 - 6                 43.63     [8, 7, 1, 4, 6, 2, 5, 7, 4, 8]  2 - 7 - 11                 36.73  [3, 8, 3, 5, 4, 5, 8, 6, 6, 13]  11 - 19 - 26                 60.11  [12, 31, 30, 24, 18, 25, 22, 30, 28, 37]  0 - 0 - 0                 44.87  [0, 5, 3, 1, 1, 3, 2, 5, 4, 4]
175  Dorian Finney-Smith  LAL    1 - 2 - 2                 58.68     [6, 5, 4, 3, 7, 2, 4, 3, 6, 1]   1 - 1 - 2                 27.56   [3, 1, 2, 1, 0, 1, 4, 1, 3, 0]    2 - 7 - 11                 39.82     [20, 11, 3, 11, 14, 2, 14, 15, 10, 5]  0 - 1 - 1                 24.47  [6, 3, 1, 3, 4, 0, 3, 4, 2, 1]
176         Shake Milton  LAL    1 - 3 - 5                 11.22     [1, 6, 1, 0, 5, 1, 0, 2, 1, 1]   1 - 3 - 5                  6.97   [1, 3, 0, 1, 3, 0, 1, 2, 0, 0]    2 - 7 - 16                 12.50          [2, 4, 1, 2, 16, 0, 0, 12, 6, 0]  0 - 1 - 2                 33.11  [0, 0, 0, 0, 1, 0, 0, 2, 2, 0]
177         LeBron James  LAL  6 - 11 - 15                 58.90  [8, 6, 5, 13, 6, 6, 14, 12, 8, 5]  5 - 8 - 10                 63.31  [4, 8, 12, 7, 7, 4, 9, 8, 6, 9]  22 - 33 - 43                 68.71  [16, 25, 17, 13, 24, 17, 22, 31, 34, 17]  0 - 2 - 3                 21.18  [2, 2, 0, 0, 0, 1, 0, 2, 5, 1]
178             Alex Len  LAL    1 - 1 - 2                 14.53     [1, 9, 5, 3, 2, 0, 1, 1, 7, 0]   0 - 0 - 0                 31.02   [0, 1, 1, 1, 2, 0, 0, 0, 2, 0]     0 - 0 - 0                  0.00           [0, 10, 2, 2, 0, 0, 0, 0, 4, 0]  0 - 0 - 0                 31.18  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
179        Rui Hachimura  LAL    1 - 4 - 6                 38.35    [2, 3, 4, 3, 2, 3, 6, 0, 12, 8]   1 - 1 - 2                  0.00   [0, 0, 1, 0, 0, 2, 0, 4, 1, 3]   7 - 14 - 20                 53.62       [7, 13, 14, 5, 5, 5, 15, 21, 6, 17]  0 - 3 - 5                 29.29  [1, 3, 4, 0, 1, 1, 2, 4, 0, 1]
180       Jordan Goodwin  LAL    1 - 2 - 3                 37.14     [2, 1, 2, 2, 1, 3, 8, 3, 4, 3]   1 - 2 - 3                  3.33   [1, 0, 2, 1, 0, 1, 5, 3, 3, 1]    1 - 7 - 13                 11.02           [4, 0, 8, 2, 1, 4, 8, 8, 15, 2]  0 - 0 - 0                 41.55  [0, 0, 2, 0, 0, 0, 2, 0, 3, 0]
181          Luka Doncic  LAL   6 - 9 - 11                 67.36  [6, 8, 10, 7, 7, 8, 8, 9, 11, 11]  5 - 9 - 12                 59.93  [9, 9, 8, 7, 7, 6, 7, 14, 8, 3]  27 - 37 - 46                 74.78  [20, 29, 25, 34, 32, 34, 31, 21, 33, 45]  1 - 4 - 6                 43.10  [1, 2, 4, 6, 4, 8, 4, 1, 4, 7]
182      Markieff Morris  LAL    1 - 2 - 4                 10.58     [0, 4, 5, 1, 0, 0, 1, 1, 1, 1]   1 - 1 - 2                 50.00   [1, 2, 3, 2, 1, 2, 0, 0, 1, 1]     1 - 5 - 9                  5.14            [2, 9, 7, 4, 5, 3, 3, 2, 0, 5]  0 - 0 - 0                 27.90  [0, 1, 1, 1, 1, 1, 1, 0, 0, 1]

Confidence scores for each group:
Parlay 1: 51.02


Parlay 1: total confidence score: 51.02

                 Player team Stat    Stat Range  Confidence                               recentgames
0           Luka Doncic  LAL  PTS  27 - 37 - 46       74.78  [20, 29, 25, 34, 32, 34, 31, 21, 33, 45]
1          LeBron James  LAL  PTS  22 - 33 - 43       68.71  [16, 25, 17, 13, 24, 17, 22, 31, 34, 17]
2           Luka Doncic  LAL  REB    6 - 9 - 11       67.36         [6, 8, 10, 7, 7, 8, 8, 9, 11, 11]
3          LeBron James  LAL  AST    5 - 8 - 10       63.31           [4, 8, 12, 7, 7, 4, 9, 8, 6, 9]
4         Austin Reaves  LAL  PTS  11 - 19 - 26       60.11  [12, 31, 30, 24, 18, 25, 22, 30, 28, 37]
5           Luka Doncic  LAL  AST    5 - 9 - 12       59.93           [9, 9, 8, 7, 7, 6, 7, 14, 8, 3]
6          LeBron James  LAL  REB   6 - 11 - 15       58.90         [8, 6, 5, 13, 6, 6, 14, 12, 8, 5]
7   Dorian Finney-Smith  LAL  REB     1 - 2 - 2       58.68            [6, 5, 4, 3, 7, 2, 4, 3, 6, 1]
8         Rui Hachimura  LAL  PTS   7 - 14 - 20       53.62       [7, 13, 14, 5, 5, 5, 15, 21, 6, 17]
9       Markieff Morris  LAL  AST     1 - 1 - 2       50.00            [1, 2, 3, 2, 1, 2, 0, 0, 1, 1]
10    Jarred Vanderbilt  LAL  REB    4 - 9 - 13       46.77            [6, 4, 5, 6, 4, 2, 2, 1, 3, 7]
11        Austin Reaves  LAL  3PM     0 - 0 - 0       44.87            [0, 5, 3, 1, 1, 3, 2, 5, 4, 4]
12        Austin Reaves  LAL  REB     1 - 4 - 6       43.63            [8, 7, 1, 4, 6, 2, 5, 7, 4, 8]
13          Luka Doncic  LAL  3PM     1 - 4 - 6       43.10            [1, 2, 4, 6, 4, 8, 4, 1, 4, 7]
14       Jordan Goodwin  LAL  3PM     0 - 0 - 0       41.55            [0, 0, 2, 0, 0, 0, 2, 0, 3, 0]
15  Dorian Finney-Smith  LAL  PTS    2 - 7 - 11       39.82     [20, 11, 3, 11, 14, 2, 14, 15, 10, 5]
16        Rui Hachimura  LAL  REB     1 - 4 - 6       38.35           [2, 3, 4, 3, 2, 3, 6, 0, 12, 8]
17       Jordan Goodwin  LAL  REB     1 - 2 - 3       37.14            [2, 1, 2, 2, 1, 3, 8, 3, 4, 3]
18        Austin Reaves  LAL  AST    2 - 7 - 11       36.73           [3, 8, 3, 5, 4, 5, 8, 6, 6, 13]
19         Shake Milton  LAL  3PM     0 - 1 - 2       33.11            [0, 0, 0, 0, 1, 0, 0, 2, 2, 0]

In [ ]:
def get_safe_bets(df, confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df["confidence_level_PTS"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets["PTS"].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", "PTS", "Safe Bet", "confidence_level_PTS"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_pts, confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df, confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df["confidence_level_REB"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets["REB"].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", "REB", "Safe Bet", "confidence_level_REB"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_reb, confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df,target ,confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df[f"confidence_level_{target}"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets[target].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", f"{target}", "Safe Bet", f"confidence_level_{target}"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_ast,"AST" ,confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df,target ,confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df[f"confidence_level_{target}"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets[target].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", f"{target}", "Safe Bet", f"confidence_level_{target}"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_3pm,"3PM" ,confidence_threshold=50)
print(safe_bets_df)

In [ ]:
results_pts.head(10)

In [ ]:
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players

# Retrieve player ID (e.g., LeBron James)
for basketball_players in results_pts["Player"]:
    a_player = players.find_players_by_full_name(basketball_players)[0]
    player_id = a_player['id']

    gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')  # Use the latest season
    games = gamelog.get_data_frames()[0]  # Extract data frame
    
    latest_game = games.iloc[0]
    print(basketball_players,latest_game['PTS'])




# player_name = "LeBron James"
# player = players.find_players_by_full_name(player_name)[0]  # Get player data by name

# player_id = player['id']  # Get player ID

# # Fetch the player's game log (latest games)
# gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')  # Use the latest season
# games = gamelog.get_data_frames()[0]  # Extract data frame

# # Get the latest game data
# latest_game = games.iloc[0]  # Latest game data
# print(type(latest_game))
# print(latest_game["PTS"])
# display(latest_game)

In [42]:
from nba_api.stats.endpoints import commonteamroster
from nba_api.stats.static import teams
import pandas as pd
from unidecode import unidecode

team_abbreviations = [
    "BOS", "BKN", "NYK", "PHI", "TOR",  # Atlantic Division
    "CHI", "CLE", "DET", "IND", "MIL",  # Central Division
    "ATL", "CHA", "MIA", "ORL", "WAS",  # Southeast Division
    "DEN", "MIN", "OKC", "POR", "UTA",  # Northwest Division
    "GSW", "LAC", "LAL", "PHX", "SAC",  # Pacific Division
    "DAL", "HOU", "MEM", "NOP", "SAS"   # Southwest Division
]


# Get all NBA teams and create a mapping of abbreviations to team IDs
nba_teams = teams.get_teams()
team_id_map = {team['abbreviation']: team['id'] for team in nba_teams}

# Dictionary to store team rosters
team_rosters = {}

# Loop through each team
for team_abbr in team_abbreviations:
    team_id = team_id_map[team_abbr]

    # Specify the season in 'YYYY-YY' format
    season = '2024-25'

    # Retrieve the team's roster
    roster = commonteamroster.CommonTeamRoster(team_id=team_id, season=season)

    # Convert the roster data to a pandas DataFrame
    roster_df = roster.get_data_frames()[0]

    # Normalize player names by removing accents
    roster_df['PLAYER_uni'] = roster_df['PLAYER'].apply(unidecode)


    roster_df['api_team_name'] = team_abbr

    # Store the roster for the team
    team_rosters[team_abbr] = roster_df

In [43]:
# Display rosters
import pandas as pd
import os
for team_abbr, roster_df in team_rosters.items():
    print(f"\n{team_abbr} Roster:")
    display(roster_df[['PLAYER_uni','POSITION','api_team_name']])
    # roster = roster.DataFrame(ri)
    directory = "D:/roster_folder/2024"
    os.makedirs(directory, exist_ok=True)
    roster_df.to_csv(fr"{directory}/{team_abbr}_roster_file.csv", index=False)

BOS Roster:

            PLAYER_uni POSITION api_team_name
0         Jayson Tatum      F-G           BOS
1         Miles Norris        F           BOS
2         Jrue Holiday        G           BOS
3         Jaylen Brown      G-F           BOS
4   Kristaps Porzingis      F-C           BOS
5        Derrick White        G           BOS
6     Payton Pritchard        G           BOS
7         Torrey Craig        F           BOS
8        Drew Peterson        F           BOS
9           JD Davison        G           BOS
10      Xavier Tillman        F           BOS
11        Jordan Walsh        G           BOS
12          Sam Hauser        F           BOS
13         Luke Kornet      C-F           BOS
14          Al Horford      C-F           BOS
15   Baylor Scheierman        G           BOS
16       Neemias Queta        C           BOS

BKN Roster:

           PLAYER_uni POSITION api_team_name
0     Dariq Whitehead      G-F           BKN
1    D'Angelo Russell        G           BKN
2     Cameron Johnson        F           BKN
3       Reece Beekman        G           BKN
4     Ziaire Williams        F           BKN
5     Trendon Watford      G-F           BKN
6       Tyson Etienne        G           BKN
7     Tosan Evbuomwan        F           BKN
8       Tyrese Martin        F           BKN
9   De'Anthony Melton        G           BKN
10     Day'Ron Sharpe        C           BKN
11       Noah Clowney      F-C           BKN
12       Jalen Wilson        F           BKN
13         Cam Thomas        G           BKN
14         Drew Timme        F           BKN
15      Maxwell Lewis        F           BKN
16        Nic Claxton        C           BKN
17       Keon Johnson        G           BKN

NYK Roster:

            PLAYER_uni POSITION api_team_name
0         Delon Wright        G           NYK
1     MarJon Beauchamp        F           NYK
2          P.J. Tucker        F           NYK
3        Cameron Payne        G           NYK
4        Miles McBride        G           NYK
5            Josh Hart        G           NYK
6        Pacome Dadiet        F           NYK
7     Precious Achiuwa        F           NYK
8           OG Anunoby      F-G           NYK
9   Kevin McCullar Jr.        G           NYK
10       Jalen Brunson        G           NYK
11         Tyler Kolek        G           NYK
12   Mitchell Robinson      C-F           NYK
13       Mikal Bridges      G-F           NYK
14        Anton Watson        F           NYK
15  Karl-Anthony Towns      C-F           NYK
16       Landry Shamet        G           NYK
17      Ariel Hukporti        C           NYK

PHI Roster:

             PLAYER_uni POSITION api_team_name
0       Phillip Wheeler        F           PHI
1          Tyrese Maxey        G           PHI
2        Andre Drummond        C           PHI
3        Quentin Grimes        G           PHI
4            Kyle Lowry        G           PHI
5           Paul George        F           PHI
6       Kelly Oubre Jr.      F-G           PHI
7       Jeff Dowtin Jr.        G           PHI
8          Jared Butler        G           PHI
9      Ricky Council IV        G           PHI
10     Lonnie Walker IV      G-F           PHI
11  Jalen Hood-Schifino        G           PHI
12       Justin Edwards        F           PHI
13         Jared McCain        G           PHI
14          Joel Embiid      C-F           PHI
15          Eric Gordon        G           PHI
16   Guerschon Yabusele        F           PHI
17            Adem Bona        F           PHI
18           Alex Reese      F-C           PHI

TOR Roster:

           PLAYER_uni POSITION api_team_name
0         A.J. Lawson        G           TOR
1         Gradey Dick      G-F           TOR
2      Jonathan Mogbo        F           TOR
3      Brandon Ingram        F           TOR
4      Scottie Barnes      F-G           TOR
5   Immanuel Quickley        G           TOR
6        Jared Rhoden        G           TOR
7          RJ Barrett      F-G           TOR
8         Cole Swider        F           TOR
9      Ja'Kobe Walter        G           TOR
10     Garrett Temple      G-F           TOR
11       Jakob Poeltl        C           TOR
12   Orlando Robinson        C           TOR
13     Ulrich Chomche        C           TOR
14        Jamal Shead        G           TOR
15      Chris Boucher        F           TOR
16       Ochai Agbaji        G           TOR
17     Jamison Battle        F           TOR

CHI Roster:

             PLAYER_uni POSITION api_team_name
0            Coby White        G           CHI
1            Lonzo Ball        G           CHI
2           Josh Giddey        G           CHI
3          Jevon Carter        G           CHI
4           Jalen Smith      F-C           CHI
5        Nikola Vucevic        C           CHI
6           Ayo Dosunmu        G           CHI
7          Jahmir Young        G           CHI
8          Zach Collins      F-C           CHI
9         Kevin Huerter      G-F           CHI
10        Matas Buzelis        F           CHI
11      Julian Phillips        F           CHI
12       Emanuel Miller        F           CHI
13  Talen Horton-Tucker        G           CHI
14          Dalen Terry        F           CHI
15            Tre Jones        G           CHI
16         E.J. Liddell        F           CHI
17     Patrick Williams        F           CHI

CLE Roster:

          PLAYER_uni POSITION api_team_name
0          Max Strus      G-F           CLE
1          Ty Jerome      G-F           CLE
2        Evan Mobley        C           CLE
3        Sam Merrill        G           CLE
4      Javonte Green        G           CLE
5   Craig Porter Jr.        G           CLE
6     Darius Garland        G           CLE
7    De'Andre Hunter      F-G           CLE
8   Tristan Thompson      C-F           CLE
9        Emoni Bates        F           CLE
10      Jaylon Tyson      G-F           CLE
11   Nae'Qwan Tomlin        F           CLE
12     Jarrett Allen        C           CLE
13         Dean Wade      F-C           CLE
14      Luke Travers        F           CLE
15       Isaac Okoro      F-G           CLE
16  Donovan Mitchell        G           CLE

DET Roster:

           PLAYER_uni POSITION api_team_name
0         Jalen Duren        C           DET
1   Ronald Holland II        F           DET
2     Cade Cunningham        G           DET
3       Malik Beasley        G           DET
4           Paul Reed        F           DET
5    Tim Hardaway Jr.      G-F           DET
6      Ausar Thompson      G-F           DET
7       Tobias Harris        F           DET
8      Ron Harper Jr.      G-F           DET
9     Dennis Schroder        G           DET
10  Simone Fontecchio        F           DET
11         Jaden Ivey        G           DET
12     Daniss Jenkins        G           DET
13      Marcus Sasser        G           DET
14     Isaiah Stewart      F-C           DET
15      Bobi Klintman        F           DET
16         Tolu Smith        F           DET
17   Lindy Waters III        F           DET

IND Roster:

            PLAYER_uni POSITION api_team_name
0    Tyrese Haliburton        G           IND
1   Bennedict Mathurin      G-F           IND
2           Obi Toppin        F           IND
3      Andrew Nembhard      G-F           IND
4        Thomas Bryant      C-F           IND
5        Jarace Walker        F           IND
6      Enrique Freeman        F           IND
7       T.J. McConnell        G           IND
8          RayJ Dennis        G           IND
9        Johnny Furphy        G           IND
10        Tony Bradley      C-F           IND
11       James Johnson        F           IND
12      Isaiah Jackson        F           IND
13       Aaron Nesmith      G-F           IND
14        Ben Sheppard        G           IND
15     Quenton Jackson        G           IND
16        Myles Turner      C-F           IND
17       Pascal Siakam        F           IND

MIL Roster:

               PLAYER_uni POSITION api_team_name
0          Damian Lillard        G           MIL
1            Jericho Sims        C           MIL
2        Kevin Porter Jr.      G-F           MIL
3          Gary Trent Jr.        G           MIL
4        Chris Livingston        F           MIL
5            Bobby Portis        F           MIL
6             Brook Lopez        C           MIL
7          Taurean Prince        F           MIL
8            Ryan Rollins        G           MIL
9          Jamaree Bouyea        G           MIL
10          Stanley Umude        G           MIL
11             Kyle Kuzma        F           MIL
12               AJ Green        G           MIL
13            Tyler Smith        F           MIL
14        Pat Connaughton        G           MIL
15  Giannis Antetokounmpo        F           MIL
16             Pete Nance        F           MIL
17      Andre Jackson Jr.        G           MIL

ATL Roster:

            PLAYER_uni POSITION api_team_name
0         Jacob Toppin        F           ATL
1        Jalen Johnson        F           ATL
2       Keaton Wallace        G           ATL
3         Caris LeVert        G           ATL
4          Kobe Bufkin        G           ATL
5        Dyson Daniels        G           ATL
6   Zaccharie Risacher        F           ATL
7           Trae Young        G           ATL
8         Terance Mann      G-F           ATL
9         Clint Capela        C           ATL
10      Onyeka Okongwu      F-C           ATL
11      Mouhamed Gueye        F           ATL
12       Georges Niang        F           ATL
13     Larry Nance Jr.      F-C           ATL
14    Garrison Mathews        G           ATL
15     Dominick Barlow        F           ATL
16          Vit Krejci        G           ATL
17     Daeqwon Plowden      G-F           ATL

CHA Roster:

           PLAYER_uni POSITION api_team_name
0       Miles Bridges        F           CHA
1         LaMelo Ball        G           CHA
2      Grant Williams        F           CHA
3     DaQuan Jeffries      G-F           CHA
4       Mark Williams        C           CHA
5        Damion Baugh        G           CHA
6      Nick Smith Jr.        G           CHA
7   Wendell Moore Jr.        G           CHA
8          Josh Green        G           CHA
9        Jusuf Nurkic        C           CHA
10        Josh Okogie        G           CHA
11     Moussa Diabate        F           CHA
12           Tre Mann        G           CHA
13     Brandon Miller        F           CHA
14         KJ Simpson        G           CHA
15         Seth Curry        G           CHA
16     Tidjane Salaun        F           CHA
17         Taj Gibson        F           CHA

MIA Roster:

           PLAYER_uni POSITION api_team_name
0      Isaiah Stevens        G           MIA
1        Terry Rozier        G           MIA
2        Nikola Jovic        F           MIA
3         Kel'el Ware        C           MIA
4    Josh Christopher        G           MIA
5       Pelle Larsson        G           MIA
6    Jaime Jaquez Jr.        G           MIA
7           Dru Smith        G           MIA
8         Bam Adebayo      C-F           MIA
9         Tyler Herro        G           MIA
10     Keshad Johnson        F           MIA
11         Alec Burks        G           MIA
12      Kyle Anderson      F-G           MIA
13     Andrew Wiggins        F           MIA
14  Haywood Highsmith        F           MIA
15         Kevin Love      F-C           MIA
16    Davion Mitchell        G           MIA
17    Duncan Robinson        F           MIA

ORL Roster:

                  PLAYER_uni POSITION api_team_name
0              Anthony Black        G           ORL
1             Jonathan Isaac        F           ORL
2              Caleb Houstan        G           ORL
3   Kentavious Caldwell-Pope        G           ORL
4                Jalen Suggs        G           ORL
5             Paolo Banchero        F           ORL
6                Mac McClung        G           ORL
7                Cory Joseph        G           ORL
8             Trevelin Queen        G           ORL
9                Jett Howard        G           ORL
10               Gary Harris        G           ORL
11             Moritz Wagner      F-C           ORL
12              Franz Wagner        F           ORL
13          Tristan da Silva        F           ORL
14        Wendell Carter Jr.      C-F           ORL
15              Goga Bitadze      C-F           ORL
16              Cole Anthony        G           ORL
17            Ethan Thompson        G           ORL

WAS Roster:

           PLAYER_uni POSITION api_team_name
0     Bilal Coulibaly        G           WAS
1    Tristan Vukcevic        F           WAS
2         Colby Jones        G           WAS
3       Jaylen Martin        G           WAS
4          AJ Johnson        G           WAS
5      Bub Carrington        G           WAS
6   Justin Champagnie      G-F           WAS
7        Jordan Poole        G           WAS
8          Saddiq Bey      G-F           WAS
9     Malcolm Brogdon        G           WAS
10       Anthony Gill        F           WAS
11     Kyshawn George        F           WAS
12          Alex Sarr        C           WAS
13            JT Thor        F           WAS
14     Richaun Holmes        F           WAS
15      Corey Kispert        F           WAS
16    Khris Middleton        F           WAS
17       Marcus Smart        G           WAS

DEN Roster:

            PLAYER_uni POSITION api_team_name
0      Christian Braun        G           DEN
1   Michael Porter Jr.        F           DEN
2     Julian Strawther        G           DEN
3    Russell Westbrook        G           DEN
4         Hunter Tyson        F           DEN
5       DeAndre Jordan        C           DEN
6        Peyton Watson        G           DEN
7          Dario Saric      F-C           DEN
8              PJ Hall        C           DEN
9      DaRon Holmes II        F           DEN
10        Nikola Jokic        C           DEN
11       Spencer Jones        F           DEN
12          Zeke Nnaji      F-C           DEN
13      Trey Alexander        G           DEN
14       Jalen Pickett        G           DEN
15        Jamal Murray        G           DEN
16       Vlatko Cancar        F           DEN
17        Aaron Gordon        F           DEN

MIN Roster:

                  PLAYER_uni POSITION api_team_name
0       Terrence Shannon Jr.      G-F           MIN
1           Donte DiVincenzo        G           MIN
2            Jaden McDaniels        F           MIN
3             Rob Dillingham        G           MIN
4            Anthony Edwards        G           MIN
5                 Joe Ingles      F-G           MIN
6                Josh Minott        F           MIN
7   Nickeil Alexander-Walker        G           MIN
8                Mike Conley        G           MIN
9                   Naz Reid      C-F           MIN
10            Tristen Newton        G           MIN
11             Jesse Edwards        C           MIN
12              Jaylen Clark        G           MIN
13               Rudy Gobert        C           MIN
14             Julius Randle      F-C           MIN
15            Leonard Miller        F           MIN
16                Luka Garza        C           MIN
17              Bones Hyland        G           MIN

OKC Roster:

                 PLAYER_uni POSITION api_team_name
0   Shai Gilgeous-Alexander        G           OKC
1              Dillon Jones        F           OKC
2             Luguentz Dort        G           OKC
3           Jaylin Williams        F           OKC
4             Chet Holmgren      C-F           OKC
5            Jalen Williams      G-F           OKC
6               Alex Caruso        G           OKC
7                Isaiah Joe        G           OKC
8             Ousmane Dieng        F           OKC
9              Adam Flagler        G           OKC
10          Branden Carlson        C           OKC
11            Aaron Wiggins        G           OKC
12            Cason Wallace        G           OKC
13            Ajay Mitchell        G           OKC
14         Kenrich Williams      G-F           OKC
15             Nikola Topic        G           OKC
16       Isaiah Hartenstein      C-F           OKC
17               Alex Ducas        G           OKC

POR Roster:

             PLAYER_uni POSITION api_team_name
0       Scoot Henderson        G           POR
1       Anfernee Simons        G           POR
2         Deandre Ayton        C           POR
3      Matisse Thybulle      G-F           POR
4         Dalano Banton        F           POR
5           Deni Avdija        F           POR
6          Jerami Grant        F           POR
7         Justin Minaya        F           POR
8        Bryce McGowens        G           POR
9        Shaedon Sharpe        G           POR
10         Rayan Rupert      G-F           POR
11      Donovan Clingan        C           POR
12          Kris Murray        F           POR
13         Sidy Cissoko        G           POR
14           Duop Reath        C           POR
15       Toumani Camara        F           POR
16        Jabari Walker        F           POR
17  Robert Williams III      C-F           POR

UTA Roster:

          PLAYER_uni POSITION api_team_name
0    Jordan Clarkson        G           UTA
1   Taylor Hendricks        F           UTA
2      Collin Sexton        G           UTA
3     Keyonte George        G           UTA
4      Cody Williams        F           UTA
5     Jaden Springer        G           UTA
6     Isaiah Collier        G           UTA
7    Elijah Harkless        G           UTA
8     Svi Mykhailiuk      G-F           UTA
9       John Collins      F-C           UTA
10   Kyle Filipowski        C           UTA
11   Lauri Markkanen      F-C           UTA
12    Walker Kessler        C           UTA
13      Micah Potter        C           UTA
14  Brice Sensabaugh        F           UTA
15     Johnny Juzang        G           UTA
16    Oscar Tshiebwe      F-C           UTA
17         KJ Martin        F           UTA

GSW Roster:

              PLAYER_uni POSITION api_team_name
0         Gary Payton II        G           GSW
1       Jonathan Kuminga        F           GSW
2        Taran Armstrong        G           GSW
3     Brandin Podziemski        G           GSW
4            Moses Moody        G           GSW
5           Kevon Looney        F           GSW
6            Buddy Hield        G           GSW
7       Jimmy Butler III        F           GSW
8            Braxton Key        F           GSW
9             Gui Santos        F           GSW
10          Quinten Post        C           GSW
11        Draymond Green        F           GSW
12         Stephen Curry        G           GSW
13         Kevin Knox II        F           GSW
14  Trayce Jackson-Davis        F           GSW
15          Jackson Rowe        F           GSW
16           Pat Spencer        G           GSW

LAC Roster:

             PLAYER_uni POSITION api_team_name
0          James Harden        G           LAC
1         Kawhi Leonard        F           LAC
2            Seth Lundy      G-F           LAC
3           Amir Coffey      G-F           LAC
4             Kris Dunn        G           LAC
5       Trentyn Flowers        F           LAC
6     Bogdan Bogdanovic        G           LAC
7         Jordan Miller        G           LAC
8          Cam Christie        G           LAC
9          Drew Eubanks      F-C           LAC
10           Kobe Brown        F           LAC
11  Patrick Baldwin Jr.        F           LAC
12        Norman Powell        G           LAC
13          Ben Simmons      G-F           LAC
14        Nicolas Batum      G-F           LAC
15          Ivica Zubac        C           LAC
16    Derrick Jones Jr.        F           LAC
17          Patty Mills        G           LAC

LAL Roster:

             PLAYER_uni POSITION api_team_name
0     Jarred Vanderbilt        F           LAL
1         Dalton Knecht        F           LAL
2          Gabe Vincent        G           LAL
3          Bronny James        G           LAL
4      Christian Koloko        C           LAL
5          Jaxson Hayes      C-F           LAL
6           Maxi Kleber        F           LAL
7         Austin Reaves        G           LAL
8   Dorian Finney-Smith        F           LAL
9          Shake Milton        G           LAL
10         LeBron James        F           LAL
11             Alex Len        C           LAL
12        Rui Hachimura        F           LAL
13       Jordan Goodwin        G           LAL
14     Trey Jemison III        C           LAL
15          Luka Doncic      F-G           LAL
16      Markieff Morris        F           LAL

PHX Roster:

             PLAYER_uni POSITION api_team_name
0         Royce O'Neale        F           PHX
1             Ryan Dunn        F           PHX
2          Devin Booker        G           PHX
3         Nick Richards        C           PHX
4          Bradley Beal        G           PHX
5          Oso Ighodaro        F           PHX
6         Grayson Allen        G           PHX
7            Damion Lee      G-F           PHX
8               Bol Bol      C-F           PHX
9      Collin Gillespie        G           PHX
10  TyTy Washington Jr.        G           PHX
11        Jalen Bridges        F           PHX
12          Cody Martin        F           PHX
13       Vasilije Micic        G           PHX
14           Tyus Jones        G           PHX
15        Mason Plumlee      F-C           PHX
16         Monte Morris        G           PHX
17         Kevin Durant        F           PHX

SAC Roster:

           PLAYER_uni POSITION api_team_name
0          Malik Monk        G           SAC
1         Isaac Jones        F           SAC
2      Doug McDermott        F           SAC
3         Zach LaVine        G           SAC
4       DeMar DeRozan      G-F           SAC
5    Domantas Sabonis      F-C           SAC
6       Keegan Murray        F           SAC
7         Mason Jones        G           SAC
8   Jonas Valanciunas        C           SAC
9      Markelle Fultz        G           SAC
10       Devin Carter        G           SAC
11         Keon Ellis        G           SAC
12    Isaiah Crawford        F           SAC
13       Jake LaRavia        F           SAC
14         Trey Lyles        F           SAC
15        Jae Crowder        F           SAC

DAL Roster:

                 PLAYER_uni POSITION api_team_name
0                Dante Exum        G           DAL
1              Max Christie        G           DAL
2               Jaden Hardy        G           DAL
3          Dereck Lively II        C           DAL
4             Anthony Davis      F-C           DAL
5             Dwight Powell      F-C           DAL
6   Olivier-Maxence Prosper        F           DAL
7          Brandon Williams        G           DAL
8              Kyrie Irving        G           DAL
9             Naji Marshall        F           DAL
10             Caleb Martin        F           DAL
11          Kessler Edwards        F           DAL
12           Daniel Gafford      F-C           DAL
13                Kai Jones      C-F           DAL
14          P.J. Washington        F           DAL
15        Spencer Dinwiddie        G           DAL
16            Klay Thompson        G           DAL

HOU Roster:

          PLAYER_uni POSITION api_team_name
0      Aaron Holiday        G           HOU
1      Amen Thompson      G-F           HOU
2       Jock Landale        C           HOU
3       N'Faly Dante        C           HOU
4        Jalen Green        G           HOU
5      Fred VanVleet        G           HOU
6       Cam Whitmore        F           HOU
7      Jae'Sean Tate        F           HOU
8      Dillon Brooks      G-F           HOU
9   Jabari Smith Jr.        F           HOU
10      Steven Adams        C           HOU
11     Reed Sheppard        G           HOU
12        Tari Eason        F           HOU
13     Nate Williams        G           HOU
14    Alperen Sengun        C           HOU
15        Jeff Green        F           HOU
16       David Roddy        F           HOU
17      Jack McVeigh      G-F           HOU

MEM Roster:

            PLAYER_uni POSITION api_team_name
0          Zyon Pullin        G           MEM
1         Jaylen Wells        F           MEM
2    Scotty Pippen Jr.        G           MEM
3   Vince Williams Jr.        G           MEM
4         Santi Aldama      F-C           MEM
5        Lamar Stevens        F           MEM
6         Luke Kennard        G           MEM
7            Ja Morant        G           MEM
8    Jaren Jackson Jr.      F-C           MEM
9            Zach Edey        C           MEM
10      Brandon Clarke        F           MEM
11       Yuki Kawamura        G           MEM
12        Desmond Bane        G           MEM
13         Cam Spencer        G           MEM
14            Jay Huff        C           MEM
15   Marvin Bagley III        F           MEM
16          GG Jackson        F           MEM
17        John Konchar        G           MEM

NOP Roster:

                PLAYER_uni POSITION api_team_name
0         Keion Brooks Jr.        F           NOP
1              Bruce Brown      G-F           NOP
2          Zion Williamson        F           NOP
3            Herbert Jones        F           NOP
4              CJ McCollum        G           NOP
5            Elfrid Payton        G           NOP
6          Dejounte Murray        G           NOP
7               Jamal Cain        F           NOP
8           Brandon Boston        G           NOP
9           Antonio Reeves        G           NOP
10            Kelly Olynyk      F-C           NOP
11           Jose Alvarado        G           NOP
12          Karlo Matkovic      F-C           NOP
13              Yves Missi        C           NOP
14         Lester Quinones        G           NOP
15          Jordan Hawkins        G           NOP
16         Trey Murphy III        F           NOP
17  Jeremiah Robinson-Earl        F           NOP

SAS Roster:

               PLAYER_uni POSITION api_team_name
0          Keldon Johnson      F-G           SAS
1       Victor Wembanyama      F-C           SAS
2              Chris Paul        G           SAS
3            De'Aaron Fox        G           SAS
4          Stephon Castle        G           SAS
5          David Duke Jr.        G           SAS
6           Jeremy Sochan        F           SAS
7       Jordan McLaughlin        G           SAS
8            Blake Wesley        G           SAS
9         Bismack Biyombo        C           SAS
10         Malaki Branham        F           SAS
11          Devin Vassell      G-F           SAS
12            Riley Minix        F           SAS
13         Charles Bassey      C-F           SAS
14      Julian Champagnie        F           SAS
15        Harrison Barnes        F           SAS
16  Sandro Mamukelashvili      F-C           SAS
17        Harrison Ingram        F           SAS

In [ ]:


matched_players_list = []
for team_abbr, roster_df in team_rosters.items():
    # print(f"\n{team_abbr} Roster:")
    df_roster = roster_df[['PLAYER', 'PLAYER_uni']]

    if team_abbr in results_pts['team'].values:
        matched_players = df_roster[df_roster['PLAYER_uni'].isin(results_pts['Player'])]
        
        if not matched_players.empty:
            matched_players = matched_players['PLAYER']
            matched_players_list.append(matched_players)
            # display(matched_players)
            # print(matched_players)

# Combine all matched players into a single DataFrame
if matched_players_list:
    final_matched_df = pd.concat(matched_players_list, ignore_index=True)
    display(final_matched_df)  # Display the final combined DataFrame
else:
    print("No matches found.")


from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players

# Retrieve player ID (e.g., LeBron James)
player_list = final_matched_df.tolist()
for basketball_players in player_list:
    found_players = players.find_players_by_full_name(basketball_players)

    if found_players:
        a_player = found_players[0]
        player_id = a_player['id']

        # Fetch game log
        gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')
        games = gamelog.get_data_frames()[0]  # Extract DataFrame
        
        if not games.empty:
            latest_game = games.iloc[0]  # Get the most recent game
            print(f"{basketball_players}: {latest_game['PTS']} points")
        else:
            print(f"{basketball_players}: No game data available")

    else:
        print(f"Player not found: {basketball_players}")

In [ ]:

# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

# results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != 100.00]
# df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
#     .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
#     .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))

# df_merged = df_merged[df_merged["Player"] != 'Tyrese Haliburton']


# print(df_merged.columns)


# df_merged['middlebet_PTS+REB'] = 0000

# df_merged['PTS+REB'] = df_merged[['middlebet_PTS', 'middlebet_REB']].sum(axis=1)
# df_merged['confidence_level_PTS+REB']=  round(df_merged[['confidence_level_PTS','confidence_level_REB']].sum(axis=1)/2,2)
# df_merged = df_merged.rename(columns={'FGA': 'PTS'})
# display(df_merged)
# display(df_merged[['Player','confidence_level_PTS+REB']])


from parlay_picker import create_parlays, create_parlays_high

num_groups = 10  # Number of parlays you want to generate
players_per_group = 40  # Number of players in each parlay
min_confidence = 20

parlays_df, group_confidence_scores = create_parlays_high(df_merged, num_groups, players_per_group,min_confidence, 70)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")

In [ ]:
# Gets you player names
import pandas as pd

target = ["BOS","MEM", "CHI", "OKC", "BKN", "DAL", "HOU", "LAL"]
df_list = []  # List to store dataframes
for team in target:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path



    # Iterate through all files in the directory
    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Append DataFrame to the list




        # Concatenate all the box score dataframes into one
        df= pd.concat(df_list, ignore_index=True)
        


        df =df['PLAYER_uni'].tolist()

list_of_names = df
print(list_of_names)

In [ ]:
# checks if player from roster is in history
import os

target = ["BOS","MEM", "CHI", "OKC", "BKN", "DAL", "HOU", "LAL"]
df_list = []  # List to store dataframes
for team in target:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path



    # Iterate through all files in the directory
    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Append DataFrame to the list




        # Concatenate all the box score dataframes into one
        df= pd.concat(df_list, ignore_index=True)
        


        df =df['PLAYER_uni'].tolist()


list_of_names = df




unavaliable_names = []
for name in list_of_names:
    file_path = f"D:/nba_player_historic/nba_html_2023-24/{name}_content.html"
    # print(file_path)

    if os.path.exists(file_path):
        print("File exists! ")
    else:
        print("File does not exist.")
        unavaliable_names.append(name)

print(unavaliable_names)

In [ ]:
# this gets player and their team and put into a dictionary 
import os
import pandas as pd

# List of target teams
target = ["BOS", "MEM", "CHI", "OKC", "BKN", "DAL", "HOU", "LAL"]
df_list = []  # List to store DataFrames

# Loop through each team's roster file
for team in target:
    roster_path = f"D:\\roster_folder\\2024\\{team}_roster_file.csv"  # Construct the file path

    if os.path.exists(roster_path):  # Check if file exists
        df = pd.read_csv(roster_path)  # Read CSV file
        df_list.append(df)  # Store DataFrame in list
    else:
        print(f"File not found: {roster_path}")  # Debugging message

# Combine all DataFrames if any were found
if df_list:
    df_combined = pd.concat(df_list, ignore_index=True)

    # Extract two columns as a dictionary
    player_dict = dict(zip(df_combined['PLAYER_uni'], df_combined['api_team_name']))

    print(player_dict)  # Display dictionary
else:
    print("No valid roster files found.")