In [ ]:
from prediction import prediction

players_teams = {
    "Donovan Mitchell": "CLE",
    "Sam Merrill": "CLE",
    "Darius Garland": "CLE",
    "Evan Mobley": "CLE",
    "Jarrett Allen": "CLE",
    "Tim Hardaway Jr.": "DET",
    "Ausar Thompson": "DET",
    "Dennis Schroder": "DET",
    "Tobias Harris": "DET",
    "Jalen Duren": "DET",
    "Kris Dunn": "LAC",
    "Norman Powell": "LAC",
    "James Harden": "LAC",
    "Kawhi Leonard": "LAC",
    "Ivica Zubac": "LAC",
    "Keon Johnson": "BKN",
    "Ziaire Williams": "BKN",
    "D'Angelo Russell": "BKN",
    "Cameron Johnson": "BKN",
    "Nic Claxton": "BKN",
    "Josh Green": "CHA",
    "DaQuan Jeffries": "CHA",
    "KJ Simpson": "CHA",
    "Miles Bridges": "CHA",
    "Mark Williams": "CHA",
    "Ja'Kobe Walter": "TOR",
    "Jamison Battle": "TOR",
    "Immanuel Quickley": "TOR",
    "Scottie Barnes": "TOR",
    "Jakob Poeltl": "TOR",
    "Mikal Bridges": "NYK",
    "Josh Hart": "NYK",
    "Tyler Kolek": "NYK",
    "OG Anunoby": "NYK",
    "Karl-Anthony Towns": "NYK",
    "Devin Booker": "MIL",
    "Ryan Dunn": "MIL",
    "Collin Gillespie": "MIL",
    "Kevin Durant": "MIL",
    "Nick Richards": "MIL",
    "Anthony Edwards": "MIN",
    "Jaden McDaniels": "MIN",
    "Mike Conley": "MIN",
    "Julius Randle": "MIN",
    "Rudy Gobert": "MIN",
    "Brandin Podziemski": "GSW",
    "Moses Moody": "GSW",
    "Stephen Curry": "GSW",
    "Jimmy Butler III": "GSW",
    "Draymond Green": "GSW",
    "Jordan Hawkins": "NOP",
    "Bruce Brown": "NOP",
    "Jose Alvarado": "NOP",
    "Kelly Olynyk": "NOP",
    "Yves Missi": "NOP",
    "Collin Sexton": "UTA",
    "Cody Williams": "UTA",
    "Isaiah Collier": "UTA",
    "Kyle Filipowski": "UTA",
    "Walker Kessler": "UTA",
    "Christian Braun": "DEN",
    "Michael Porter Jr.": "DEN",
    "Jamal Murray": "DEN",
    "Aaron Gordon": "DEN",
    "Nikola Jokic": "DEN"
}









# remember to run mover
# remember to check schedule csv
import pandas as pd
date_list = ["2023-24","2024-25"]
stats_path = {
    'usage_path':'D:/nba_usage_csv_historic/usage_csv_{date}/{date}_content.csv',
    'catch_shoot':"D:/nba_tracking_data_csv/nba_csv_{date}/catch_shoot_content.csv",
    'drives':"D:/nba_tracking_data_csv/nba_csv_{date}/drives_content.csv",
    'elbow_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/elbow_touch_content.csv",
    'paint_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/paint_touch_content.csv",
    'passing':"D:/nba_tracking_data_csv/nba_csv_{date}/passing_content.csv",
    'pullup':"D:/nba_tracking_data_csv/nba_csv_{date}/pullup_content.csv",
    'shooting_efficiency':"D:/nba_tracking_data_csv/nba_csv_{date}/shooting_efficiency_content.csv",
    'touches':"D:/nba_tracking_data_csv/nba_csv_{date}/touches_content.csv",
    'tracking_post_ups_content':"D:/nba_tracking_data_csv/nba_csv_{date}/tracking_post_ups_content.csv"
}
schedule_base_path = "D:/nba_scheduled_csv/schedule_csv_2025/{schedule_team}_schedule_content.csv"
player_base_path = "D:/nba_player_csv_historic/season_{date}/all_quarters/{player}_content.csv"
defense_base_path = "D:/nba_defense_history_csv/defense_csv_{date}/all_quarter_defense_content.csv"

results_reb = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'REB','REB')
results_ast = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'AST','AST')
results_pts = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'PTS','PTS')
results_3pm = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'3PM','3PM')
results_pts = results_pts.rename(columns={'FGA': 'PTS'})



# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

In [ ]:

display(results_reb)
display(results_ast)
display(results_pts)
display(results_3pm)

results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != 100.00]
df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
    .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
    .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))


players_to_remove = [
    # "Jordan Poole",
    # "Bub Carrington",
    # "A.J. Johnson",
    # "Justin Champagnie",
    # "Alex Sarr",
    # "Quentin Grimes",
    # "Justin Edwards",
    # "Jared Butler",
    # "Ricky Council IV",
    # "Guerschon Yabusele",
    # "Austin Reaves",
    # "LeBron James",
    # "Luka Doncic",
    # "Dorian Finney-Smith",
    # "Jaxson Hayes",
    # "Andrew Nembhard",
    # "Aaron Nesmith",
    # "Tyrese Haliburton",
    # "Pascal Siakam",
    # "Myles Turner",
    # "Kris Dunn",
    # "Norman Powell",
    # "James Harden",
    # "Kawhi Leonard",
    # "Ivica Zubac",
    # "Mikal Bridges",
    # "Josh Hart",
    # "Cameron Payne",
    # "OG Anunoby",
    # "Karl-Anthony Towns",
    # "RJ Barrett",
    # "Ochai Agbaji",
    # "Jamal Shead",
    # "Scottie Barnes",
    # "Orlando Robinson",
    # "Keon Johnson",
    # "Ziaire Williams",
    # "D'Angelo Russell",
    # "Jalen Wilson",
    # "Nic Claxton",
    # "Gary Trent Jr.",
    # "Taurean Prince",
    # "Ryan Rollins",
    # "Kyle Kuzma",
    # "Brook Lopez",
    # "Christian Braun",
    # "Michael Porter Jr.",
    # "Jamal Murray",
    # "Aaron Gordon",
    # "Nikola Jokic",
    # "Jrue Holiday",
    # "Jaylen Brown",
    # "Derrick White",
    # "Jayson Tatum",
    # "Kristaps Porzingis"
    # "Devin Booker",
    # "Ryan Dunn",
    # "Collin Gillespie",
    # "Kevin Durant",
    # "Nick Richards"
    ]

# players_to_remove = ['Tyrese Haliburton', 'Player1', 'Player2', 'Player3']

df_merged = df_merged[~df_merged["Player"].isin(players_to_remove)]



from parlay_picker import create_parlays

num_groups = 10  # Number of parlays you want to generate
players_per_group = 4 # Number of players in each parlay
min_confidence = 60
threepm_confidence = 50

parlays_df, group_confidence_scores = create_parlays(df_merged, num_groups, players_per_group,min_confidence,threepm_confidence)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")

In [ ]:
def get_safe_bets(df, confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df["confidence_level_PTS"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets["PTS"].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", "PTS", "Safe Bet", "confidence_level_PTS"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_pts, confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df, confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df["confidence_level_REB"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets["REB"].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", "REB", "Safe Bet", "confidence_level_REB"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_reb, confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df,target ,confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df[f"confidence_level_{target}"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets[target].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", f"{target}", "Safe Bet", f"confidence_level_{target}"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_ast,"AST" ,confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df,target ,confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df[f"confidence_level_{target}"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets[target].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", f"{target}", "Safe Bet", f"confidence_level_{target}"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_3pm,"3PM" ,confidence_threshold=50)
print(safe_bets_df)

In [ ]:
results_pts.head(10)

In [ ]:
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players

# Retrieve player ID (e.g., LeBron James)
for basketball_players in results_pts["Player"]:
    a_player = players.find_players_by_full_name(basketball_players)[0]
    player_id = a_player['id']

    gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')  # Use the latest season
    games = gamelog.get_data_frames()[0]  # Extract data frame
    
    latest_game = games.iloc[0]
    print(basketball_players,latest_game['PTS'])




# player_name = "LeBron James"
# player = players.find_players_by_full_name(player_name)[0]  # Get player data by name

# player_id = player['id']  # Get player ID

# # Fetch the player's game log (latest games)
# gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')  # Use the latest season
# games = gamelog.get_data_frames()[0]  # Extract data frame

# # Get the latest game data
# latest_game = games.iloc[0]  # Latest game data
# print(type(latest_game))
# print(latest_game["PTS"])
# display(latest_game)

In [121]:
from nba_api.stats.endpoints import commonteamroster
from nba_api.stats.static import teams
import pandas as pd
from unidecode import unidecode

# List of team abbreviations you want to check
team_abbreviations = ['CLE', 'DET', 'LAC', 'BKN', 'CHA', 'TOR', 'NYK', 'MIL', 'MIN', 'GSW', 'NOP', 'UTA', 'DEN']  # Example teams

# Get all NBA teams and create a mapping of abbreviations to team IDs
nba_teams = teams.get_teams()
team_id_map = {team['abbreviation']: team['id'] for team in nba_teams}

# Dictionary to store team rosters
team_rosters = {}

# Loop through each team
for team_abbr in team_abbreviations:
    team_id = team_id_map[team_abbr]

    # Specify the season in 'YYYY-YY' format
    season = '2024-25'

    # Retrieve the team's roster
    roster = commonteamroster.CommonTeamRoster(team_id=team_id, season=season)

    # Convert the roster data to a pandas DataFrame
    roster_df = roster.get_data_frames()[0]

    # Normalize player names by removing accents
    roster_df['PLAYER_uni'] = roster_df['PLAYER'].apply(unidecode)

    # Store the roster for the team
    team_rosters[team_abbr] = roster_df

# Display rosters
for team_abbr, roster_df in team_rosters.items():
    print(f"\n{team_abbr} Roster:")
    display(roster_df)  # or use print(roster_df) if you're not in a Jupyter notebook

CLE Roster:

        TeamID SEASON LeagueID            PLAYER  NICKNAME       PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP                    SCHOOL  PLAYER_ID                 HOW_ACQUIRED        PLAYER_uni
0   1610612739   2024       00         Max Strus       Max         max-strus   1      G-F    6-5    215  MAR 28, 1996  29.0   5                    DePaul    1629622  Traded from MIA on 07/06/23         Max Strus
1   1610612739   2024       00         Ty Jerome        Ty         ty-jerome   2      G-F    6-5    195  JUL 08, 1997  27.0   5                  Virginia    1629660           Signed on 07/06/23         Ty Jerome
2   1610612739   2024       00       Evan Mobley      Evan       evan-mobley   4        C   6-11    215  JUN 18, 2001  23.0   3       Southern California    1630596        #3 Pick in 2021 Draft       Evan Mobley
3   1610612739   2024       00       Sam Merrill       Sam       sam-merrill   5        G    6-4    205  MAY 15, 1996  28.0   4                Utah State    1630241           Signed on 03/03/23       Sam Merrill
4   1610612739   2024       00     Javonte Green   Javonte     javonte-green   8        G    6-5    205  JUL 23, 1993  31.0   5                   Radford    1629750           Signed on 02/23/25     Javonte Green
5   1610612739   2024       00  Craig Porter Jr.     Craig   craig-porter-jr   9        G    6-1    180  FEB 26, 2000  25.0   1             Wichita State    1641854           Signed on 07/03/23  Craig Porter Jr.
6   1610612739   2024       00    Darius Garland    Darius    darius-garland  10        G    6-1    192  JAN 26, 2000  25.0   5                Vanderbilt    1629636        #5 Pick in 2019 Draft    Darius Garland
7   1610612739   2024       00   De'Andre Hunter  De'Andre    deandre-hunter  12      F-G    6-8    221  DEC 02, 1997  27.0   5                  Virginia    1629631  Traded from ATL on 02/06/25   De'Andre Hunter
8   1610612739   2024       00  Tristan Thompson   Tristan  tristan-thompson  13      C-F    6-9    254  MAR 13, 1991  34.0  13              Texas-Austin     202684           Signed on 09/12/23  Tristan Thompson
9   1610612739   2024       00       Emoni Bates     Emoni       emoni-bates  21        F    6-8    190  JAN 28, 2004  21.0   1          Eastern Michigan    1641734       #49 Pick in 2023 Draft       Emoni Bates
10  1610612739   2024       00      Jaylon Tyson    Jaylon      jaylon-tyson  24      G-F    6-6    215  DEC 02, 2002  22.0   R                California    1642281       #20 Pick in 2024 Draft      Jaylon Tyson
11  1610612739   2024       00   Nae'Qwan Tomlin  Nae'Qwan    naeqwan-tomlin  30        F   6-10    210  DEC 19, 2000  24.0   R                   Memphis    1641772           Signed on 09/23/24   Nae'Qwan Tomlin
12  1610612739   2024       00     Jarrett Allen   Jarrett     jarrett-allen  31        C    6-9    243  APR 21, 1998  26.0   7                     Texas    1628386  Traded from BKN on 01/16/21     Jarrett Allen
13  1610612739   2024       00         Dean Wade      Dean         dean-wade  32      F-C    6-9    228  NOV 20, 1996  28.0   5              Kansas State    1629731           Signed on 07/01/19         Dean Wade
14  1610612739   2024       00      Luke Travers      Luke      luke-travers  33        F    6-7    207  SEP 03, 2001  23.0   R  Rockingham Flames (Aus.)    1631247       #56 Pick in 2022 Draft      Luke Travers
15  1610612739   2024       00       Isaac Okoro     Isaac       isaac-okoro  35      F-G    6-5    225  JAN 26, 2001  24.0   4                    Auburn    1630171        #5 Pick in 2020 Draft       Isaac Okoro
16  1610612739   2024       00  Donovan Mitchell   Donovan  donovan-mitchell  45        G    6-3    215  SEP 07, 1996  28.0   7                Louisville    1628378  Traded from UTA on 09/03/22  Donovan Mitchell

DET Roster:

        TeamID SEASON LeagueID             PLAYER NICKNAME        PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP               SCHOOL  PLAYER_ID                              HOW_ACQUIRED         PLAYER_uni
0   1610612765   2024       00        Jalen Duren    Jalen        jalen-duren   0        C   6-10    250  NOV 18, 2003  21.0   2              Memphis    1631105  Draft Rights Traded from NYK on 07/06/22        Jalen Duren
1   1610612765   2024       00  Ronald Holland II   Ronald  ronald-holland-ii  00        F    6-8    206  JUL 07, 2005  19.0   R  NBA G League Ignite    1641842                     #5 Pick in 2024 Draft  Ronald Holland II
2   1610612765   2024       00    Cade Cunningham     Cade    cade-cunningham   2        G    6-6    220  SEP 25, 2001  23.0   3       Oklahoma State    1630595                     #1 Pick in 2021 Draft    Cade Cunningham
3   1610612765   2024       00      Malik Beasley    Malik      malik-beasley   5        G    6-4    187  NOV 26, 1996  28.0   8        Florida State    1627736                        Signed on 07/11/24      Malik Beasley
4   1610612765   2024       00          Paul Reed     Paul          paul-reed   7        F    6-9    210  JUN 14, 1999  25.0   4               DePaul    1630194            Awarded on Waivers on 07/09/24          Paul Reed
5   1610612765   2024       00   Tim Hardaway Jr.      Tim    tim-hardaway-jr   8      G-F    6-5    205  MAR 16, 1992  33.0  11             Michigan     203501               Traded from DAL on 07/06/24   Tim Hardaway Jr.
6   1610612765   2024       00     Ausar Thompson    Ausar     ausar-thompson   9      G-F    6-6    205  JAN 30, 2003  22.0   1       Overtime Elite    1641709                     #5 Pick in 2023 Draft     Ausar Thompson
7   1610612765   2024       00      Tobias Harris   Tobias      tobias-harris  12        F    6-8    226  JUL 15, 1992  32.0  13            Tennessee     202699                        Signed on 07/08/24      Tobias Harris
8   1610612765   2024       00     Ron Harper Jr.      Ron      ron-harper-jr  13      G-F    6-4    233  APR 12, 2000  24.0   2              Rutgers    1631199                        Signed on 01/06/25     Ron Harper Jr.
9   1610612765   2024       00    Dennis Schröder   Dennis    dennis-schröder  17        G    6-1    175  SEP 15, 1993  31.0  11         Braunschweig     203471               Traded from GSW on 02/06/25    Dennis Schroder
10  1610612765   2024       00  Simone Fontecchio   Simone  simone-fontecchio  19        F    6-7    209  DEC 09, 1995  29.0   2             Baskonia    1631323               Traded from UTA on 02/08/24  Simone Fontecchio
11  1610612765   2024       00         Jaden Ivey    Jaden         jaden-ivey  23        G    6-4    195  FEB 13, 2002  23.0   2               Purdue    1631093                     #5 Pick in 2022 Draft         Jaden Ivey
12  1610612765   2024       00     Daniss Jenkins   Daniss     daniss-jenkins  24        G    6-3    165  AUG 17, 2001  23.0   R           St. John's    1642450                        Signed on 07/06/24     Daniss Jenkins
13  1610612765   2024       00      Marcus Sasser   Marcus      marcus-sasser  25        G    6-2    195  SEP 21, 2000  24.0   1              Houston    1631204  Draft Rights Traded from BOS on 06/28/23      Marcus Sasser
14  1610612765   2024       00     Isaiah Stewart   Isaiah     isaiah-stewart  28      F-C    6-8    250  MAY 22, 2001  23.0   4           Washington    1630191  Draft Rights Traded from HOU on 11/24/20     Isaiah Stewart
15  1610612765   2024       00      Bobi Klintman     Bobi      bobi-klintman  34        F    6-9    225  MAR 06, 2003  22.0   R               Cairns    1641752  Draft Rights Traded from MIN on 07/06/24      Bobi Klintman
16  1610612765   2024       00         Tolu Smith     Tolu         tolu-smith  35        F   6-11   None  JUL 26, 2000  24.0   R    Mississippi State    1642449                        Signed on 09/17/24         Tolu Smith
17  1610612765   2024       00   Lindy Waters III    Lindy   lindy-waters-iii  43        F    6-6    210  JUL 28, 1997  27.0   3       Oklahoma State    1630322               Traded from GSW on 02/06/25   Lindy Waters III

LAC Roster:

        TeamID SEASON LeagueID               PLAYER NICKNAME         PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP               SCHOOL  PLAYER_ID                 HOW_ACQUIRED           PLAYER_uni
0   1610612746   2024       00         James Harden    James        james-harden   1        G    6-5    220  AUG 26, 1989  35.0  15        Arizona State     201935  Traded from PHI on 11/01/23         James Harden
1   1610612746   2024       00        Kawhi Leonard    Kawhi       kawhi-leonard   2        F    6-7    225  JUN 29, 1991  33.0  12      San Diego State     202695           Signed on 07/09/19        Kawhi Leonard
2   1610612746   2024       00           Seth Lundy     Seth          seth-lundy   5      G-F    6-4    220  APR 02, 2000  24.0   1           Penn State    1641754           Signed on 03/01/25           Seth Lundy
3   1610612746   2024       00          Amir Coffey     Amir         amir-coffey   7      G-F    6-7    210  JUN 17, 1997  27.0   5            Minnesota    1629599           Signed on 07/09/19          Amir Coffey
4   1610612746   2024       00            Kris Dunn     Kris           kris-dunn   8        G    6-3    205  MAR 18, 1994  31.0   8           Providence    1627739  Traded from UTA on 07/18/24            Kris Dunn
5   1610612746   2024       00      Trentyn Flowers  Trentyn     trentyn-flowers   9        F    6-9    185  MAR 08, 2005  20.0   R             Adelaide    1642280           Signed on 07/24/24      Trentyn Flowers
6   1610612746   2024       00    Bogdan Bogdanović   Bogdan   bogdan-bogdanović  10        G    6-5    225  AUG 18, 1992  32.0   7           Fenerbahce     203992  Traded from ATL on 02/06/25    Bogdan Bogdanovic
7   1610612746   2024       00        Jordan Miller   Jordan       jordan-miller  11        G    6-5    194  JAN 23, 2000  25.0   1                Miami    1641757       #48 Pick in 2023 Draft        Jordan Miller
8   1610612746   2024       00         Cam Christie      Cam        cam-christie  12        G    6-6    190  JUL 24, 2005  19.0   R            Minnesota    1642353       #46 Pick in 2024 Draft         Cam Christie
9   1610612746   2024       00         Drew Eubanks     Drew        drew-eubanks  15      F-C   6-10    245  FEB 01, 1997  28.0   6         Oregon State    1629234  Traded from UTA on 02/01/25         Drew Eubanks
10  1610612746   2024       00           Kobe Brown     Kobe          kobe-brown  21        F    6-7    250  JAN 01, 2000  25.0   1             Missouri    1641738       #30 Pick in 2023 Draft           Kobe Brown
11  1610612746   2024       00  Patrick Baldwin Jr.  Patrick  patrick-baldwin-jr  23        F    6-9    220  NOV 18, 2002  22.0   2  Wisconsin-Milwaukee    1631116           Signed on 03/01/25  Patrick Baldwin Jr.
12  1610612746   2024       00        Norman Powell   Norman       norman-powell  24        G    6-4    215  MAY 25, 1993  31.0   9                 UCLA    1626181  Traded from POR on 02/04/22        Norman Powell
13  1610612746   2024       00          Ben Simmons      Ben         ben-simmons  25      G-F   6-10    240  JUL 20, 1996  28.0   6      Louisiana State    1627732           Signed on 02/10/25          Ben Simmons
14  1610612746   2024       00        Nicolas Batum  Nicolas       nicolas-batum  33      G-F    6-8    230  DEC 14, 1988  36.0  16              Le Mans     201587           Signed on 07/09/24        Nicolas Batum
15  1610612746   2024       00          Ivica Zubac    Ivica         ivica-zubac  40        C    7-0    240  MAR 18, 1997  28.0   8          Mega Basket    1627826  Traded from LAL on 02/07/19          Ivica Zubac
16  1610612746   2024       00    Derrick Jones Jr.  Derrick    derrick-jones-jr  55        F    6-6    210  FEB 15, 1997  28.0   8                 UNLV    1627884           Signed on 07/09/24    Derrick Jones Jr.
17  1610612746   2024       00          Patty Mills    Patty         patty-mills  88        G    6-2    180  AUG 11, 1988  36.0  15           St. Mary's     201988  Traded from UTA on 02/01/25          Patty Mills

BKN Roster:

        TeamID SEASON LeagueID             PLAYER    NICKNAME       PLAYER_SLUG   NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP               SCHOOL  PLAYER_ID                              HOW_ACQUIRED         PLAYER_uni
0   1610612751   2024       00         Drew Timme        Drew        drew-timme  None        F   6-10    235  SEP 09, 2000  24.0   R              Gonzaga    1631166                        Signed on 03/28/25         Drew Timme
1   1610612751   2024       00    Dariq Whitehead       Dariq   dariq-whitehead     0      G-F    6-6    220  AUG 01, 2004  20.0   1                 Duke    1641727                    #22 Pick in 2023 Draft    Dariq Whitehead
2   1610612751   2024       00   D'Angelo Russell    D'Angelo   dangelo-russell     1        G    6-3    193  FEB 23, 1996  29.0   9           Ohio State    1626156               Traded from LAL on 12/29/24   D'Angelo Russell
3   1610612751   2024       00    Cameron Johnson     Cameron   cameron-johnson     2        F    6-8    210  MAR 03, 1996  29.0   5       North Carolina    1629661               Traded from PHX on 02/09/23    Cameron Johnson
4   1610612751   2024       00      Reece Beekman       Reece     reece-beekman     4        G    6-3    190  OCT 08, 2001  23.0   R             Virginia    1641736                                      None      Reece Beekman
5   1610612751   2024       00    Ziaire Williams      Ziaire   ziaire-williams     8        F    6-9    185  SEP 12, 2001  23.0   3             Stanford    1630533               Traded from MEM on 07/19/24    Ziaire Williams
6   1610612751   2024       00    Trendon Watford     Trendon   trendon-watford     9      G-F    6-8    237  NOV 09, 2000  24.0   3      Louisiana State    1630570                        Signed on 08/03/23    Trendon Watford
7   1610612751   2024       00      Tyson Etienne       Tyson     tyson-etienne    10        G    6-2    200  SEP 17, 1999  25.0   R        Wichita State    1630623                        Signed on 09/10/24      Tyson Etienne
8   1610612751   2024       00    Tosan Evbuomwan       Tosan   tosan-evbuomwan    12        F    6-7    217  FEB 16, 2001  24.0   1            Princeton    1641787                        Signed on 01/01/25    Tosan Evbuomwan
9   1610612751   2024       00      Tyrese Martin      Tyrese     tyrese-martin    13        F    6-6    215  MAR 07, 1999  26.0   1          Connecticut    1631213                        Signed on 09/20/24      Tyrese Martin
10  1610612751   2024       00  De'Anthony Melton  De'Anthony  deanthony-melton    14        G    6-3    200  MAY 28, 1998  26.0   6  Southern California    1629001               Traded from GSW on 12/15/24  De'Anthony Melton
11  1610612751   2024       00     Day'Ron Sharpe     Day'Ron     dayron-sharpe    20        C    6-9    265  NOV 06, 2001  23.0   3       North Carolina    1630549  Draft Rights Traded from PHX on 08/06/21     Day'Ron Sharpe
12  1610612751   2024       00       Noah Clowney        Noah      noah-clowney    21      F-C    6-9    210  JUL 14, 2004  20.0   1              Alabama    1641730                    #21 Pick in 2023 Draft       Noah Clowney
13  1610612751   2024       00       Jalen Wilson       Jalen      jalen-wilson    22        F    6-6    220  NOV 04, 2000  24.0   1               Kansas    1630592                    #51 Pick in 2023 Draft       Jalen Wilson
14  1610612751   2024       00         Cam Thomas         Cam        cam-thomas    24        G    6-3    210  OCT 13, 2001  23.0   3      Louisiana State    1630560                    #27 Pick in 2021 Draft         Cam Thomas
15  1610612751   2024       00      Maxwell Lewis     Maxwell     maxwell-lewis    27        F    6-7    215  JUL 27, 2002  22.0   1           Pepperdine    1641721               Traded from LAL on 12/29/24      Maxwell Lewis
16  1610612751   2024       00        Nic Claxton         Nic       nic-claxton    33        C   6-11    215  APR 17, 1999  25.0   5              Georgia    1629651                    #31 Pick in 2019 Draft        Nic Claxton
17  1610612751   2024       00       Keon Johnson        Keon      keon-johnson    45        G    6-5    185  MAR 10, 2002  23.0   3            Tennessee    1630553                        Signed on 11/01/23       Keon Johnson

CHA Roster:

        TeamID SEASON LeagueID             PLAYER NICKNAME       PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP               SCHOOL  PLAYER_ID                              HOW_ACQUIRED         PLAYER_uni
0   1610612766   2024       00      Miles Bridges    Miles     miles-bridges   0        F    6-7    225  MAR 21, 1998  27.0   5       Michigan State    1628970  Draft Rights Traded from LAC on 06/21/18      Miles Bridges
1   1610612766   2024       00        LaMelo Ball   LaMelo       lamelo-ball   1        G    6-7    180  AUG 22, 2001  23.0   4            Illawarra    1630163                     #3 Pick in 2020 Draft        LaMelo Ball
2   1610612766   2024       00     Grant Williams    Grant    grant-williams   2        F    6-6    236  NOV 30, 1998  26.0   5            Tennessee    1629684               Traded from DAL on 02/08/24     Grant Williams
3   1610612766   2024       00    DaQuan Jeffries   DaQuan   daquan-jeffries   3      G-F    6-5    222  AUG 30, 1997  27.0   5                Tulsa    1629610               Traded from NYK on 10/02/24    DaQuan Jeffries
4   1610612766   2024       00      Mark Williams     Mark     mark-williams   5        C    7-0    240  DEC 16, 2001  23.0   2                 Duke    1631109                    #15 Pick in 2022 Draft      Mark Williams
5   1610612766   2024       00       Damion Baugh   Damion      damion-baugh   7        G    6-4    194  AUG 03, 2000  24.0   R                  TCU    1641878                        Signed on 02/12/25       Damion Baugh
6   1610612766   2024       00     Nick Smith Jr.     Nick     nick-smith-jr   8        G    6-2    185  APR 18, 2004  20.0   1             Arkansas    1641733                    #27 Pick in 2023 Draft     Nick Smith Jr.
7   1610612766   2024       00  Wendell Moore Jr.  Wendell  wendell-moore-jr   9        G    6-5    215  SEP 18, 2001  23.0   2                 Duke    1631111                        Signed on 02/15/25  Wendell Moore Jr.
8   1610612766   2024       00         Josh Green     Josh        josh-green  10        G    6-5    200  NOV 16, 2000  24.0   4              Arizona    1630182               Traded from DAL on 07/06/24         Josh Green
9   1610612766   2024       00       Jusuf Nurkić    Jusuf      jusuf-nurkić  11        C    7-0    290  AUG 23, 1994  30.0  10             Cedevita     203994               Traded from PHX on 02/06/25       Jusuf Nurkic
10  1610612766   2024       00        Josh Okogie     Josh       josh-okogie  12        G    6-4    213  SEP 01, 1998  26.0   6         Georgia Tech    1629006               Traded from PHX on 01/15/25        Josh Okogie
11  1610612766   2024       00     Moussa Diabaté   Moussa    moussa-diabaté  14        F    6-9    210  JAN 21, 2002  23.0   2             Michigan    1631217                        Signed on 07/31/24     Moussa Diabate
12  1610612766   2024       00           Tre Mann      Tre          tre-mann  23        G    6-3    178  FEB 03, 2001  24.0   3              Florida    1630544               Traded from OKC on 02/08/24           Tre Mann
13  1610612766   2024       00     Brandon Miller  Brandon    brandon-miller  24        F    6-7    200  NOV 22, 2002  22.0   1              Alabama    1641706                     #2 Pick in 2023 Draft     Brandon Miller
14  1610612766   2024       00         KJ Simpson       KJ        kj-simpson  25        G    6-0    189  AUG 08, 2002  22.0   R             Colorado    1642354                    #42 Pick in 2024 Draft         KJ Simpson
15  1610612766   2024       00         Seth Curry     Seth        seth-curry  30        G    6-1    185  AUG 23, 1990  34.0  10                 Duke     203552               Traded from DAL on 02/08/24         Seth Curry
16  1610612766   2024       00     Tidjane Salaün  Tidjane    tidjane-salaün  31        F    6-8    207  AUG 10, 2005  19.0   R               Cholet    1642275                     #6 Pick in 2024 Draft     Tidjane Salaun
17  1610612766   2024       00         Taj Gibson      Taj        taj-gibson  67        F    6-9    232  JUN 24, 1985  39.0  15  Southern California     201959                        Signed on 07/13/24         Taj Gibson

TOR Roster:

        TeamID SEASON LeagueID             PLAYER  NICKNAME        PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP              SCHOOL  PLAYER_ID                              HOW_ACQUIRED         PLAYER_uni
0   1610612761   2024       00        A.J. Lawson      A.J.          aj-lawson   0        G    6-6    179  JUL 15, 2000  24.0   2      South Carolina    1630639                        Signed on 12/11/24        A.J. Lawson
1   1610612761   2024       00        Gradey Dick    Gradey        gradey-dick   1      G-F    6-6    200  NOV 20, 2003  21.0   1              Kansas    1641711                    #13 Pick in 2023 Draft        Gradey Dick
2   1610612761   2024       00     Jonathan Mogbo  Jonathan     jonathan-mogbo   2        F    6-9    225  OCT 29, 2001  23.0   R       San Francisco    1642367                    #31 Pick in 2024 Draft     Jonathan Mogbo
3   1610612761   2024       00     Brandon Ingram   Brandon     brandon-ingram   3        F    6-8    190  SEP 02, 1997  27.0   8                Duke    1627742               Traded from NOP on 02/06/25     Brandon Ingram
4   1610612761   2024       00     Scottie Barnes   Scottie     scottie-barnes   4      F-G    6-7    237  AUG 01, 2001  23.0   3       Florida State    1630567                     #4 Pick in 2021 Draft     Scottie Barnes
5   1610612761   2024       00  Immanuel Quickley  Immanuel  immanuel-quickley   5        G    6-2    190  JUN 17, 1999  25.0   4            Kentucky    1630193               Traded from NYK on 12/30/23  Immanuel Quickley
6   1610612761   2024       00       Jared Rhoden     Jared       jared-rhoden   8        G    6-5    210  AUG 27, 1999  25.0   2          Seton Hall    1631197                        Signed on 02/19/25       Jared Rhoden
7   1610612761   2024       00         RJ Barrett        RJ         rj-barrett   9      F-G    6-6    214  JUN 14, 2000  24.0   5                Duke    1629628               Traded from NYK on 12/30/23         RJ Barrett
8   1610612761   2024       00        Cole Swider      Cole        cole-swider  13        F    6-8    220  MAY 08, 1999  25.0   2            Syracuse    1631306                        Signed on 03/26/25        Cole Swider
9   1610612761   2024       00     Ja'Kobe Walter   Ja'Kobe      jakobe-walter  14        G    6-5    180  SEP 04, 2004  20.0   R              Baylor    1642266                    #19 Pick in 2024 Draft     Ja'Kobe Walter
10  1610612761   2024       00     Garrett Temple   Garrett     garrett-temple  17      G-F    6-5    195  MAY 08, 1986  38.0  14     Louisiana State     202066                        Signed on 07/31/23     Garrett Temple
11  1610612761   2024       00       Jakob Poeltl     Jakob       jakob-poeltl  19        C    7-0    260  OCT 15, 1995  29.0   8                Utah    1627751               Traded from SAS on 02/09/23       Jakob Poeltl
12  1610612761   2024       00   Orlando Robinson   Orlando   orlando-robinson  21        C   6-10    235  JUL 10, 2000  24.0   2        Fresno State    1631115                        Signed on 01/18/25   Orlando Robinson
13  1610612761   2024       00     Ulrich Chomche    Ulrich     ulrich-chomche  22        C   6-11    235  DEC 30, 2005  19.0   R  NBA Global Academy    1642279  Draft Rights Traded from MEM on 07/06/24     Ulrich Chomche
14  1610612761   2024       00        Jamal Shead     Jamal        jamal-shead  23        G    6-1    200  JUL 24, 2002  22.0   R             Houston    1642347  Draft Rights Traded from SAC on 06/28/24        Jamal Shead
15  1610612761   2024       00      Chris Boucher     Chris      chris-boucher  25        F    6-9    200  JAN 11, 1993  32.0   7              Oregon    1628449                        Signed on 07/20/18      Chris Boucher
16  1610612761   2024       00       Ochai Agbaji     Ochai       ochai-agbaji  30        G    6-5    215  APR 20, 2000  24.0   2              Kansas    1630534               Traded from UTA on 02/08/24       Ochai Agbaji
17  1610612761   2024       00     Jamison Battle   Jamison     jamison-battle  77        F    6-7    220  MAY 10, 2001  23.0   R          Ohio State    1642419                        Signed on 07/16/24     Jamison Battle

NYK Roster:

        TeamID SEASON LeagueID              PLAYER      NICKNAME         PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP               SCHOOL  PLAYER_ID                              HOW_ACQUIRED          PLAYER_uni
0   1610612752   2024       00        Delon Wright         Delon        delon-wright   0        G    6-5    185  APR 26, 1992  32.0   9                 Utah    1626153               Traded from MIL on 02/06/25        Delon Wright
1   1610612752   2024       00    MarJon Beauchamp        MarJon    marjon-beauchamp   0        F    6-7    199  OCT 12, 2000  24.0   2  NBA G League Ignite    1630699                        Signed on 03/04/25    MarJon Beauchamp
2   1610612752   2024       00         P.J. Tucker          P.J.           pj-tucker            F    6-5    245  MAY 05, 1985  39.0  13                Texas     200782                        Signed on 03/10/25         P.J. Tucker
3   1610612752   2024       00       Cameron Payne       Cameron       cameron-payne   1        G    6-3    183  AUG 08, 1994  30.0   9         Murray State    1626166                        Signed on 07/15/24       Cameron Payne
4   1610612752   2024       00       Miles McBride         Miles       miles-mcbride   2        G    6-1    195  SEP 08, 2000  24.0   3        West Virginia    1630540  Draft Rights Traded from OKC on 07/30/21       Miles McBride
5   1610612752   2024       00           Josh Hart          Josh           josh-hart   3        G    6-4    215  MAR 06, 1995  30.0   7            Villanova    1628404               Traded from POR on 02/09/23           Josh Hart
6   1610612752   2024       00       Pacôme Dadiet        Pacôme       pacôme-dadiet   4        F    6-8    210  JUL 27, 2005  19.0   R       Ratiopharm Ulm    1642359                    #25 Pick in 2024 Draft       Pacome Dadiet
7   1610612752   2024       00    Precious Achiuwa      Precious    precious-achiuwa   5        F    6-8    243  SEP 19, 1999  25.0   4              Memphis    1630173               Traded from TOR on 12/30/23    Precious Achiuwa
8   1610612752   2024       00          OG Anunoby            OG          og-anunoby   8      F-G    6-7    240  JUL 17, 1997  27.0   7              Indiana    1628384               Traded from TOR on 12/30/23          OG Anunoby
9   1610612752   2024       00  Kevin McCullar Jr.         Kevin   kevin-mccullar-jr   9        G    6-6    210  MAR 15, 2001  24.0   R               Kansas    1641755  Draft Rights Traded from PHX on 06/27/24  Kevin McCullar Jr.
10  1610612752   2024       00       Jalen Brunson         Jalen       jalen-brunson  11        G    6-2    190  AUG 31, 1996  28.0   6            Villanova    1628973                        Signed on 07/12/22       Jalen Brunson
11  1610612752   2024       00         Tyler Kolek         Tyler         tyler-kolek  13        G    6-3    195  MAR 27, 2001  24.0   R            Marquette    1642278  Draft Rights Traded from POR on 06/27/24         Tyler Kolek
12  1610612752   2024       00   Mitchell Robinson      Mitchell   mitchell-robinson  23      C-F    7-0    240  APR 01, 1998  26.0   6     Western Kentucky    1629011                    #36 Pick in 2018 Draft   Mitchell Robinson
13  1610612752   2024       00       Mikal Bridges         Mikal       mikal-bridges  25      G-F    6-6    209  AUG 30, 1996  28.0   6            Villanova    1628969               Traded from BKN on 07/06/24       Mikal Bridges
14  1610612752   2024       00        Anton Watson         Anton        anton-watson  28        F    6-8    225  OCT 06, 2000  24.0   R              Gonzaga    1641817                                      None        Anton Watson
15  1610612752   2024       00  Karl-Anthony Towns  Karl-Anthony  karl-anthony-towns  32      C-F    7-0    248  NOV 15, 1995  29.0   9             Kentucky    1626157               Traded from MIN on 10/02/24  Karl-Anthony Towns
16  1610612752   2024       00       Landry Shamet        Landry       landry-shamet  44        G    6-4    190  MAR 13, 1997  28.0   6        Wichita State    1629013                        Signed on 09/14/24       Landry Shamet
17  1610612752   2024       00      Ariel Hukporti         Ariel      ariel-hukporti  55        C   6-11    246  APR 12, 2002  22.0   R           MHP Riesen    1630574  Draft Rights Traded from DAL on 06/27/24      Ariel Hukporti

MIL Roster:

        TeamID SEASON LeagueID                 PLAYER NICKNAME            PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP               SCHOOL  PLAYER_ID                              HOW_ACQUIRED             PLAYER_uni
0   1610612749   2024       00         Damian Lillard   Damian         damian-lillard   0        G    6-2    195  JUL 15, 1990  34.0  12          Weber State     203081               Traded from POR on 09/27/23         Damian Lillard
1   1610612749   2024       00           Jericho Sims  Jericho           jericho-sims  00        C   6-10    250  OCT 20, 1998  26.0   3                Texas    1630579               Traded from NYK on 02/06/25           Jericho Sims
2   1610612749   2024       00       Kevin Porter Jr.    Kevin        kevin-porter-jr   3      G-F    6-4    203  MAY 04, 2000  24.0   4  Southern California    1629645               Traded from LAC on 02/06/25       Kevin Porter Jr.
3   1610612749   2024       00         Gary Trent Jr.     Gary          gary-trent-jr   5        G    6-5    204  JAN 18, 1999  26.0   6                 Duke    1629018                        Signed on 07/20/24         Gary Trent Jr.
4   1610612749   2024       00       Chris Livingston    Chris       chris-livingston   7        F    6-6    220  OCT 15, 2003  21.0   1             Kentucky    1641753                    #58 Pick in 2023 Draft       Chris Livingston
5   1610612749   2024       00           Bobby Portis    Bobby           bobby-portis   9        F   6-10    250  FEB 10, 1995  30.0   9             Arkansas    1626171                        Signed on 11/24/20           Bobby Portis
6   1610612749   2024       00            Brook Lopez    Brook            brook-lopez  11        C    7-1    282  APR 01, 1988  36.0  16             Stanford     201572                        Signed on 07/17/18            Brook Lopez
7   1610612749   2024       00         Taurean Prince  Taurean         taurean-prince  12        F    6-6    218  MAR 22, 1994  31.0   8               Baylor    1627752                        Signed on 07/09/24         Taurean Prince
8   1610612749   2024       00           Ryan Rollins     Ryan           ryan-rollins  13        G    6-3    180  JUL 03, 2002  22.0   2               Toledo    1631157                        Signed on 02/20/24           Ryan Rollins
9   1610612749   2024       00         Jamaree Bouyea  Jamaree         jamaree-bouyea  15        G    6-2    180  JUN 27, 1999  25.0   2        San Francisco    1631123                        Signed on 03/04/25         Jamaree Bouyea
10  1610612749   2024       00          Stanley Umude  Stanley          stanley-umude  17        G    6-6    210  APR 12, 1999  25.0   2             Arkansas    1630649                        Signed on 07/09/24          Stanley Umude
11  1610612749   2024       00             Kyle Kuzma     Kyle             kyle-kuzma  18        F    6-9    221  JUL 24, 1995  29.0   7                 Utah    1628398               Traded from WAS on 02/06/25             Kyle Kuzma
12  1610612749   2024       00               AJ Green       AJ               aj-green  20        G    6-4    190  SEP 27, 1999  25.0   2        Northern Iowa    1631260                        Signed on 07/01/22               AJ Green
13  1610612749   2024       00            Tyler Smith    Tyler            tyler-smith  21        F    6-9    224  NOV 02, 2004  20.0   R  NBA G League Ignite    1641890                    #33 Pick in 2024 Draft            Tyler Smith
14  1610612749   2024       00        Pat Connaughton      Pat        pat-connaughton  24        G    6-5    209  JAN 06, 1993  32.0   9           Notre Dame    1626192                        Signed on 08/01/18        Pat Connaughton
15  1610612749   2024       00  Giannis Antetokounmpo  Giannis  giannis-antetokounmpo  34        F   6-11    243  DEC 06, 1994  30.0  11        Filathlitikos     203507                    #15 Pick in 2013 Draft  Giannis Antetokounmpo
16  1610612749   2024       00             Pete Nance     Pete             pete-nance  35        F   6-10    225  FEB 19, 2000  25.0   1       North Carolina    1631250                        Signed on 02/27/25             Pete Nance
17  1610612749   2024       00      Andre Jackson Jr.    Andre       andre-jackson-jr  44        G    6-6    209  NOV 13, 2001  23.0   1          Connecticut    1641748  Draft Rights Traded from ORL on 06/22/23      Andre Jackson Jr.

MIN Roster:

        TeamID SEASON LeagueID                    PLAYER  NICKNAME               PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP                 SCHOOL  PLAYER_ID                              HOW_ACQUIRED                PLAYER_uni
0   1610612750   2024       00      Terrence Shannon Jr.  Terrence       terrence-shannon-jr  00      G-F    6-6    215  JUL 30, 2000  24.0   R               Illinois    1630545                    #27 Pick in 2024 Draft      Terrence Shannon Jr.
1   1610612750   2024       00          Donte DiVincenzo     Donte          donte-divincenzo   0        G    6-4    203  JAN 31, 1997  28.0   6              Villanova    1628978               Traded from NYK on 10/02/24          Donte DiVincenzo
2   1610612750   2024       00           Jaden McDaniels     Jaden           jaden-mcdaniels   3        F    6-9    185  SEP 29, 2000  24.0   4             Washington    1630183  Draft Rights Traded from OKC on 11/20/20           Jaden McDaniels
3   1610612750   2024       00            Rob Dillingham       Rob            rob-dillingham   4        G    6-3    175  JAN 04, 2005  20.0   R               Kentucky    1642265  Draft Rights Traded from SAS on 06/26/24            Rob Dillingham
4   1610612750   2024       00           Anthony Edwards   Anthony           anthony-edwards   5        G    6-4    225  AUG 05, 2001  23.0   4                Georgia    1630162                     #1 Pick in 2020 Draft           Anthony Edwards
5   1610612750   2024       00                Joe Ingles       Joe                joe-ingles   7      F-G    6-8    220  OCT 02, 1987  37.0  10       Maccabi Tel Aviv     204060                        Signed on 07/06/24                Joe Ingles
6   1610612750   2024       00               Josh Minott      Josh               josh-minott   8        F    6-8    205  NOV 25, 2002  22.0   2                Memphis    1631169  Draft Rights Traded from CHA on 06/24/22               Josh Minott
7   1610612750   2024       00  Nickeil Alexander-Walker   Nickeil  nickeil-alexander-walker   9        G    6-5    205  SEP 02, 1998  26.0   5          Virginia Tech    1629638               Traded from UTA on 02/09/23  Nickeil Alexander-Walker
8   1610612750   2024       00               Mike Conley      Mike               mike-conley  10        G    6-0    175  OCT 11, 1987  37.0  17             Ohio State     201144               Traded from UTA on 02/09/23               Mike Conley
9   1610612750   2024       00                  Naz Reid       Naz                  naz-reid  11      C-F    6-9    264  AUG 26, 1999  25.0   5        Louisiana State    1629675                        Signed on 07/04/19                  Naz Reid
10  1610612750   2024       00            Tristen Newton   Tristen            tristen-newton  13        G    6-5    190  APR 26, 2001  23.0   R            Connecticut    1641803                                      None            Tristen Newton
11  1610612750   2024       00             Jesse Edwards     Jesse             jesse-edwards  14        C    7-0    236  MAR 18, 2000  25.0   R          West Virginia    1642399                        Signed on 07/09/24             Jesse Edwards
12  1610612750   2024       00              Jaylen Clark    Jaylen              jaylen-clark  22        G    6-4    205  OCT 13, 2001  23.0   R                   UCLA    1641740                    #53 Pick in 2023 Draft              Jaylen Clark
13  1610612750   2024       00               Rudy Gobert      Rudy               rudy-gobert  27        C    7-1    258  JUN 26, 1992  32.0  11                 Cholet     203497               Traded from UTA on 07/06/22               Rudy Gobert
14  1610612750   2024       00             Julius Randle    Julius             julius-randle  30      F-C    6-9    250  NOV 29, 1994  30.0  10               Kentucky     203944               Traded from NYK on 10/02/24             Julius Randle
15  1610612750   2024       00            Leonard Miller   Leonard            leonard-miller  33        F   6-10    220  NOV 26, 2003  21.0   1    NBA G League Ignite    1631159  Draft Rights Traded from SAS on 06/23/23            Leonard Miller
16  1610612750   2024       00                Luka Garza      Luka                luka-garza  55        C   6-10    243  DEC 27, 1998  26.0   3                   Iowa    1630568                        Signed on 08/22/22                Luka Garza
17  1610612750   2024       00              Bones Hyland     Bones              bones-hyland  77        G    6-2    169  SEP 14, 2000  24.0   3  Virginia Commonwealth    1630538                        Signed on 02/27/25              Bones Hyland

GSW Roster:

        TeamID SEASON LeagueID                PLAYER  NICKNAME           PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP                      SCHOOL  PLAYER_ID                              HOW_ACQUIRED            PLAYER_uni
0   1610612744   2024       00        Gary Payton II      Gary        gary-payton-ii   0        G    6-2    195  DEC 01, 1992  32.0   8                Oregon State    1627780               Traded from POR on 02/09/23        Gary Payton II
1   1610612744   2024       00      Jonathan Kuminga  Jonathan      jonathan-kuminga  00        F    6-7    225  OCT 06, 2002  22.0   3         NBA G League Ignite    1630228                     #7 Pick in 2021 Draft      Jonathan Kuminga
2   1610612744   2024       00       Taran Armstrong     Taran       taran-armstrong   1        G    6-5    190  JAN 15, 2002  23.0   R           Cairns, Australia    1642379                        Signed on 02/24/25       Taran Armstrong
3   1610612744   2024       00    Brandin Podziemski   Brandin    brandin-podziemski   2        G    6-4    205  FEB 25, 2003  22.0   1                 Santa Clara    1641764                    #19 Pick in 2023 Draft    Brandin Podziemski
4   1610612744   2024       00           Moses Moody     Moses           moses-moody   4        G    6-5    211  MAY 31, 2002  22.0   3                    Arkansas    1630541                    #14 Pick in 2021 Draft           Moses Moody
5   1610612744   2024       00          Kevon Looney     Kevon          kevon-looney   5        F    6-9    222  FEB 06, 1996  29.0   9                        UCLA    1626172                    #30 Pick in 2015 Draft          Kevon Looney
6   1610612744   2024       00           Buddy Hield     Buddy           buddy-hield   7        G    6-4    220  DEC 17, 1992  32.0   8                    Oklahoma    1627741               Traded from PHI on 07/06/24           Buddy Hield
7   1610612744   2024       00      Jimmy Butler III     Jimmy      jimmy-butler-iii  10        F    6-7    230  SEP 14, 1989  35.0  13                   Marquette     202710               Traded from MIA on 02/06/25      Jimmy Butler III
8   1610612744   2024       00           Braxton Key   Braxton           braxton-key  12        F    6-8    225  FEB 14, 1997  28.0   3                    Virginia    1630296                        Signed on 03/04/25           Braxton Key
9   1610612744   2024       00            Gui Santos       Gui            gui-santos  15        F    6-6    185  JUN 22, 2002  22.0   1                       Minas    1630611                    #55 Pick in 2022 Draft            Gui Santos
10  1610612744   2024       00          Quinten Post   Quinten          quinten-post  21        C    7-0    238  MAR 21, 2000  25.0   R              Boston College    1642366  Draft Rights Traded from POR on 07/06/24          Quinten Post
11  1610612744   2024       00        Draymond Green  Draymond        draymond-green  23        F    6-6    230  MAR 04, 1990  35.0  12              Michigan State     203110                    #35 Pick in 2012 Draft        Draymond Green
12  1610612744   2024       00         Stephen Curry   Stephen         stephen-curry  30        G    6-2    185  MAR 14, 1988  37.0  15                    Davidson     201939                     #7 Pick in 2009 Draft         Stephen Curry
13  1610612744   2024       00         Kevin Knox II     Kevin         kevin-knox-ii  31        F    6-8    215  AUG 11, 1999  25.0   6                    Kentucky    1628995                        Signed on 09/25/24         Kevin Knox II
14  1610612744   2024       00  Trayce Jackson-Davis    Trayce  trayce-jackson-davis  32        F    6-9    245  FEB 22, 2000  25.0   1                     Indiana    1631218  Draft Rights Traded from WAS on 06/23/23  Trayce Jackson-Davis
15  1610612744   2024       00          Jackson Rowe   Jackson          jackson-rowe  44        F    6-7    210  JAN 04, 1997  28.0   R  California State-Fullerton    1642050                        Signed on 07/19/24          Jackson Rowe
16  1610612744   2024       00           Pat Spencer       Pat           pat-spencer  61        G    6-3    205  JUL 04, 1996  28.0   1                Northwestern    1630311                        Signed on 07/23/22           Pat Spencer

NOP Roster:

        TeamID SEASON LeagueID                  PLAYER  NICKNAME             PLAYER_SLUG   NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP              SCHOOL  PLAYER_ID                              HOW_ACQUIRED              PLAYER_uni
0   1610612740   2024       00        Keion Brooks Jr.     Keion         keion-brooks-jr  None        F    6-7    210  AUG 07, 2000  24.0   R          Washington    1631232                        Signed on 09/23/24        Keion Brooks Jr.
1   1610612740   2024       00             Bruce Brown     Bruce             bruce-brown    00      G-F    6-4    202  AUG 15, 1996  28.0   6               Miami    1628971               Traded from TOR on 02/06/25             Bruce Brown
2   1610612740   2024       00         Zion Williamson      Zion         zion-williamson     1        F    6-6    284  JUL 06, 2000  24.0   4                Duke    1629627                     #1 Pick in 2019 Draft         Zion Williamson
3   1610612740   2024       00           Herbert Jones   Herbert           herbert-jones     2        F    6-7    206  OCT 06, 1998  26.0   3             Alabama    1630529                    #35 Pick in 2021 Draft           Herbert Jones
4   1610612740   2024       00             CJ McCollum        CJ             cj-mccollum     3        G    6-3    190  SEP 19, 1991  33.0  11              Lehigh     203468               Traded from POR on 02/08/22             CJ McCollum
5   1610612740   2024       00         Dejounte Murray  Dejounte         dejounte-murray     5        G    6-4    180  SEP 19, 1996  28.0   7          Washington    1627749               Traded from ATL on 07/06/24         Dejounte Murray
6   1610612740   2024       00              Jamal Cain     Jamal              jamal-cain     8        F    6-6    191  MAR 20, 1999  26.0   2             Oakland    1631288                        Signed on 07/12/24              Jamal Cain
7   1610612740   2024       00          Brandon Boston   Brandon          brandon-boston    11        G    6-6    188  NOV 28, 2001  23.0   3            Kentucky    1630527            Awarded on Waivers on 10/21/24          Brandon Boston
8   1610612740   2024       00          Antonio Reeves   Antonio          antonio-reeves    12        G    6-5    205  NOV 20, 2002  22.0   R            Kentucky    1641810  Draft Rights Traded from ORL on 06/27/24          Antonio Reeves
9   1610612740   2024       00            Kelly Olynyk     Kelly            kelly-olynyk    13      F-C   6-11    240  APR 19, 1991  33.0  11             Gonzaga     203482               Traded from TOR on 02/06/25            Kelly Olynyk
10  1610612740   2024       00           Jose Alvarado      Jose           jose-alvarado    15        G    6-0    179  APR 12, 1998  26.0   3        Georgia Tech    1630631                        Signed on 08/18/21           Jose Alvarado
11  1610612740   2024       00          Karlo Matković     Karlo          karlo-matković    17      F-C   6-10    231  MAR 30, 2001  24.0   R         Mega Basket    1631255                    #52 Pick in 2022 Draft          Karlo Matkovic
12  1610612740   2024       00              Yves Missi      Yves              yves-missi    21        C   6-11    235  MAY 14, 2004  20.0   R              Baylor    1642274                    #21 Pick in 2024 Draft              Yves Missi
13  1610612740   2024       00           Elfrid Payton    Elfrid           elfrid-payton    22        G    6-3    195  FEB 22, 1994  31.0   8  Louisana-Lafayette     203901                        Signed on 03/21/25           Elfrid Payton
14  1610612740   2024       00          Jordan Hawkins    Jordan          jordan-hawkins    24        G    6-5    190  APR 29, 2002  22.0   1         Connecticut    1641722                    #14 Pick in 2023 Draft          Jordan Hawkins
15  1610612740   2024       00         Trey Murphy III      Trey         trey-murphy-iii    25        F    6-8    206  JUN 18, 2000  24.0   3            Virginia    1630530  Draft Rights Traded from MEM on 08/07/21         Trey Murphy III
16  1610612740   2024       00         Lester Quinones    Lester         lester-quinones    25        G    6-4    208  NOV 16, 2000  24.0   2             Memphis    1631311                        Signed on 03/02/25         Lester Quinones
17  1610612740   2024       00  Jeremiah Robinson-Earl  Jeremiah  jeremiah-robinson-earl    50        F    6-8    240  NOV 03, 2000  24.0   3           Villanova    1630526                        Signed on 11/03/23  Jeremiah Robinson-Earl

UTA Roster:

        TeamID SEASON LeagueID            PLAYER NICKNAME       PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP               SCHOOL  PLAYER_ID                              HOW_ACQUIRED        PLAYER_uni
0   1610612762   2024       00   Jordan Clarkson   Jordan   jordan-clarkson  00        G    6-3    194  JUN 07, 1992  32.0  10             Missouri     203903               Traded from CLE on 12/23/19   Jordan Clarkson
1   1610612762   2024       00  Taylor Hendricks   Taylor  taylor-hendricks   0        F    6-9    215  NOV 22, 2003  21.0   1      Central Florida    1641707                     #9 Pick in 2023 Draft  Taylor Hendricks
2   1610612762   2024       00     Collin Sexton   Collin     collin-sexton   2        G    6-3    190  JAN 04, 1999  26.0   6              Alabama    1629012               Traded from CLE on 09/03/22     Collin Sexton
3   1610612762   2024       00    Keyonte George  Keyonte    keyonte-george   3        G    6-4    185  NOV 08, 2003  21.0   1               Baylor    1641718                    #16 Pick in 2023 Draft    Keyonte George
4   1610612762   2024       00     Cody Williams     Cody     cody-williams   5        F    6-7    190  NOV 20, 2004  20.0   R             Colorado    1642262                    #10 Pick in 2024 Draft     Cody Williams
5   1610612762   2024       00    Jaden Springer    Jaden    jaden-springer  11        G    6-4    202  SEP 25, 2002  22.0   3            Tennessee    1630531                        Signed on 02/20/25    Jaden Springer
6   1610612762   2024       00    Isaiah Collier   Isaiah    isaiah-collier  13        G    6-3    210  OCT 08, 2004  20.0   R  Southern California    1642268                    #29 Pick in 2024 Draft    Isaiah Collier
7   1610612762   2024       00   Elijah Harkless   Elijah   elijah-harkless  16        G    6-3    195  FEB 03, 2000  25.0   R                 UNLV    1641989                        Signed on 01/01/25   Elijah Harkless
8   1610612762   2024       00    Svi Mykhailiuk      Svi    svi-mykhailiuk  19      G-F    6-7    205  JUN 10, 1997  27.0   6               Kansas    1629004                        Signed on 08/10/24    Svi Mykhailiuk
9   1610612762   2024       00      John Collins     John      john-collins  20      F-C    6-9    226  SEP 23, 1997  27.0   7          Wake Forest    1628381               Traded from ATL on 07/07/23      John Collins
10  1610612762   2024       00   Kyle Filipowski     Kyle   kyle-filipowski  22        C   6-11    250  NOV 07, 2003  21.0   R                 Duke    1642271                    #32 Pick in 2024 Draft   Kyle Filipowski
11  1610612762   2024       00   Lauri Markkanen    Lauri   lauri-markkanen  23      F-C    7-0    240  MAY 22, 1997  27.0   7              Arizona    1628374               Traded from CLE on 09/03/22   Lauri Markkanen
12  1610612762   2024       00    Walker Kessler   Walker    walker-kessler  24        C    7-0    245  JUL 26, 2001  23.0   2               Auburn    1631117  Draft Rights Traded from MIN on 07/06/22    Walker Kessler
13  1610612762   2024       00      Micah Potter    Micah      micah-potter  25        C    6-9    248  APR 06, 1998  26.0   3            Wisconsin    1630695                        Signed on 10/12/22      Micah Potter
14  1610612762   2024       00  Brice Sensabaugh    Brice  brice-sensabaugh  28        F    6-5    235  OCT 30, 2003  21.0   1           Ohio State    1641729                    #28 Pick in 2023 Draft  Brice Sensabaugh
15  1610612762   2024       00     Johnny Juzang   Johnny     johnny-juzang  33        G    6-5    226  MAR 17, 2001  24.0   2                 UCLA    1630548                        Signed on 07/15/22     Johnny Juzang
16  1610612762   2024       00    Oscar Tshiebwe    Oscar    oscar-tshiebwe  34      F-C    6-8    255  NOV 27, 1999  25.0   1             Kentucky    1631131                        Signed on 08/12/24    Oscar Tshiebwe
17  1610612762   2024       00         KJ Martin       KJ         kj-martin  99        F    6-6    215  JAN 06, 2001  24.0   4     IMG Academy (FL)    1630231               Traded from DET on 02/06/25         KJ Martin

DEN Roster:

        TeamID SEASON LeagueID              PLAYER   NICKNAME        PLAYER_SLUG NUM POSITION HEIGHT WEIGHT    BIRTH_DATE   AGE EXP            SCHOOL  PLAYER_ID                              HOW_ACQUIRED          PLAYER_uni
0   1610612743   2024       00     Christian Braun  Christian    christian-braun   0        G    6-6    220  APR 17, 2001  23.0   2            Kansas    1631128                    #21 Pick in 2022 Draft     Christian Braun
1   1610612743   2024       00  Michael Porter Jr.    Michael  michael-porter-jr   1        F   6-10    218  JUN 29, 1998  26.0   5          Missouri    1629008                    #14 Pick in 2018 Draft  Michael Porter Jr.
2   1610612743   2024       00    Julian Strawther     Julian   julian-strawther   3        G    6-6    205  APR 18, 2002  22.0   1           Gonzaga    1631124  Draft Rights Traded from IND on 06/23/23    Julian Strawther
3   1610612743   2024       00   Russell Westbrook    Russell  russell-westbrook   4        G    6-4    200  NOV 12, 1988  36.0  16              UCLA     201566                        Signed on 07/26/24   Russell Westbrook
4   1610612743   2024       00        Hunter Tyson     Hunter       hunter-tyson   5        F    6-8    215  JUN 13, 2000  24.0   1           Clemson    1641816  Draft Rights Traded from OKC on 06/23/23        Hunter Tyson
5   1610612743   2024       00      DeAndre Jordan    DeAndre     deandre-jordan   6        C   6-11    265  JUL 21, 1988  36.0  16         Texas A&M     201599                        Signed on 07/11/22      DeAndre Jordan
6   1610612743   2024       00       Peyton Watson     Peyton      peyton-watson   8        G    6-7    200  SEP 11, 2002  22.0   2              UCLA    1631212  Draft Rights Traded from OKC on 06/23/22       Peyton Watson
7   1610612743   2024       00         Dario Šarić      Dario        dario-šarić   9      F-C   6-10    225  APR 08, 1994  30.0   7      Anadolu Efes     203967                        Signed on 07/12/24         Dario Saric
8   1610612743   2024       00             PJ Hall         PJ            pj-hall  13        C   6-10    245  FEB 21, 2002  23.0   R           Clemson    1641790                        Signed on 07/10/24             PJ Hall
9   1610612743   2024       00     DaRon Holmes II      DaRon    daron-holmes-ii  14        F   6-10    225  AUG 15, 2002  22.0   R            Dayton    1641747  Draft Rights Traded from PHX on 06/26/24     DaRon Holmes II
10  1610612743   2024       00        Nikola Jokić     Nikola       nikola-jokić  15        C   6-11    284  FEB 19, 1995  30.0   9       Mega Basket     203999                    #41 Pick in 2014 Draft        Nikola Jokic
11  1610612743   2024       00       Spencer Jones    Spencer      spencer-jones  21        F    6-7    225  JUN 14, 2001  23.0   R          Stanford    1642461                        Signed on 07/30/24       Spencer Jones
12  1610612743   2024       00          Zeke Nnaji       Zeke         zeke-nnaji  22      F-C    6-9    240  JAN 09, 2001  24.0   4           Arizona    1630192                    #22 Pick in 2020 Draft          Zeke Nnaji
13  1610612743   2024       00      Trey Alexander       Trey     trey-alexander  23        G    6-4    185  MAY 02, 2003  21.0   R         Creighton    1641725                        Signed on 07/03/24      Trey Alexander
14  1610612743   2024       00       Jalen Pickett      Jalen      jalen-pickett  24        G    6-2    202  OCT 22, 1999  25.0   1        Penn State    1629618  Draft Rights Traded from IND on 06/23/23       Jalen Pickett
15  1610612743   2024       00        Jamal Murray      Jamal       jamal-murray  27        G    6-4    215  FEB 23, 1997  28.0   7          Kentucky    1627750                     #7 Pick in 2016 Draft        Jamal Murray
16  1610612743   2024       00       Vlatko Čančar     Vlatko      vlatko-čančar  31        F    6-8    236  APR 10, 1997  27.0   4  San Pablo Burgos    1628427                    #49 Pick in 2017 Draft       Vlatko Cancar
17  1610612743   2024       00        Aaron Gordon      Aaron       aaron-gordon  32        F    6-8    235  SEP 16, 1995  29.0  10           Arizona     203932               Traded from ORL on 03/25/21        Aaron Gordon

In [119]:


matched_players_list = []
for team_abbr, roster_df in team_rosters.items():
    # print(f"\n{team_abbr} Roster:")
    df_roster = roster_df[['PLAYER', 'PLAYER_uni']]

    if team_abbr in results_pts['team'].values:
        matched_players = df_roster[df_roster['PLAYER_uni'].isin(results_pts['Player'])]
        
        if not matched_players.empty:
            matched_players = matched_players['PLAYER']
            matched_players_list.append(matched_players)
            # display(matched_players)
            # print(matched_players)

# Combine all matched players into a single DataFrame
if matched_players_list:
    final_matched_df = pd.concat(matched_players_list, ignore_index=True)
    display(final_matched_df)  # Display the final combined DataFrame
else:
    print("No matches found.")


from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players

# Retrieve player ID (e.g., LeBron James)
player_list = final_matched_df.tolist()
for basketball_players in player_list:
    found_players = players.find_players_by_full_name(basketball_players)

    if found_players:
        a_player = found_players[0]
        player_id = a_player['id']

        # Fetch game log
        gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')
        games = gamelog.get_data_frames()[0]  # Extract DataFrame
        
        if not games.empty:
            latest_game = games.iloc[0]  # Get the most recent game
            print(f"{basketball_players}: {latest_game['PTS']} points")
        else:
            print(f"{basketball_players}: No game data available")

    else:
        print(f"Player not found: {basketball_players}")

0            Evan Mobley
1            Sam Merrill
2         Darius Garland
3          Jarrett Allen
4       Donovan Mitchell
5            Jalen Duren
6       Tim Hardaway Jr.
7         Ausar Thompson
8          Tobias Harris
9        Dennis Schröder
10          James Harden
11         Kawhi Leonard
12             Kris Dunn
13         Norman Powell
14           Ivica Zubac
15      D'Angelo Russell
16       Cameron Johnson
17       Ziaire Williams
18           Nic Claxton
19          Keon Johnson
20         Miles Bridges
21       DaQuan Jeffries
22         Mark Williams
23            Josh Green
24            KJ Simpson
25        Scottie Barnes
26     Immanuel Quickley
27        Ja'Kobe Walter
28          Jakob Poeltl
29        Jamison Battle
30             Josh Hart
31            OG Anunoby
32           Tyler Kolek
33         Mikal Bridges
34    Karl-Anthony Towns
35       Jaden McDaniels
36       Anthony Edwards
37           Mike Conley
38           Rudy Gobert
39         Julius Randle
40    Brandin Podziemski
41           Moses Moody
42      Jimmy Butler III
43        Draymond Green
44         Stephen Curry
45           Bruce Brown
46          Kelly Olynyk
47         Jose Alvarado
48            Yves Missi
49        Jordan Hawkins
50         Collin Sexton
51         Cody Williams
52        Isaiah Collier
53       Kyle Filipowski
54        Walker Kessler
55       Christian Braun
56    Michael Porter Jr.
57          Nikola Jokić
58          Jamal Murray
59          Aaron Gordon
Name: PLAYER, dtype: object

Evan Mobley: 9 points

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [ ]:

# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

# results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != 100.00]
# df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
#     .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
#     .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))

# df_merged = df_merged[df_merged["Player"] != 'Tyrese Haliburton']


# print(df_merged.columns)


# df_merged['middlebet_PTS+REB'] = 0000

# df_merged['PTS+REB'] = df_merged[['middlebet_PTS', 'middlebet_REB']].sum(axis=1)
# df_merged['confidence_level_PTS+REB']=  round(df_merged[['confidence_level_PTS','confidence_level_REB']].sum(axis=1)/2,2)
# df_merged = df_merged.rename(columns={'FGA': 'PTS'})
# display(df_merged)
# display(df_merged[['Player','confidence_level_PTS+REB']])


from parlay_picker import create_parlays, create_parlays_high

num_groups = 10  # Number of parlays you want to generate
players_per_group = 9  # Number of players in each parlay
min_confidence = 70

parlays_df, group_confidence_scores = create_parlays_high(df_merged, num_groups, players_per_group,min_confidence, 70)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")