In [1]:
from prediction import prediction

players_teams = {
    "Donovan Mitchell": "CLE",
    "Sam Merrill": "CLE",
    "Darius Garland": "CLE",
    "Evan Mobley": "CLE",
    "Jarrett Allen": "CLE",
    "Tim Hardaway Jr.": "DET",
    "Ausar Thompson": "DET",
    "Dennis Schroder": "DET",
    "Tobias Harris": "DET",
    "Jalen Duren": "DET",
    "Kris Dunn": "LAC",
    "Norman Powell": "LAC",
    "James Harden": "LAC",
    "Kawhi Leonard": "LAC",
    "Ivica Zubac": "LAC",
    "Keon Johnson": "BKN",
    "Ziaire Williams": "BKN",
    "D'Angelo Russell": "BKN",
    "Cameron Johnson": "BKN",
    "Nic Claxton": "BKN",
    "Josh Green": "CHA",
    "DaQuan Jeffries": "CHA",
    "KJ Simpson": "CHA",
    "Miles Bridges": "CHA",
    "Mark Williams": "CHA",
    "Ja'Kobe Walter": "TOR",
    "Jamison Battle": "TOR",
    "Immanuel Quickley": "TOR",
    "Scottie Barnes": "TOR",
    "Jakob Poeltl": "TOR",
    "Mikal Bridges": "NYK",
    "Josh Hart": "NYK",
    "Tyler Kolek": "NYK",
    "OG Anunoby": "NYK",
    "Karl-Anthony Towns": "NYK",
    "Devin Booker": "MIL",
    "Ryan Dunn": "MIL",
    "Collin Gillespie": "MIL",
    "Kevin Durant": "MIL",
    "Nick Richards": "MIL",
    "Anthony Edwards": "MIN",
    "Jaden McDaniels": "MIN",
    "Mike Conley": "MIN",
    "Julius Randle": "MIN",
    "Rudy Gobert": "MIN",
    "Brandin Podziemski": "GSW",
    "Moses Moody": "GSW",
    "Stephen Curry": "GSW",
    "Jimmy Butler III": "GSW",
    "Draymond Green": "GSW",
    "Jordan Hawkins": "NOP",
    "Bruce Brown": "NOP",
    "Jose Alvarado": "NOP",
    "Kelly Olynyk": "NOP",
    "Yves Missi": "NOP",
    "Collin Sexton": "UTA",
    "Cody Williams": "UTA",
    "Isaiah Collier": "UTA",
    "Kyle Filipowski": "UTA",
    "Walker Kessler": "UTA",
    "Christian Braun": "DEN",
    "Michael Porter Jr.": "DEN",
    "Jamal Murray": "DEN",
    "Aaron Gordon": "DEN",
    "Nikola Jokic": "DEN"
}









# remember to run mover
# remember to check schedule csv
import pandas as pd
date_list = ["2023-24","2024-25"]
stats_path = {
    'usage_path':'D:/nba_usage_csv_historic/usage_csv_{date}/{date}_content.csv',
    'catch_shoot':"D:/nba_tracking_data_csv/nba_csv_{date}/catch_shoot_content.csv",
    'drives':"D:/nba_tracking_data_csv/nba_csv_{date}/drives_content.csv",
    'elbow_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/elbow_touch_content.csv",
    'paint_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/paint_touch_content.csv",
    'passing':"D:/nba_tracking_data_csv/nba_csv_{date}/passing_content.csv",
    'pullup':"D:/nba_tracking_data_csv/nba_csv_{date}/pullup_content.csv",
    'shooting_efficiency':"D:/nba_tracking_data_csv/nba_csv_{date}/shooting_efficiency_content.csv",
    'touches':"D:/nba_tracking_data_csv/nba_csv_{date}/touches_content.csv",
    'tracking_post_ups_content':"D:/nba_tracking_data_csv/nba_csv_{date}/tracking_post_ups_content.csv"
}
schedule_base_path = "D:/nba_scheduled_csv/schedule_csv_2025/{schedule_team}_schedule_content.csv"
player_base_path = "D:/nba_player_csv_historic/season_{date}/all_quarters/{player}_content.csv"
defense_base_path = "D:/nba_defense_history_csv/defense_csv_{date}/all_quarter_defense_content.csv"

results_reb = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'REB','REB')
results_ast = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'AST','AST')
results_pts = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'PTS','PTS')
results_3pm = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'3PM','3PM')
results_pts = results_pts.rename(columns={'FGA': 'PTS'})



# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

Player data missing for KJ Simpson on 2023-24, skipping.
Skipping merge for KJ Simpson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ja'Kobe Walter on 2023-24, skipping.
Skipping merge for Ja'Kobe Walter on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ryan Dunn on 2023-24, skipping.
Skipping merge for Ryan Dunn on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yves Missi on 2023-24, skipping.
Skipping merge for Yves Missi on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cody Williams on 2023-24, skipping.
Skipping merge for Cody Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Collier on 2023-24, skipping.
Skipping merge for Isaiah Collier on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kyle Filipowski on 2023-24, skipping.
Skipping merge for Kyle Filipowski on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for KJ Simpson on 2023-24, skipping.
Skipping merge for KJ Simpson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ja'Kobe Walter on 2023-24, skipping.
Skipping merge for Ja'Kobe Walter on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ryan Dunn on 2023-24, skipping.
Skipping merge for Ryan Dunn on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yves Missi on 2023-24, skipping.
Skipping merge for Yves Missi on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cody Williams on 2023-24, skipping.
Skipping merge for Cody Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Collier on 2023-24, skipping.
Skipping merge for Isaiah Collier on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kyle Filipowski on 2023-24, skipping.
Skipping merge for Kyle Filipowski on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for KJ Simpson on 2023-24, skipping.
Skipping merge for KJ Simpson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ja'Kobe Walter on 2023-24, skipping.
Skipping merge for Ja'Kobe Walter on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ryan Dunn on 2023-24, skipping.
Skipping merge for Ryan Dunn on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yves Missi on 2023-24, skipping.
Skipping merge for Yves Missi on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cody Williams on 2023-24, skipping.
Skipping merge for Cody Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Collier on 2023-24, skipping.
Skipping merge for Isaiah Collier on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kyle Filipowski on 2023-24, skipping.
Skipping merge for Kyle Filipowski on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for KJ Simpson on 2023-24, skipping.
Skipping merge for KJ Simpson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ja'Kobe Walter on 2023-24, skipping.
Skipping merge for Ja'Kobe Walter on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ryan Dunn on 2023-24, skipping.
Skipping merge for Ryan Dunn on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yves Missi on 2023-24, skipping.
Skipping merge for Yves Missi on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cody Williams on 2023-24, skipping.
Skipping merge for Cody Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Collier on 2023-24, skipping.
Skipping merge for Isaiah Collier on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kyle Filipowski on 2023-24, skipping.
Skipping merge for Kyle Filipowski on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.634e-02, tolerance: 5.613e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.713e-01, tolerance: 8.972e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.121e-01, tolerance: 7.981e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.427e-01, tolerance: 3.310e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.200e-02, tolerance: 1.080e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.104e-02, tolerance: 1.150e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.644e-01, tolerance: 1.050e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.315e-02, tolerance: 6.275e-03
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.485e-01, tolerance: 7.148e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.872e-02, tolerance: 5.659e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.657e-01, tolerance: 9.037e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.339e-01, tolerance: 4.156e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.204e-02, tolerance: 5.691e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.177e+00, tolerance: 4.175e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.676e-01, tolerance: 4.056e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.139e+00, tolerance: 3.667e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.463e-01, tolerance: 6.084e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.944e-02, tolerance: 4.217e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.802e+00, tolerance: 4.619e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.612e-01, tolerance: 5.502e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.307e-02, tolerance: 1.187e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.683e-01, tolerance: 1.548e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.407e+00, tolerance: 1.079e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:212: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:212: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:212: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:212: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:212: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:212: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:212: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:212: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\linear\prediction.py:214: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

Player data missing for KJ Simpson on 2023-24, skipping.
Skipping merge for KJ Simpson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ja'Kobe Walter on 2023-24, skipping.
Skipping merge for Ja'Kobe Walter on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ryan Dunn on 2023-24, skipping.
Skipping merge for Ryan Dunn on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yves Missi on 2023-24, skipping.
Skipping merge for Yves Missi on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cody Williams on 2023-24, skipping.
Skipping merge for Cody Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Collier on 2023-24, skipping.
Skipping merge for Isaiah Collier on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kyle Filipowski on 2023-24, skipping.
Skipping merge for Kyle Filipowski on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for KJ Simpson on 2023-24, skipping.
Skipping merge for KJ Simpson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ja'Kobe Walter on 2023-24, skipping.
Skipping merge for Ja'Kobe Walter on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ryan Dunn on 2023-24, skipping.
Skipping merge for Ryan Dunn on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yves Missi on 2023-24, skipping.
Skipping merge for Yves Missi on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cody Williams on 2023-24, skipping.
Skipping merge for Cody Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Collier on 2023-24, skipping.
Skipping merge for Isaiah Collier on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kyle Filipowski on 2023-24, skipping.
Skipping merge for Kyle Filipowski on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for KJ Simpson on 2023-24, skipping.
Skipping merge for KJ Simpson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ja'Kobe Walter on 2023-24, skipping.
Skipping merge for Ja'Kobe Walter on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ryan Dunn on 2023-24, skipping.
Skipping merge for Ryan Dunn on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yves Missi on 2023-24, skipping.
Skipping merge for Yves Missi on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cody Williams on 2023-24, skipping.
Skipping merge for Cody Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Collier on 2023-24, skipping.
Skipping merge for Isaiah Collier on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kyle Filipowski on 2023-24, skipping.
Skipping merge for Kyle Filipowski on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for KJ Simpson on 2023-24, skipping.
Skipping merge for KJ Simpson on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ja'Kobe Walter on 2023-24, skipping.
Skipping merge for Ja'Kobe Walter on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jamison Battle on 2023-24, skipping.
Skipping merge for Jamison Battle on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Tyler Kolek on 2023-24, skipping.
Skipping merge for Tyler Kolek on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Ryan Dunn on 2023-24, skipping.
Skipping merge for Ryan Dunn on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Yves Missi on 2023-24, skipping.
Skipping merge for Yves Missi on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Cody Williams on 2023-24, skipping.
Skipping merge for Cody Williams on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Isaiah Collier on 2023-24, skipping.
Skipping merge for Isaiah Collier on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Kyle Filipowski on 2023-24, skipping.
Skipping merge for Kyle Filipowski on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(

In [2]:

display(results_reb)
display(results_ast)
display(results_pts)
display(results_3pm)

results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != 100.00]
df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
    .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
    .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))


players_to_remove = [
    # "Jordan Poole",
    # "Bub Carrington",
    # "A.J. Johnson",
    # "Justin Champagnie",
    # "Alex Sarr",
    # "Quentin Grimes",
    # "Justin Edwards",
    # "Jared Butler",
    # "Ricky Council IV",
    # "Guerschon Yabusele",
    # "Austin Reaves",
    # "LeBron James",
    # "Luka Doncic",
    # "Dorian Finney-Smith",
    # "Jaxson Hayes",
    # "Andrew Nembhard",
    # "Aaron Nesmith",
    # "Tyrese Haliburton",
    # "Pascal Siakam",
    # "Myles Turner",
    # "Kris Dunn",
    # "Norman Powell",
    # "James Harden",
    # "Kawhi Leonard",
    # "Ivica Zubac",
    # "Mikal Bridges",
    # "Josh Hart",
    # "Cameron Payne",
    # "OG Anunoby",
    # "Karl-Anthony Towns",
    # "RJ Barrett",
    # "Ochai Agbaji",
    # "Jamal Shead",
    # "Scottie Barnes",
    # "Orlando Robinson",
    # "Keon Johnson",
    # "Ziaire Williams",
    # "D'Angelo Russell",
    # "Jalen Wilson",
    # "Nic Claxton",
    # "Gary Trent Jr.",
    # "Taurean Prince",
    # "Ryan Rollins",
    # "Kyle Kuzma",
    # "Brook Lopez",
    # "Christian Braun",
    # "Michael Porter Jr.",
    # "Jamal Murray",
    # "Aaron Gordon",
    # "Nikola Jokic",
    # "Jrue Holiday",
    # "Jaylen Brown",
    # "Derrick White",
    # "Jayson Tatum",
    # "Kristaps Porzingis"
    # "Devin Booker",
    # "Ryan Dunn",
    # "Collin Gillespie",
    # "Kevin Durant",
    # "Nick Richards"
    ]

# players_to_remove = ['Tyrese Haliburton', 'Player1', 'Player2', 'Player3']

df_merged = df_merged[~df_merged["Player"].isin(players_to_remove)]



from parlay_picker import create_parlays

num_groups = 10  # Number of parlays you want to generate
players_per_group = 4 # Number of players in each parlay
min_confidence = 60
threepm_confidence = 50

parlays_df, group_confidence_scores = create_parlays(df_merged, num_groups, players_per_group,min_confidence,threepm_confidence)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")

                Player team           REB  confidence_level_REB                          recentgames_REB
0     Donovan Mitchell  CLE     1 - 2 - 2                 52.62           [8, 3, 4, 5, 4, 6, 5, 3, 7, 7]
1          Sam Merrill  CLE     0 - 3 - 5                 26.70           [2, 2, 5, 7, 1, 1, 1, 1, 6, 2]
2       Darius Garland  CLE     1 - 3 - 4                 53.69           [4, 5, 7, 5, 5, 6, 2, 4, 5, 1]
3          Evan Mobley  CLE   7 - 11 - 14                 72.33    [12, 11, 12, 10, 3, 11, 9, 7, 10, 13]
4        Jarrett Allen  CLE   6 - 12 - 17                 52.18        [15, 8, 6, 6, 5, 8, 12, 6, 13, 6]
5     Tim Hardaway Jr.  DET     1 - 3 - 4                 33.39           [2, 1, 2, 3, 1, 3, 4, 7, 2, 4]
6       Ausar Thompson  DET     4 - 7 - 9                 65.45           [6, 1, 3, 6, 4, 4, 4, 5, 6, 5]
7      Dennis Schroder  DET     0 - 3 - 5                 22.52           [2, 1, 3, 1, 0, 3, 2, 1, 4, 0]
8        Tobias Harris  DET     0 - 1 - 1                 59.68          [8, 3, 6, 5, 6, 7, 6, 8, 9, 12]
9          Jalen Duren  DET   7 - 13 - 18                 60.92     [4, 12, 9, 11, 7, 5, 14, 13, 12, 13]
10           Kris Dunn  LAC     0 - 1 - 1                 42.89           [3, 3, 3, 1, 3, 2, 3, 2, 2, 4]
11       Norman Powell  LAC     1 - 3 - 4                 37.12           [1, 4, 3, 1, 1, 1, 3, 5, 1, 4]
12        James Harden  LAC     2 - 5 - 7                 54.80          [6, 5, 4, 4, 10, 8, 8, 4, 9, 3]
13       Kawhi Leonard  LAC     1 - 3 - 4                 66.10        [10, 10, 10, 7, 6, 6, 8, 4, 7, 4]
14         Ivica Zubac  LAC    6 - 9 - 11                 71.03  [10, 11, 10, 20, 14, 6, 14, 11, 14, 14]
15        Keon Johnson  BKN     0 - 1 - 1                 50.60           [2, 4, 4, 3, 3, 8, 6, 2, 7, 3]
16     Ziaire Williams  BKN     1 - 3 - 4                 45.13           [6, 2, 5, 4, 5, 4, 6, 9, 3, 1]
17    D'Angelo Russell  BKN     0 - 3 - 5                 25.26           [5, 1, 5, 3, 3, 3, 6, 0, 1, 0]
18     Cameron Johnson  BKN     1 - 2 - 2                 55.37          [2, 9, 2, 4, 10, 6, 5, 7, 6, 3]
19         Nic Claxton  BKN     3 - 5 - 6                 63.09       [11, 7, 10, 14, 9, 6, 14, 4, 6, 6]
20          Josh Green  CHA     0 - 4 - 7                 17.69           [0, 1, 0, 2, 1, 1, 3, 6, 4, 3]
21     DaQuan Jeffries  CHA     0 - 0 - 0                 13.26           [1, 3, 0, 4, 5, 5, 1, 0, 3, 0]
22          KJ Simpson  CHA     0 - 2 - 3                 16.13           [1, 3, 1, 4, 6, 9, 4, 3, 0, 4]
23       Miles Bridges  CHA     3 - 6 - 8                 60.54       [6, 13, 3, 10, 4, 7, 11, 5, 12, 8]
24       Mark Williams  CHA     4 - 7 - 9                 64.91    [13, 5, 14, 5, 15, 10, 14, 10, 8, 13]
25      Ja'Kobe Walter  TOR     1 - 2 - 2                 52.53           [2, 3, 5, 3, 4, 4, 8, 3, 4, 4]
26      Jamison Battle  TOR    0 - 6 - 11                  2.57          [10, 3, 1, 2, 3, 2, 6, 8, 3, 8]
27   Immanuel Quickley  TOR     2 - 5 - 7                 50.01           [4, 4, 7, 5, 6, 5, 4, 2, 5, 2]
28      Scottie Barnes  TOR   5 - 10 - 14                 56.99      [7, 10, 6, 10, 4, 6, 10, 13, 2, 12]
29        Jakob Poeltl  TOR    4 - 8 - 11                 59.57         [11, 8, 8, 5, 5, 7, 11, 4, 5, 2]
30       Mikal Bridges  NYK     0 - 2 - 3                 37.30           [4, 1, 6, 4, 5, 1, 6, 4, 3, 4]
31           Josh Hart  NYK   5 - 10 - 14                 56.64      [5, 12, 12, 4, 7, 13, 7, 11, 6, 20]
32         Tyler Kolek  NYK     1 - 2 - 5                 35.83           [1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
33          OG Anunoby  NYK     1 - 3 - 4                 40.90           [5, 5, 2, 6, 5, 1, 9, 7, 7, 8]
34  Karl-Anthony Towns  NYK   9 - 14 - 18                 65.93     [14, 12, 11, 10, 9, 7, 12, 7, 9, 10]
35        Devin Booker  MIL     2 - 5 - 7                 49.33           [7, 2, 4, 4, 6, 4, 3, 9, 3, 6]
36           Ryan Dunn  MIL     0 - 3 - 5                 20.97           [5, 9, 5, 6, 3, 5, 2, 0, 1, 3]
37    Collin Gillespie  MIL     0 - 1 - 1                  3.61           [1, 2, 5, 2, 7, 1, 2, 4, 0, 0]
38        Kevin Durant  MIL     1 - 3 - 4                 53.33           [1, 6, 4, 3, 9, 4, 7, 5, 9, 9]
39       Nick Richards  MIL    4 - 8 - 11                 56.45         [4, 9, 4, 6, 12, 9, 5, 7, 8, 12]
40     Anthony Edwards  MIN     2 - 6 - 9                 43.07          [2, 3, 6, 3, 2, 4, 4, 3, 13, 3]
41     Jaden McDaniels  MIN     2 - 6 - 9                 49.16         [1, 5, 0, 7, 12, 8, 8, 4, 6, 10]
42         Mike Conley  MIN     0 - 0 - 0                 22.79           [4, 1, 2, 3, 1, 1, 5, 2, 7, 1]
43       Julius Randle  MIN     3 - 6 - 8                 56.78         [6, 6, 3, 6, 3, 7, 4, 7, 10, 10]
44         Rudy Gobert  MIN     4 - 7 - 9                 67.96      [16, 11, 9, 7, 6, 12, 10, 8, 14, 8]
45  Brandin Podziemski  GSW     2 - 6 - 9                 43.78          [3, 8, 3, 7, 0, 5, 11, 6, 4, 5]
46         Moses Moody  GSW     1 - 3 - 4                 39.31           [1, 4, 1, 7, 2, 1, 4, 2, 7, 5]
47       Stephen Curry  GSW     2 - 5 - 7                 53.41           [2, 4, 7, 2, 2, 3, 4, 7, 3, 5]
48    Jimmy Butler III  GSW     2 - 4 - 5                 53.06         [6, 4, 11, 8, 8, 6, 5, 10, 9, 2]
49      Draymond Green  GSW     3 - 6 - 8                 61.48          [5, 6, 7, 10, 6, 4, 4, 4, 9, 7]
50      Jordan Hawkins  NOP     0 - 2 - 3                 46.06           [5, 3, 5, 6, 2, 1, 0, 3, 5, 2]
51         Bruce Brown  NOP     0 - 2 - 3                 32.93           [1, 2, 7, 1, 6, 0, 5, 1, 2, 5]
52       Jose Alvarado  NOP     0 - 2 - 3                 18.83           [3, 4, 1, 3, 1, 0, 2, 2, 0, 4]
53        Kelly Olynyk  NOP     2 - 6 - 9                 41.14          [11, 5, 3, 4, 3, 6, 4, 6, 5, 4]
54          Yves Missi  NOP     2 - 4 - 5                 58.80         [9, 10, 7, 10, 8, 9, 6, 4, 2, 7]
55       Collin Sexton  UTA     0 - 1 - 1                 32.83           [1, 3, 0, 2, 3, 4, 1, 8, 3, 2]
56       Cody Williams  UTA     0 - 1 - 1                 18.53           [2, 1, 1, 1, 1, 3, 1, 4, 6, 4]
57      Isaiah Collier  UTA     1 - 2 - 2                 55.99           [1, 3, 7, 4, 3, 6, 6, 5, 4, 1]
58     Kyle Filipowski  UTA     1 - 3 - 4                 42.13         [7, 2, 13, 4, 4, 5, 4, 11, 8, 5]
59      Walker Kessler  UTA   7 - 12 - 16                 62.86    [9, 9, 13, 11, 5, 12, 19, 14, 10, 25]
60     Christian Braun  DEN     2 - 4 - 5                 52.94          [10, 5, 4, 5, 4, 3, 5, 4, 5, 3]
61  Michael Porter Jr.  DEN     3 - 6 - 8                 60.32        [10, 6, 9, 5, 4, 10, 11, 4, 9, 6]
62        Jamal Murray  DEN     1 - 3 - 4                 56.42           [4, 5, 4, 4, 6, 4, 5, 4, 2, 1]
63        Aaron Gordon  DEN     1 - 4 - 6                 44.50          [2, 4, 3, 11, 6, 7, 2, 3, 5, 5]
64        Nikola Jokic  DEN  10 - 15 - 19                 69.23   [10, 13, 7, 8, 18, 13, 21, 15, 14, 17]

                Player team          AST  confidence_level_AST                     recentgames_AST
0     Donovan Mitchell  CLE    2 - 6 - 9                 48.55    [14, 4, 3, 4, 11, 5, 6, 1, 5, 5]
1          Sam Merrill  CLE    0 - 1 - 2                 18.16      [2, 3, 5, 0, 4, 0, 2, 2, 0, 1]
2       Darius Garland  CLE    3 - 5 - 6                 65.34      [9, 8, 4, 6, 8, 4, 9, 8, 5, 2]
3          Evan Mobley  CLE    1 - 4 - 6                 41.14      [4, 1, 5, 2, 1, 3, 6, 2, 4, 3]
4        Jarrett Allen  CLE    0 - 2 - 3                 20.67      [0, 2, 4, 1, 2, 1, 2, 3, 1, 3]
5     Tim Hardaway Jr.  DET    0 - 1 - 1                 36.97      [4, 0, 1, 0, 0, 1, 1, 2, 2, 1]
6       Ausar Thompson  DET    0 - 2 - 3                 32.34      [3, 1, 3, 1, 3, 1, 1, 1, 2, 0]
7      Dennis Schroder  DET    2 - 5 - 7                 59.71     [6, 5, 4, 3, 5, 11, 3, 4, 4, 4]
8        Tobias Harris  DET    0 - 1 - 1                 34.55      [4, 4, 3, 2, 0, 0, 3, 1, 2, 2]
9          Jalen Duren  DET    0 - 2 - 3                 32.46      [7, 2, 3, 1, 6, 2, 0, 0, 2, 2]
10           Kris Dunn  LAC    0 - 1 - 1                 43.20      [6, 1, 1, 0, 1, 3, 5, 4, 3, 6]
11       Norman Powell  LAC    0 - 1 - 1                 41.09      [2, 1, 3, 1, 0, 1, 1, 2, 3, 3]
12        James Harden  LAC   5 - 9 - 12                 64.91   [6, 8, 9, 9, 7, 7, 11, 17, 11, 7]
13       Kawhi Leonard  LAC    1 - 2 - 2                 54.84      [7, 3, 4, 4, 5, 2, 3, 2, 6, 3]
14         Ivica Zubac  LAC    0 - 3 - 5                 26.39      [2, 3, 1, 1, 8, 2, 1, 5, 2, 3]
15        Keon Johnson  BKN    0 - 2 - 3                 41.24      [5, 3, 1, 2, 1, 5, 2, 2, 2, 3]
16     Ziaire Williams  BKN    0 - 1 - 1                 36.96      [1, 1, 1, 0, 2, 1, 3, 2, 1, 1]
17    D'Angelo Russell  BKN   3 - 7 - 10                 53.90      [2, 6, 7, 8, 4, 7, 7, 4, 4, 5]
18     Cameron Johnson  BKN    0 - 2 - 3                 45.51      [8, 5, 4, 7, 6, 1, 5, 5, 4, 4]
19         Nic Claxton  BKN    0 - 1 - 1                 25.11      [1, 3, 4, 0, 2, 2, 5, 4, 1, 2]
20          Josh Green  CHA    0 - 1 - 1                 23.00      [0, 2, 1, 3, 2, 3, 0, 2, 5, 1]
21     DaQuan Jeffries  CHA    0 - 0 - 0                  0.29      [2, 0, 1, 0, 1, 3, 1, 1, 1, 1]
22          KJ Simpson  CHA    0 - 2 - 3                  6.84      [0, 2, 8, 5, 2, 4, 6, 3, 3, 1]
23       Miles Bridges  CHA    1 - 3 - 4                 50.65      [4, 4, 4, 4, 3, 8, 5, 5, 5, 2]
24       Mark Williams  CHA    0 - 2 - 3                 36.30      [4, 1, 4, 5, 7, 3, 2, 2, 2, 1]
25      Ja'Kobe Walter  TOR    0 - 3 - 6                  1.15      [6, 4, 2, 0, 1, 1, 1, 0, 0, 0]
26      Jamison Battle  TOR    0 - 0 - 0                  8.63      [0, 0, 1, 2, 1, 1, 0, 1, 0, 0]
27   Immanuel Quickley  TOR    3 - 6 - 8                 63.07      [7, 8, 7, 5, 6, 5, 4, 4, 5, 6]
28      Scottie Barnes  TOR    3 - 6 - 8                 66.30      [5, 8, 6, 6, 3, 6, 3, 2, 4, 6]
29        Jakob Poeltl  TOR    0 - 2 - 3                 44.49      [1, 2, 3, 2, 5, 2, 3, 3, 2, 2]
30       Mikal Bridges  NYK    2 - 4 - 5                 51.91      [9, 1, 4, 6, 7, 3, 3, 4, 8, 5]
31           Josh Hart  NYK    2 - 5 - 7                 52.50    [6, 11, 2, 6, 7, 11, 7, 9, 3, 6]
32         Tyler Kolek  NYK    0 - 1 - 2                 17.45      [7, 9, 8, 0, 1, 1, 0, 0, 1, 3]
33          OG Anunoby  NYK    0 - 2 - 3                 26.90      [3, 1, 3, 2, 1, 2, 2, 3, 8, 1]
34  Karl-Anthony Towns  NYK    0 - 3 - 5                 15.96     [4, 11, 1, 3, 2, 3, 3, 4, 3, 2]
35        Devin Booker  MIL    4 - 6 - 7                 69.00  [10, 10, 7, 6, 11, 13, 4, 6, 6, 7]
36           Ryan Dunn  MIL    1 - 1 - 3                  0.00      [0, 1, 0, 0, 1, 3, 0, 0, 0, 1]
37    Collin Gillespie  MIL    0 - 2 - 3                  2.67      [0, 4, 7, 2, 3, 2, 2, 5, 0, 0]
38        Kevin Durant  MIL    1 - 3 - 4                 46.28      [2, 8, 8, 3, 2, 6, 0, 5, 8, 5]
39       Nick Richards  MIL    0 - 1 - 2                  8.71      [0, 2, 1, 0, 2, 0, 0, 0, 2, 2]
40     Anthony Edwards  MIN    2 - 5 - 7                 57.96      [4, 5, 4, 5, 2, 5, 6, 3, 6, 6]
41     Jaden McDaniels  MIN    0 - 2 - 3                 36.34      [1, 0, 4, 4, 2, 2, 1, 7, 4, 4]
42         Mike Conley  MIN    1 - 3 - 4                 54.24      [5, 6, 2, 5, 3, 5, 5, 2, 6, 1]
43       Julius Randle  MIN    1 - 4 - 6                 48.33     [2, 5, 3, 4, 4, 5, 3, 10, 9, 9]
44         Rudy Gobert  MIN    0 - 1 - 1                 26.07      [3, 3, 1, 1, 0, 1, 3, 2, 4, 1]
45  Brandin Podziemski  GSW    1 - 4 - 6                 40.91      [4, 4, 1, 1, 0, 4, 2, 2, 7, 2]
46         Moses Moody  GSW    0 - 0 - 0                 32.35      [2, 5, 2, 3, 0, 1, 6, 0, 3, 2]
47       Stephen Curry  GSW    2 - 5 - 7                 51.18    [1, 7, 5, 5, 3, 4, 4, 9, 10, 13]
48    Jimmy Butler III  GSW    3 - 5 - 6                 61.77   [2, 8, 12, 10, 6, 7, 7, 10, 5, 6]
49      Draymond Green  GSW    4 - 6 - 7                 67.11     [3, 6, 5, 4, 5, 3, 4, 7, 7, 10]
50      Jordan Hawkins  NOP    0 - 1 - 1                 14.84      [1, 2, 3, 1, 1, 2, 1, 1, 0, 1]
51         Bruce Brown  NOP    0 - 1 - 1                 12.44      [2, 1, 6, 0, 6, 2, 5, 2, 2, 1]
52       Jose Alvarado  NOP    2 - 4 - 5                 55.28     [6, 8, 2, 6, 4, 5, 4, 4, 11, 7]
53        Kelly Olynyk  NOP    0 - 2 - 3                 45.37      [7, 8, 4, 0, 3, 7, 4, 6, 2, 2]
54          Yves Missi  NOP    0 - 0 - 0                  7.20      [2, 2, 2, 0, 1, 0, 4, 1, 1, 0]
55       Collin Sexton  UTA    1 - 3 - 4                 39.39     [5, 5, 2, 3, 5, 4, 2, 7, 13, 3]
56       Cody Williams  UTA    0 - 0 - 0                  6.47      [1, 1, 0, 0, 1, 2, 1, 0, 0, 1]
57      Isaiah Collier  UTA    2 - 4 - 5                 57.56      [5, 4, 6, 5, 6, 8, 6, 8, 6, 4]
58     Kyle Filipowski  UTA    0 - 1 - 1                 21.33      [4, 0, 1, 0, 2, 1, 3, 3, 3, 0]
59      Walker Kessler  UTA    0 - 2 - 3                 17.04      [2, 1, 2, 6, 2, 1, 0, 5, 1, 0]
60     Christian Braun  DEN    1 - 3 - 4                 43.30      [6, 3, 2, 2, 3, 4, 6, 0, 5, 2]
61  Michael Porter Jr.  DEN    0 - 2 - 3                 37.74      [4, 2, 2, 3, 1, 5, 1, 2, 2, 2]
62        Jamal Murray  DEN    5 - 7 - 8                 72.01      [6, 7, 7, 2, 7, 5, 8, 6, 4, 8]
63        Aaron Gordon  DEN    0 - 4 - 7                 15.51      [1, 8, 4, 0, 3, 4, 0, 1, 2, 2]
64        Nikola Jokic  DEN  5 - 10 - 14                 58.33   [10, 9, 5, 4, 8, 9, 22, 6, 9, 15]

                Player team           PTS  confidence_level_PTS                           recentgames_PTS
0     Donovan Mitchell  CLE  12 - 20 - 27                 64.20   [25, 16, 7, 26, 18, 23, 15, 24, 26, 28]
1          Sam Merrill  CLE    2 - 7 - 11                 33.89         [13, 14, 6, 4, 0, 3, 5, 14, 6, 9]
2       Darius Garland  CLE  16 - 23 - 29                 69.73  [10, 27, 12, 18, 17, 19, 20, 30, 13, 20]
3          Evan Mobley  CLE  14 - 20 - 25                 71.49  [21, 11, 16, 31, 17, 22, 21, 13, 19, 16]
4        Jarrett Allen  CLE   5 - 10 - 14                 54.06    [29, 14, 18, 6, 10, 8, 20, 16, 23, 11]
5     Tim Hardaway Jr.  DET   7 - 14 - 20                 56.12      [12, 0, 10, 8, 11, 10, 11, 13, 6, 7]
6       Ausar Thompson  DET     3 - 5 - 6                 61.99         [14, 5, 8, 14, 9, 8, 10, 8, 5, 6]
7      Dennis Schroder  DET   8 - 14 - 19                 58.10    [7, 16, 11, 8, 12, 17, 11, 11, 12, 11]
8        Tobias Harris  DET     3 - 5 - 6                 74.77    [15, 14, 9, 13, 9, 18, 14, 12, 20, 15]
9          Jalen Duren  DET    5 - 9 - 12                 65.59    [14, 22, 14, 15, 9, 8, 18, 15, 18, 13]
10           Kris Dunn  LAC     1 - 4 - 6                 31.48          [9, 7, 11, 2, 0, 4, 11, 4, 2, 8]
11       Norman Powell  LAC   8 - 15 - 21                 57.17     [19, 9, 14, 11, 7, 4, 41, 18, 26, 22]
12        James Harden  LAC  15 - 22 - 28                 69.02  [29, 17, 30, 22, 31, 25, 24, 25, 29, 27]
13       Kawhi Leonard  LAC  15 - 22 - 28                 71.40  [27, 25, 23, 33, 23, 25, 29, 17, 20, 21]
14         Ivica Zubac  LAC   9 - 14 - 18                 65.57  [18, 15, 17, 28, 17, 18, 26, 19, 22, 16]
15        Keon Johnson  BKN     2 - 6 - 9                 42.59       [8, 8, 17, 6, 13, 22, 21, 2, 1, 18]
16     Ziaire Williams  BKN     3 - 6 - 8                 58.91    [13, 6, 22, 15, 14, 11, 14, 7, 19, 10]
17    D'Angelo Russell  BKN   9 - 22 - 34                 43.82       [5, 22, 18, 11, 4, 8, 28, 7, 12, 3]
18     Cameron Johnson  BKN   9 - 13 - 16                 76.70  [17, 20, 11, 28, 23, 16, 17, 18, 26, 17]
19         Nic Claxton  BKN    5 - 9 - 12                 57.27        [22, 19, 9, 6, 6, 7, 18, 9, 12, 8]
20          Josh Green  CHA    1 - 7 - 12                 18.10         [13, 12, 5, 2, 8, 20, 2, 3, 0, 3]
21     DaQuan Jeffries  CHA     0 - 3 - 5                 19.94       [7, 7, 11, 14, 19, 5, 13, 20, 8, 3]
22          KJ Simpson  CHA     1 - 4 - 6                 44.88      [7, 2, 10, 11, 16, 9, 10, 12, 15, 9]
23       Miles Bridges  CHA   7 - 13 - 18                 56.45   [11, 17, 20, 15, 7, 21, 31, 35, 26, 46]
24       Mark Williams  CHA     3 - 6 - 8                 57.74    [8, 14, 19, 4, 18, 14, 14, 24, 12, 12]
25      Ja'Kobe Walter  TOR   5 - 10 - 14                 57.74        [11, 10, 14, 17, 7, 7, 3, 6, 6, 8]
26      Jamison Battle  TOR     0 - 4 - 7                 24.81       [8, 11, 5, 14, 14, 9, 7, 11, 5, 11]
27   Immanuel Quickley  TOR  12 - 19 - 25                 63.77  [21, 21, 15, 20, 15, 34, 15, 24, 23, 18]
28      Scottie Barnes  TOR  14 - 20 - 25                 70.29  [15, 13, 22, 29, 16, 16, 20, 14, 18, 22]
29        Jakob Poeltl  TOR   8 - 13 - 17                 63.40    [21, 18, 19, 9, 21, 17, 16, 10, 10, 5]
30       Mikal Bridges  NYK   6 - 11 - 15                 54.68  [17, 21, 27, 16, 14, 28, 19, 33, 15, 22]
31           Josh Hart  NYK   4 - 11 - 17                 44.61      [7, 16, 9, 13, 2, 12, 0, 11, 18, 14]
32         Tyler Kolek  NYK     1 - 4 - 9                  7.47            [0, 2, 4, 0, 2, 2, 0, 0, 0, 3]
33          OG Anunoby  NYK   7 - 12 - 16                 60.73   [28, 35, 23, 25, 14, 9, 23, 23, 24, 11]
34  Karl-Anthony Towns  NYK  20 - 31 - 41                 65.10  [34, 26, 31, 24, 32, 23, 29, 21, 26, 23]
35        Devin Booker  MIL  15 - 23 - 30                 68.28  [14, 17, 41, 27, 19, 22, 19, 26, 24, 34]
36           Ryan Dunn  MIL    0 - 7 - 14                 18.90       [6, 10, 16, 17, 13, 16, 4, 0, 0, 5]
37    Collin Gillespie  MIL    1 - 9 - 16                 13.08           [5, 13, 4, 3, 3, 5, 2, 0, 3, 3]
38        Kevin Durant  MIL  25 - 36 - 46                 71.12  [30, 42, 26, 14, 21, 22, 19, 35, 21, 29]
39       Nick Richards  MIL     2 - 5 - 7                 55.02   [10, 18, 10, 11, 10, 14, 18, 16, 4, 19]
40     Anthony Edwards  MIN  24 - 38 - 51                 65.02  [17, 17, 29, 38, 41, 28, 29, 25, 13, 29]
41     Jaden McDaniels  MIN   7 - 13 - 18                 61.15    [6, 17, 5, 13, 20, 11, 16, 16, 13, 29]
42         Mike Conley  MIN     1 - 4 - 6                 47.82        [7, 0, 16, 9, 9, 8, 13, 15, 12, 3]
43       Julius Randle  MIN  14 - 23 - 31                 61.11   [9, 20, 17, 17, 11, 22, 25, 14, 13, 25]
44         Rudy Gobert  MIN     4 - 7 - 9                 64.97    [16, 15, 10, 3, 7, 12, 11, 16, 20, 12]
45  Brandin Podziemski  GSW   6 - 12 - 17                 51.23     [14, 19, 15, 17, 0, 19, 19, 5, 8, 10]
46         Moses Moody  GSW     2 - 5 - 7                 58.15      [7, 20, 4, 7, 9, 18, 17, 20, 12, 10]
47       Stephen Curry  GSW  15 - 25 - 34                 63.95  [17, 20, 28, 11, 24, 32, 40, 28, 21, 29]
48    Jimmy Butler III  GSW   7 - 13 - 18                 60.78   [11, 25, 16, 24, 23, 11, 6, 15, 26, 25]
49      Draymond Green  GSW   5 - 12 - 18                 46.34        [2, 5, 21, 3, 10, 9, 23, 4, 12, 7]
50      Jordan Hawkins  NOP   6 - 14 - 21                 46.38     [9, 25, 10, 13, 6, 0, 11, 11, 12, 13]
51         Bruce Brown  NOP     0 - 2 - 3                 31.49       [12, 14, 15, 2, 19, 0, 12, 5, 0, 4]
52       Jose Alvarado  NOP   5 - 11 - 16                 51.45       [9, 10, 9, 8, 3, 7, 12, 14, 11, 17]
53        Kelly Olynyk  NOP    4 - 9 - 13                 50.18     [14, 10, 10, 13, 9, 14, 12, 0, 8, 11]
54          Yves Missi  NOP     1 - 4 - 6                 45.17      [16, 5, 13, 12, 9, 10, 14, 10, 2, 8]
55       Collin Sexton  UTA  15 - 24 - 32                 63.05   [21, 15, 10, 30, 18, 22, 8, 22, 16, 17]
56       Cody Williams  UTA     2 - 5 - 7                 51.69            [4, 8, 3, 4, 2, 5, 2, 6, 5, 5]
57      Isaiah Collier  UTA     3 - 6 - 8                 60.94      [16, 21, 7, 5, 16, 8, 11, 16, 11, 8]
58     Kyle Filipowski  UTA     1 - 3 - 4                 55.28      [16, 13, 18, 4, 21, 8, 10, 18, 9, 6]
59      Walker Kessler  UTA   6 - 13 - 19                 50.59         [2, 7, 7, 8, 7, 7, 15, 9, 11, 18]
60     Christian Braun  DEN  11 - 18 - 24                 63.61    [19, 18, 11, 15, 10, 9, 22, 6, 14, 19]
61  Michael Porter Jr.  DEN  12 - 20 - 27                 63.40  [23, 16, 17, 17, 12, 21, 20, 13, 10, 17]
62        Jamal Murray  DEN  12 - 21 - 29                 57.82  [17, 28, 39, 10, 24, 26, 12, 34, 17, 19]
63        Aaron Gordon  DEN    3 - 9 - 14                 40.32     [7, 13, 23, 26, 38, 17, 5, 27, 9, 25]
64        Nikola Jokic  DEN  24 - 33 - 41                 73.17  [39, 40, 28, 34, 35, 24, 31, 22, 20, 23]

                Player team        3PM  confidence_level_3PM                 recentgames_3PM
0     Donovan Mitchell  CLE  0 - 1 - 1                 30.54  [4, 0, 0, 1, 2, 3, 1, 0, 4, 1]
1          Sam Merrill  CLE  0 - 2 - 3                 23.83  [3, 4, 2, 0, 0, 1, 1, 4, 1, 3]
2       Darius Garland  CLE  1 - 3 - 4                 50.58  [2, 1, 2, 2, 2, 2, 3, 3, 1, 3]
3          Evan Mobley  CLE  0 - 1 - 1                  4.03  [0, 0, 2, 4, 0, 3, 1, 2, 1, 0]
4        Jarrett Allen  CLE  0 - 0 - 0                100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
5     Tim Hardaway Jr.  DET  0 - 4 - 7                 17.35  [1, 0, 1, 2, 3, 2, 3, 3, 1, 0]
6       Ausar Thompson  DET  0 - 0 - 0                 45.39  [1, 0, 0, 0, 0, 1, 1, 0, 0, 0]
7      Dennis Schroder  DET  0 - 2 - 4                  0.00  [0, 1, 2, 0, 0, 4, 1, 2, 0, 0]
8        Tobias Harris  DET  0 - 0 - 0                 20.71  [3, 0, 1, 0, 0, 2, 2, 2, 1, 0]
9          Jalen Duren  DET  0 - 0 - 0                100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
10           Kris Dunn  LAC  0 - 1 - 2                 30.22  [1, 1, 3, 0, 0, 0, 1, 0, 0, 2]
11       Norman Powell  LAC  0 - 2 - 3                 46.04  [4, 1, 1, 1, 1, 0, 5, 1, 2, 4]
12        James Harden  LAC  1 - 2 - 2                 52.70  [6, 2, 5, 2, 4, 4, 3, 4, 3, 5]
13       Kawhi Leonard  LAC  0 - 1 - 1                 39.04  [2, 2, 1, 5, 3, 1, 4, 1, 1, 1]
14         Ivica Zubac  LAC  0 - 0 - 0                100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
15        Keon Johnson  BKN  0 - 0 - 0                 22.56  [0, 0, 3, 1, 3, 4, 5, 0, 0, 3]
16     Ziaire Williams  BKN  0 - 0 - 0                 31.86  [2, 2, 6, 3, 4, 1, 4, 1, 4, 2]
17    D'Angelo Russell  BKN  0 - 3 - 5                 31.97  [1, 3, 4, 1, 0, 2, 4, 1, 2, 1]
18     Cameron Johnson  BKN  0 - 1 - 1                 52.45  [1, 3, 1, 4, 2, 2, 3, 2, 3, 3]
19         Nic Claxton  BKN  0 - 0 - 0                  0.00  [0, 2, 0, 0, 0, 0, 0, 0, 0, 0]
20          Josh Green  CHA  0 - 1 - 2                 22.68  [3, 2, 1, 0, 0, 6, 0, 1, 0, 0]
21     DaQuan Jeffries  CHA  0 - 0 - 0                 44.12  [1, 1, 3, 3, 3, 1, 3, 4, 2, 1]
22          KJ Simpson  CHA  0 - 0 - 0                 14.94  [1, 0, 2, 1, 1, 0, 2, 2, 3, 0]
23       Miles Bridges  CHA  0 - 0 - 0                 38.84  [1, 0, 4, 2, 1, 2, 5, 5, 2, 4]
24       Mark Williams  CHA  0 - 0 - 0                100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
25      Ja'Kobe Walter  TOR  0 - 1 - 1                 18.84  [1, 2, 2, 2, 1, 0, 0, 0, 0, 2]
26      Jamison Battle  TOR  0 - 1 - 1                 20.20  [2, 3, 1, 4, 4, 3, 1, 3, 1, 3]
27   Immanuel Quickley  TOR  0 - 2 - 3                 40.93  [3, 3, 2, 2, 3, 6, 2, 2, 4, 1]
28      Scottie Barnes  TOR  0 - 1 - 2                  0.00  [0, 0, 3, 1, 1, 0, 1, 0, 1, 0]
29        Jakob Poeltl  TOR  0 - 0 - 0                  0.00  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
30       Mikal Bridges  NYK  0 - 2 - 3                  9.20  [1, 2, 4, 0, 1, 4, 1, 2, 1, 0]
31           Josh Hart  NYK  0 - 0 - 0                 18.53  [0, 2, 0, 3, 0, 2, 0, 2, 4, 1]
32         Tyler Kolek  NYK  0 - 0 - 0                  0.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
33          OG Anunoby  NYK  0 - 0 - 0                 58.87  [3, 3, 4, 3, 2, 1, 2, 3, 3, 2]
34  Karl-Anthony Towns  NYK  0 - 2 - 3                 42.01  [4, 2, 1, 2, 2, 3, 3, 2, 3, 3]
35        Devin Booker  MIL  0 - 1 - 1                 30.08  [1, 1, 6, 3, 0, 4, 2, 3, 0, 5]
36           Ryan Dunn  MIL  0 - 1 - 2                 44.79  [2, 2, 2, 3, 2, 2, 1, 0, 0, 1]
37    Collin Gillespie  MIL  0 - 2 - 4                 40.04  [1, 3, 0, 1, 1, 1, 0, 0, 1, 1]
38        Kevin Durant  MIL  1 - 3 - 4                 48.74  [3, 4, 3, 1, 2, 4, 2, 7, 1, 3]
39       Nick Richards  MIL  0 - 0 - 0                100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
40     Anthony Edwards  MIN  1 - 4 - 6                 47.92  [1, 3, 4, 1, 5, 3, 5, 2, 3, 6]
41     Jaden McDaniels  MIN  0 - 1 - 1                 47.64  [0, 2, 1, 1, 2, 2, 2, 2, 1, 3]
42         Mike Conley  MIN  0 - 1 - 1                 41.51  [1, 0, 4, 2, 3, 1, 3, 3, 3, 1]
43       Julius Randle  MIN  0 - 1 - 1                  7.20  [0, 2, 2, 1, 1, 1, 3, 2, 0, 2]
44         Rudy Gobert  MIN  0 - 0 - 0                100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
45  Brandin Podziemski  GSW  0 - 1 - 1                 24.97  [2, 5, 3, 4, 0, 2, 4, 0, 2, 0]
46         Moses Moody  GSW  0 - 1 - 1                 22.26  [0, 3, 0, 1, 1, 4, 4, 2, 2, 2]
47       Stephen Curry  GSW  2 - 5 - 7                 51.63  [2, 4, 4, 2, 5, 4, 7, 5, 3, 5]
48    Jimmy Butler III  GSW  0 - 0 - 0                 18.83  [0, 1, 1, 1, 1, 1, 0, 0, 2, 1]
49      Draymond Green  GSW  0 - 2 - 4                 22.16  [0, 1, 5, 0, 0, 1, 4, 1, 2, 0]
50      Jordan Hawkins  NOP  0 - 2 - 3                 32.83  [1, 6, 1, 2, 2, 0, 1, 3, 2, 4]
51         Bruce Brown  NOP  0 - 0 - 0                  8.20  [1, 3, 4, 0, 1, 0, 1, 0, 0, 0]
52       Jose Alvarado  NOP  0 - 1 - 1                 36.02  [1, 2, 3, 2, 1, 1, 2, 4, 3, 2]
53        Kelly Olynyk  NOP  0 - 0 - 0                 12.33  [1, 1, 1, 1, 1, 0, 0, 0, 1, 1]
54          Yves Missi  NOP  0 - 0 - 0                100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
55       Collin Sexton  UTA  0 - 1 - 1                 14.84  [3, 1, 0, 4, 2, 1, 0, 1, 2, 0]
56       Cody Williams  UTA  0 - 1 - 1                  6.63  [0, 2, 1, 0, 0, 1, 0, 2, 1, 1]
57      Isaiah Collier  UTA  0 - 1 - 2                 48.03  [1, 4, 1, 0, 2, 0, 0, 0, 1, 1]
58     Kyle Filipowski  UTA  0 - 0 - 0                 25.66  [1, 2, 4, 1, 4, 0, 2, 3, 0, 0]
59      Walker Kessler  UTA  0 - 0 - 0                 54.12  [0, 1, 1, 0, 1, 0, 1, 0, 0, 0]
60     Christian Braun  DEN  0 - 0 - 0                 14.87  [3, 2, 1, 1, 0, 1, 2, 0, 2, 3]
61  Michael Porter Jr.  DEN  0 - 2 - 3                 18.42  [6, 1, 1, 3, 1, 3, 3, 1, 0, 3]
62        Jamal Murray  DEN  0 - 1 - 1                 32.39  [1, 4, 4, 0, 3, 5, 1, 3, 1, 1]
63        Aaron Gordon  DEN  0 - 0 - 0                  0.29  [1, 1, 1, 5, 4, 2, 1, 7, 1, 2]
64        Nikola Jokic  DEN  0 - 2 - 4                 24.57  [3, 1, 0, 2, 1, 2, 3, 0, 2, 0]

Confidence scores for each group:
Parlay 1: 69.72
Parlay 2: 67.86
Parlay 3: 65.94
Parlay 4: 62.66
Parlay 5: 63.58
Parlay 6: 60.24
Parlay 7: 69.51


Parlay 1: total confidence score: 69.72

           Player team Stat    Stat Range  Confidence                               recentgames
0     Evan Mobley  CLE  REB   7 - 11 - 14       72.33     [12, 11, 12, 10, 3, 11, 9, 7, 10, 13]
1     Evan Mobley  CLE  PTS  14 - 20 - 25       71.49  [21, 11, 16, 31, 17, 22, 21, 13, 19, 16]
2  Darius Garland  CLE  PTS  16 - 23 - 29       69.73  [10, 27, 12, 18, 17, 19, 20, 30, 13, 20]
3  Darius Garland  CLE  AST     3 - 5 - 6       65.34            [9, 8, 4, 6, 8, 4, 9, 8, 5, 2]

Parlay 2: total confidence score: 67.86

          Player team Stat    Stat Range  Confidence                               recentgames
0  Kawhi Leonard  LAC  PTS  15 - 22 - 28       71.40  [27, 25, 23, 33, 23, 25, 29, 17, 20, 21]
1   James Harden  LAC  PTS  15 - 22 - 28       69.02  [29, 17, 30, 22, 31, 25, 24, 25, 29, 27]
2  Kawhi Leonard  LAC  REB     1 - 3 - 4       66.10         [10, 10, 10, 7, 6, 6, 8, 4, 7, 4]
3   James Harden  LAC  AST    5 - 9 - 12       64.91         [6, 8, 9, 9, 7, 7, 11, 17, 11, 7]

Parlay 3: total confidence score: 65.94

              Player team Stat    Stat Range  Confidence                               recentgames
0     Scottie Barnes  TOR  PTS  14 - 20 - 25       70.29  [15, 13, 22, 29, 16, 16, 20, 14, 18, 22]
1     Scottie Barnes  TOR  AST     3 - 6 - 8       66.30            [5, 8, 6, 6, 3, 6, 3, 2, 4, 6]
2  Immanuel Quickley  TOR  PTS  12 - 19 - 25       63.77  [21, 21, 15, 20, 15, 34, 15, 24, 23, 18]
3       Jakob Poeltl  TOR  PTS   8 - 13 - 17       63.40    [21, 18, 19, 9, 21, 17, 16, 10, 10, 5]

Parlay 4: total confidence score: 62.66

               Player team Stat    Stat Range  Confidence                               recentgames
0  Karl-Anthony Towns  NYK  REB   9 - 14 - 18       65.93      [14, 12, 11, 10, 9, 7, 12, 7, 9, 10]
1  Karl-Anthony Towns  NYK  PTS  20 - 31 - 41       65.10  [34, 26, 31, 24, 32, 23, 29, 21, 26, 23]
2          OG Anunoby  NYK  PTS   7 - 12 - 16       60.73   [28, 35, 23, 25, 14, 9, 23, 23, 24, 11]
3          OG Anunoby  NYK  3PM     0 - 0 - 0       58.87            [3, 3, 4, 3, 2, 1, 2, 3, 3, 2]

Parlay 5: total confidence score: 63.58

             Player team Stat    Stat Range  Confidence                               recentgames
0    Draymond Green  GSW  AST     4 - 6 - 7       67.11           [3, 6, 5, 4, 5, 3, 4, 7, 7, 10]
1     Stephen Curry  GSW  PTS  15 - 25 - 34       63.95  [17, 20, 28, 11, 24, 32, 40, 28, 21, 29]
2  Jimmy Butler III  GSW  AST     3 - 5 - 6       61.77         [2, 8, 12, 10, 6, 7, 7, 10, 5, 6]
3    Draymond Green  GSW  REB     3 - 6 - 8       61.48           [5, 6, 7, 10, 6, 4, 4, 4, 9, 7]

Parlay 6: total confidence score: 60.24

           Player team Stat    Stat Range  Confidence                              recentgames
0   Collin Sexton  UTA  PTS  15 - 24 - 32       63.05  [21, 15, 10, 30, 18, 22, 8, 22, 16, 17]
1  Walker Kessler  UTA  REB   7 - 12 - 16       62.86    [9, 9, 13, 11, 5, 12, 19, 14, 10, 25]
2  Isaiah Collier  UTA  PTS     3 - 6 - 8       60.94     [16, 21, 7, 5, 16, 8, 11, 16, 11, 8]
3  Walker Kessler  UTA  3PM     0 - 0 - 0       54.12           [0, 1, 1, 0, 1, 0, 1, 0, 0, 0]

Parlay 7: total confidence score: 69.51

            Player team Stat    Stat Range  Confidence                               recentgames
0     Nikola Jokic  DEN  PTS  24 - 33 - 41       73.17  [39, 40, 28, 34, 35, 24, 31, 22, 20, 23]
1     Jamal Murray  DEN  AST     5 - 7 - 8       72.01            [6, 7, 7, 2, 7, 5, 8, 6, 4, 8]
2     Nikola Jokic  DEN  REB  10 - 15 - 19       69.23    [10, 13, 7, 8, 18, 13, 21, 15, 14, 17]
3  Christian Braun  DEN  PTS  11 - 18 - 24       63.61    [19, 18, 11, 15, 10, 9, 22, 6, 14, 19]

In [ ]:
def get_safe_bets(df, confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df["confidence_level_PTS"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets["PTS"].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", "PTS", "Safe Bet", "confidence_level_PTS"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_pts, confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df, confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df["confidence_level_REB"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets["REB"].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", "REB", "Safe Bet", "confidence_level_REB"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_reb, confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df,target ,confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df[f"confidence_level_{target}"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets[target].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", f"{target}", "Safe Bet", f"confidence_level_{target}"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_ast,"AST" ,confidence_threshold=60)
print(safe_bets_df)

In [ ]:
def get_safe_bets(df,target ,confidence_threshold=60):
    """
    Filters the DataFrame for safe bets based on confidence threshold.
    Selects the lowest value in the stat range for a conservative bet.
    """
    safe_bets = df[df[f"confidence_level_{target}"] >= confidence_threshold].copy()
    
    # Extract the lowest stat value from the "Stat Range" column
    safe_bets["Safe Bet"] = safe_bets[target].apply(lambda x: int(x.split(" - ")[0]))
    
    # Select only necessary columns
    safe_bets = safe_bets[["Player", "team", f"{target}", "Safe Bet", f"confidence_level_{target}"]]
    
    return safe_bets

# Example Usage:
safe_bets_df = get_safe_bets(results_3pm,"3PM" ,confidence_threshold=50)
print(safe_bets_df)

In [ ]:
results_pts.head(10)

In [ ]:
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players

# Retrieve player ID (e.g., LeBron James)
for basketball_players in results_pts["Player"]:
    a_player = players.find_players_by_full_name(basketball_players)[0]
    player_id = a_player['id']

    gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')  # Use the latest season
    games = gamelog.get_data_frames()[0]  # Extract data frame
    
    latest_game = games.iloc[0]
    print(basketball_players,latest_game['PTS'])




# player_name = "LeBron James"
# player = players.find_players_by_full_name(player_name)[0]  # Get player data by name

# player_id = player['id']  # Get player ID

# # Fetch the player's game log (latest games)
# gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')  # Use the latest season
# games = gamelog.get_data_frames()[0]  # Extract data frame

# # Get the latest game data
# latest_game = games.iloc[0]  # Latest game data
# print(type(latest_game))
# print(latest_game["PTS"])
# display(latest_game)

In [ ]:
from nba_api.stats.endpoints import commonteamroster
from nba_api.stats.static import teams
import pandas as pd
from unidecode import unidecode

# List of team abbreviations you want to check
team_abbreviations = ['CLE', 'DET', 'LAC', 'BKN', 'CHA', 'TOR', 'NYK', 'MIL', 'MIN', 'GSW', 'NOP', 'UTA', 'DEN']  # Example teams

# Get all NBA teams and create a mapping of abbreviations to team IDs
nba_teams = teams.get_teams()
team_id_map = {team['abbreviation']: team['id'] for team in nba_teams}

# Dictionary to store team rosters
team_rosters = {}

# Loop through each team
for team_abbr in team_abbreviations:
    team_id = team_id_map[team_abbr]

    # Specify the season in 'YYYY-YY' format
    season = '2024-25'

    # Retrieve the team's roster
    roster = commonteamroster.CommonTeamRoster(team_id=team_id, season=season)

    # Convert the roster data to a pandas DataFrame
    roster_df = roster.get_data_frames()[0]

    # Normalize player names by removing accents
    roster_df['PLAYER_uni'] = roster_df['PLAYER'].apply(unidecode)

    # Store the roster for the team
    team_rosters[team_abbr] = roster_df

# Display rosters
for team_abbr, roster_df in team_rosters.items():
    print(f"\n{team_abbr} Roster:")
    display(roster_df)  # or use print(roster_df) if you're not in a Jupyter notebook

In [ ]:
# Display rosters
for team_abbr, roster_df in team_rosters.items():
    print(f"\n{team_abbr} Roster:")
    display(roster_df)  # or use print(roster_df) if you're not in a Jupyter notebook

In [ ]:


matched_players_list = []
for team_abbr, roster_df in team_rosters.items():
    # print(f"\n{team_abbr} Roster:")
    df_roster = roster_df[['PLAYER', 'PLAYER_uni']]

    if team_abbr in results_pts['team'].values:
        matched_players = df_roster[df_roster['PLAYER_uni'].isin(results_pts['Player'])]
        
        if not matched_players.empty:
            matched_players = matched_players['PLAYER']
            matched_players_list.append(matched_players)
            # display(matched_players)
            # print(matched_players)

# Combine all matched players into a single DataFrame
if matched_players_list:
    final_matched_df = pd.concat(matched_players_list, ignore_index=True)
    display(final_matched_df)  # Display the final combined DataFrame
else:
    print("No matches found.")


from nba_api.stats.endpoints import playergamelog
from nba_api.stats.static import players

# Retrieve player ID (e.g., LeBron James)
player_list = final_matched_df.tolist()
for basketball_players in player_list:
    found_players = players.find_players_by_full_name(basketball_players)

    if found_players:
        a_player = found_players[0]
        player_id = a_player['id']

        # Fetch game log
        gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')
        games = gamelog.get_data_frames()[0]  # Extract DataFrame
        
        if not games.empty:
            latest_game = games.iloc[0]  # Get the most recent game
            print(f"{basketball_players}: {latest_game['PTS']} points")
        else:
            print(f"{basketball_players}: No game data available")

    else:
        print(f"Player not found: {basketball_players}")

In [ ]:

# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

# results_3pm = results_3pm[results_3pm["confidence_level_3PM"] != 100.00]
# df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
#     .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
#     .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))

# df_merged = df_merged[df_merged["Player"] != 'Tyrese Haliburton']


# print(df_merged.columns)


# df_merged['middlebet_PTS+REB'] = 0000

# df_merged['PTS+REB'] = df_merged[['middlebet_PTS', 'middlebet_REB']].sum(axis=1)
# df_merged['confidence_level_PTS+REB']=  round(df_merged[['confidence_level_PTS','confidence_level_REB']].sum(axis=1)/2,2)
# df_merged = df_merged.rename(columns={'FGA': 'PTS'})
# display(df_merged)
# display(df_merged[['Player','confidence_level_PTS+REB']])


from parlay_picker import create_parlays, create_parlays_high

num_groups = 10  # Number of parlays you want to generate
players_per_group = 9  # Number of players in each parlay
min_confidence = 70

parlays_df, group_confidence_scores = create_parlays_high(df_merged, num_groups, players_per_group,min_confidence, 70)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")