In [1]:
import pandas as pd
import os
import numpy as np
from IPython.display import display
import pprint
from datetime import datetime




pd.set_option('display.max_rows', 1000)  # Maximum number of rows to display
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', 1000)  # Adjust column width for better readability




import os
import pandas as pd
import sys

log_file_path = "streamlit_consumption\streamlit_log.log"


# # Open the log file in append mode ("a")
# sys.stdout = open(log_file_path, "w")
# sys.stderr = open(log_file_path, "w")

# input_dir = os.makedirs("D:\streamlit_ingest", exist_ok=True)
main_folder = "D:/prediction_output"
nested_df_dict = {}


def get_subfolder_name(main_folder, nested_df_dict):
    for root, dirs, files in os.walk(main_folder):
        for file in files:
            if file.endswith(".csv"):
                subfolder_name = os.path.basename(root)  # Get subfolder name
                file_path = os.path.join(root, file)
                df_name = os.path.splitext(file)[0]      # Get filename without .csv

                # Read CSV
                df = pd.read_csv(file_path)

                # Create subfolder dictionary if it doesn't exist
                if subfolder_name not in nested_df_dict:
                    nested_df_dict[subfolder_name] = {}

                # Store the DataFrame inside its subfolder
                nested_df_dict[subfolder_name][df_name] = df
    return nested_df_dict

nested_df_dict = get_subfolder_name(main_folder, nested_df_dict)


# pprint.pprint(nested_df_dict)
print(nested_df_dict.keys())
# print(nested_df_dict)
# print(nested_df_dict["PTS_outputs"].keys())
# df = nested_df_dict["PTS_outputs"]["PTS_output_2025-04-06"]
# display(df)

# Access the inner dictionary

linear_prediction_dict_list = ["PTS_outputs", "AST_outputs", "REB_outputs", "3PM_outputs"]

linear_prediction_df_list = []
for i in linear_prediction_dict_list:
    inner_dict = nested_df_dict[i]

    # Get the last key (in insertion order, which is preserved in Python 3.7+)
    last_key = list(inner_dict.keys())[-1]

    # Get the corresponding DataFrame
    last_df = inner_dict[last_key]

    # Optional: show the key and DataFrame shape
    print(f"Last file: {last_key}, shape: {last_df.shape}")

    linear_prediction_df_list.append(last_df)



import ast

def calculate_score_percentages(row,target):
    # Safely parse the recentgames_PTS list from string to list
    try:
        recent_games = ast.literal_eval(row[f'recentgames_{target}']) if isinstance(row[f'recentgames_{target}'], str) else row[f'recentgames_{target}']
    except Exception:
        return pd.Series([0, 0, 0], index=['First_Pct', 'Second_Pct', 'Third_Pct'])

    if not recent_games or len(recent_games) == 0:
        return pd.Series([0, 0, 0], index=['First_Pct', 'Second_Pct', 'Third_Pct'])

    total_games = len(recent_games)
    
    # Ensure thresholds are integers
    first = int(row[f'{target}_First'])
    second = int(row[f'{target}_Second'])
    third = int(row[f'{target}_Third'])


    

    # Count scores >= threshold
    first_count = sum(int(score) >= first for score in recent_games)
    second_count = sum(int(score) >= second for score in recent_games)
    third_count = sum(int(score) >= third for score in recent_games)

    # Convert to percentages
    first_pct = round((first_count / total_games) * 100, 2)
    second_pct = round((second_count / total_games) * 100, 2)
    third_pct = round((third_count / total_games) * 100, 2)

    if first_pct == 100 :
        first_pct = 95

    if second_pct == 100:
        second_pct = 95
        
    if third_pct == 100:
        third_pct = 95    


    return pd.Series([first_pct, second_pct, third_pct], index=['First_Pct', 'Second_Pct', 'Third_Pct'])





list_of_targets = ["PTS", "AST", "REB", "3PM"]

target_number = [0,1,2,3]

final_processed_dfs = []


for i in target_number:
    
    target = list_of_targets[i]

    df = linear_prediction_df_list[i]

    df[['First', 'Second', 'Third']] = df[target].str.split(' - ', expand=True).astype(int)

    df = df.rename(columns=lambda x: f"{target}_{x}" if x in ['First', 'Second', 'Third'] else x)




    display(df.head(10))

    team_totals = df.groupby('team', sort=False)[[f'{target}_First', f'{target}_Second', f'{target}_Third']].sum()
    team_totals['Total'] = team_totals.sum(axis=1)
    team_totals_reset = team_totals.reset_index()  # keeps 'team' as column, keeps order


    print(team_totals)


    # Reset index to get 'team' as a column
    team_totals_reset = team_totals.reset_index()

    # Sort alphabetically (or however you want)
    # team_totals_reset = team_totals_reset.sort_values(by='team').reset_index(drop=True)

    # Create matchups and determine winner based on 'First'
    matchups = []
    for i in range(0, len(team_totals_reset) - 1, 2):
        team1 = team_totals_reset.iloc[i]
        team2 = team_totals_reset.iloc[i + 1]

        winner = team1['team'] if team1[f'{target}_First'] > team2[f'{target}_First'] else team2['team']
        matchup = f"{team1['team']} vs {team2['team']}"

        matchups.append({
            'Matchup': matchup,
            'Winner': winner,
            'Team1_First': team1[f'{target}_First'],
            'Team2_First': team2[f'{target}_First']
        })

    # Convert to DataFrame
    matchups_df = pd.DataFrame(matchups)

    # Display results
    today_date = datetime.today().strftime('%Y-%m-%d')

    matchup_dir = f"D:/streamlit_ingest/matchup_{target}"

    os.makedirs(matchup_dir, exist_ok=True)

    matchup_file_path = os.path.join(matchup_dir, f"matchup_{today_date}.csv")

    matchups_df.to_csv(matchup_file_path, index=False)



    # display(matchups_df)


    






    # Apply to your dataframe
    df[['First_Pct', 'Second_Pct', 'Third_Pct']] = df.apply(lambda row: calculate_score_percentages(row,target), axis=1)

    first_second_third = df[['Player', 'team' ,f'{target}_First', f'{target}_Second', f'{target}_Third','First_Pct', 'Second_Pct', 'Third_Pct', f'recentgames_{target}']]
    first_second_third[f'recentgames_{target}'] = first_second_third[f'recentgames_{target}'].astype(str).str.replace(r'[\[\]]', '', regex=True)



    first_second_third_dir = f"D:/streamlit_ingest/first_second_third_{target}"

    os.makedirs(first_second_third_dir, exist_ok=True)

    first_second_third_file_path = os.path.join(first_second_third_dir, f"first_second_third_{today_date}.csv")

    first_second_third.to_csv(first_second_third_file_path, index=False)

    display(first_second_third.head(10))
    

    df = df.rename(columns={
    'First_Pct': f'{target}_First_Pct',
    'Second_Pct': f'{target}_Second_Pct',
    'Third_Pct': f'{target}_Third_Pct'})
    df[f'recentgames_{target}'] = df[f'recentgames_{target}'].astype(str).str.replace(r'[\[\]]', '', regex=True)


    # Save the processed df to combine later
    # ['Player', 'team', '3PM', 'cv-1_3PM', 'recentgames_3PM', 'rmse_3PM', '3PM_First', '3PM_Second', '3PM_Third', '3PM_First_Pct', '3PM_Second_Pct', '3PM_Third_Pct']
    final_processed_dfs.append(df)


    # Preview
    # display(df[['Player', 'team' ,f'{target}_First', f'{target}_Second', f'{target}_Third','First_Pct', 'Second_Pct', 'Third_Pct']])


from functools import reduce

# Merge on Player and team
final_merged_df = reduce(
    lambda left, right: pd.merge(left, right, on=['Player', 'team'], how='outer'),
    final_processed_dfs
)


final_merged_df_dir = f"D:/streamlit_ingest/final_merged_df"

os.makedirs(final_merged_df_dir, exist_ok=True)

final_merged_df_file_path = os.path.join(final_merged_df_dir, f"final_merged_df_{today_date}.csv")

final_merged_df.to_csv(final_merged_df_file_path, index=False)

# Final combined dataframe
print(final_merged_df)

dict_keys(['3PM_outputs', 'AST_outputs', 'PTS_outputs', 'REB_outputs'])
Last file: PTS_output_2025-04-13, shape: (485, 6)
Last file: AST_output_2025-04-13, shape: (485, 6)
Last file: REB_output_2025-04-13, shape: (485, 6)
Last file: 3PM_output_2025-04-13, shape: (485, 6)

               Player team           PTS  cv-1_PTS                           recentgames_PTS      rmse_PTS  PTS_First  PTS_Second  PTS_Third
0      Keaton Wallace  ATL    0 - 0 - 12      0.00            [0, 2, 7, 0, 3, 3, 3, 5, 2, 4]  3.211207e-14          0           0         12
1        Caris LeVert  ATL   3 - 18 - 32     51.87     [31, 4, 13, 21, 14, 14, 10, 9, 17, 5]  2.913442e-15          3          18         32
2       Dyson Daniels  ATL   0 - 11 - 21     61.82    [8, 10, 15, 19, 12, 17, 22, 22, 9, 19]  4.000326e-15          0          11         21
3  Zaccharie Risacher  ATL   0 - 12 - 29     40.51      [12, 38, 8, 16, 12, 9, 9, 36, 5, 18]  2.921746e-15          0          12         29
4          Trae Young  ATL  16 - 30 - 43     73.91  [36, 24, 28, 23, 16, 25, 29, 19, 29, 19]  4.444180e-15         16          30         43
5        Terance Mann  ATL    0 - 5 - 13     54.98       [5, 14, 0, 10, 14, 5, 7, 9, 14, 16]  1.899005e-15          0           5         13
6        Clint Capela  ATL    0 - 4 - 12     43.55           [4, 8, 6, 8, 11, 0, 8, 8, 8, 3]  5.628541e-15          0           4         12
7      Onyeka Okongwu  ATL   0 - 12 - 25     56.13    [4, 14, 30, 27, 6, 20, 12, 13, 15, 14]  2.233098e-15          0          12         25
8      Mouhamed Gueye  ATL    0 - 6 - 13     36.87          [10, 5, 6, 8, 6, 11, 0, 9, 4, 6]  6.760941e-15          0           6         13
9       Georges Niang  ATL   0 - 11 - 24     41.33       [16, 11, 9, 6, 13, 6, 3, 17, 5, 12]  3.067229e-15          0          11         24

      PTS_First  PTS_Second  PTS_Third  Total
team
ATL          48         152        305    505
ORL          26         136        261    423
BOS           8         138        297    443
CHA          11         121        262    394
BKN          20         135        286    441
NYK          18         131        270    419
CLE          35         156        291    482
IND          20         136        273    429
MIA          14         147        303    464
WAS           8         140        313    461
PHI          12         161        367    540
CHI          14         150        313    477
MIL          27         143        286    456
DET          33         120        237    390
HOU          10         148        321    479
DEN          11         135        300    446
MEM          15         132        298    445
DAL           6         157        359    522
MIN          13         125        279    417
UTA          22         172        333    527
NOP          24         158        317    499
OKC          37         192        371    600
SAS          29         157        316    502
TOR          16         139        284    439
GSW          10         112        269    391
LAC          26         126        255    407
POR          19         164        362    545
LAL          35         132        282    449
SAC           8         121        259    388
PHX           8         134        315    457

C:\Users\mandy\AppData\Local\Temp\ipykernel_26060\2942641469.py:214: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  first_second_third[f'recentgames_{target}'] = first_second_third[f'recentgames_{target}'].astype(str).str.replace(r'[\[\]]', '', regex=True)

               Player team  PTS_First  PTS_Second  PTS_Third  First_Pct  Second_Pct  Third_Pct                         recentgames_PTS
0      Keaton Wallace  ATL          0           0         12       95.0        95.0        0.0            0, 2, 7, 0, 3, 3, 3, 5, 2, 4
1        Caris LeVert  ATL          3          18         32       95.0        20.0        0.0     31, 4, 13, 21, 14, 14, 10, 9, 17, 5
2       Dyson Daniels  ATL          0          11         21       95.0        70.0       20.0    8, 10, 15, 19, 12, 17, 22, 22, 9, 19
3  Zaccharie Risacher  ATL          0          12         29       95.0        60.0       20.0      12, 38, 8, 16, 12, 9, 9, 36, 5, 18
4          Trae Young  ATL         16          30         43       95.0        10.0        0.0  36, 24, 28, 23, 16, 25, 29, 19, 29, 19
5        Terance Mann  ATL          0           5         13       95.0        90.0       40.0       5, 14, 0, 10, 14, 5, 7, 9, 14, 16
6        Clint Capela  ATL          0           4         12       95.0        80.0        0.0           4, 8, 6, 8, 11, 0, 8, 8, 8, 3
7      Onyeka Okongwu  ATL          0          12         25       95.0        80.0       20.0    4, 14, 30, 27, 6, 20, 12, 13, 15, 14
8      Mouhamed Gueye  ATL          0           6         13       95.0        70.0        0.0          10, 5, 6, 8, 6, 11, 0, 9, 4, 6
9       Georges Niang  ATL          0          11         24       95.0        50.0        0.0       16, 11, 9, 6, 13, 6, 3, 17, 5, 12

               Player team          AST  cv-1_AST                          recentgames_AST  rmse_AST  AST_First  AST_Second  AST_Third
0      Keaton Wallace  ATL    0 - 1 - 5     10.94           [1, 3, 6, 0, 1, 0, 3, 0, 4, 2]  1.034244          0           1          5
1        Caris LeVert  ATL    0 - 2 - 6     32.24           [4, 5, 0, 6, 3, 5, 0, 1, 3, 0]  2.578506          0           2          6
2       Dyson Daniels  ATL    0 - 4 - 9     52.14          [8, 9, 3, 6, 1, 5, 1, 6, 3, 10]  1.903229          0           4          9
3  Zaccharie Risacher  ATL    0 - 1 - 3      5.27           [0, 2, 1, 2, 1, 1, 2, 0, 4, 1]  1.298712          0           1          3
4          Trae Young  ATL  5 - 11 - 16     75.22  [11, 12, 10, 15, 9, 12, 15, 19, 12, 12]  3.049479          5          11         16
5        Terance Mann  ATL    0 - 2 - 5      8.41           [1, 0, 5, 1, 1, 2, 0, 4, 1, 1]  1.398602          0           2          5
6        Clint Capela  ATL    0 - 0 - 1     29.17           [1, 1, 0, 1, 1, 0, 2, 1, 0, 1]  0.936845          0           0          1
7      Onyeka Okongwu  ATL    0 - 2 - 4     46.95           [1, 2, 4, 3, 2, 2, 3, 3, 0, 3]  1.396545          0           2          4
8      Mouhamed Gueye  ATL    0 - 1 - 2     20.09           [2, 1, 2, 1, 1, 0, 0, 1, 1, 2]  1.431017          0           1          2
9       Georges Niang  ATL    0 - 1 - 3     20.97           [0, 1, 0, 4, 1, 1, 1, 1, 0, 2]  1.272423          0           1          3

      AST_First  AST_Second  AST_Third  Total
team
ATL           5          26         62     93
ORL           0          26         59     85
BOS           1          27         69     97
CHA           0          23         58     81
BKN           0          28         68     96
NYK           2          31         74    107
CLE           4          31         66    101
IND           2          30         67     99
MIA           2          33         77    112
WAS           1          28         72    101
PHI           1          33         79    113
CHI           0          34         85    119
MIL           3          31         71    105
DET           2          22         54     78
HOU           1          27         67     95
DEN           8          39         84    131
MEM           1          27         66     94
DAL           0          24         72     96
MIN           3          32         67    102
UTA           3          29         71    103
NOP           4          38         89    131
OKC           1          34         80    115
SAS           3          33         73    109
TOR           3          32         73    108
GSW           0          24         62     86
LAC           5          27         62     94
POR           1          27         70     98
LAL           1          27         67     95
SAC           3          27         64     94
PHX           0          30         77    107

C:\Users\mandy\AppData\Local\Temp\ipykernel_26060\2942641469.py:214: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  first_second_third[f'recentgames_{target}'] = first_second_third[f'recentgames_{target}'].astype(str).str.replace(r'[\[\]]', '', regex=True)

               Player team  AST_First  AST_Second  AST_Third  First_Pct  Second_Pct  Third_Pct                        recentgames_AST
0      Keaton Wallace  ATL          0           1          5       95.0        70.0       10.0           1, 3, 6, 0, 1, 0, 3, 0, 4, 2
1        Caris LeVert  ATL          0           2          6       95.0        60.0       10.0           4, 5, 0, 6, 3, 5, 0, 1, 3, 0
2       Dyson Daniels  ATL          0           4          9       95.0        60.0       20.0          8, 9, 3, 6, 1, 5, 1, 6, 3, 10
3  Zaccharie Risacher  ATL          0           1          3       95.0        80.0       10.0           0, 2, 1, 2, 1, 1, 2, 0, 4, 1
4          Trae Young  ATL          5          11         16       95.0        80.0       10.0  11, 12, 10, 15, 9, 12, 15, 19, 12, 12
5        Terance Mann  ATL          0           2          5       95.0        30.0       10.0           1, 0, 5, 1, 1, 2, 0, 4, 1, 1
6        Clint Capela  ATL          0           0          1       95.0        95.0       70.0           1, 1, 0, 1, 1, 0, 2, 1, 0, 1
7      Onyeka Okongwu  ATL          0           2          4       95.0        80.0       10.0           1, 2, 4, 3, 2, 2, 3, 3, 0, 3
8      Mouhamed Gueye  ATL          0           1          2       95.0        80.0       30.0           2, 1, 2, 1, 1, 0, 0, 1, 1, 2
9       Georges Niang  ATL          0           1          3       95.0        70.0       10.0           0, 1, 0, 4, 1, 1, 1, 1, 0, 2

               Player team         REB  cv-1_REB                       recentgames_REB      rmse_REB  REB_First  REB_Second  REB_Third
0      Keaton Wallace  ATL   0 - 0 - 2      0.00        [0, 1, 2, 0, 1, 0, 1, 0, 0, 2]  3.391787e-16          0           0          2
1        Caris LeVert  ATL   0 - 3 - 5     63.08        [4, 3, 6, 5, 4, 4, 2, 3, 5, 1]  3.972055e-16          0           3          5
2       Dyson Daniels  ATL  3 - 8 - 12     66.78      [10, 9, 5, 6, 2, 6, 10, 9, 8, 8]  3.356999e-16          3           8         12
3  Zaccharie Risacher  ATL   0 - 3 - 7     37.95        [3, 4, 1, 2, 4, 3, 3, 6, 0, 4]  4.008461e-16          0           3          7
4          Trae Young  ATL   0 - 2 - 5     43.74        [3, 1, 1, 5, 1, 4, 4, 3, 2, 2]  4.098758e-16          0           2          5
5        Terance Mann  ATL   0 - 2 - 5     50.75        [2, 3, 4, 5, 6, 3, 3, 1, 1, 4]  1.275549e-15          0           2          5
6        Clint Capela  ATL  0 - 6 - 12     59.70       [9, 9, 5, 8, 4, 4, 3, 11, 7, 4]  1.294731e-15          0           6         12
7      Onyeka Okongwu  ATL  2 - 9 - 15     68.74  [8, 15, 14, 12, 5, 14, 6, 10, 9, 15]  1.020991e-15          2           9         15
8      Mouhamed Gueye  ATL  0 - 8 - 16     13.02      [18, 12, 5, 3, 3, 5, 2, 9, 4, 1]  1.158698e-15          0           8         16
9       Georges Niang  ATL   0 - 2 - 5     19.88        [3, 0, 1, 1, 4, 2, 0, 1, 3, 0]  9.819182e-16          0           2          5

      REB_First  REB_Second  REB_Third  Total
team
ATL           5          48        108    161
ORL           1          42         92    135
BOS           3          51        114    168
CHA           6          51        118    175
BKN           2          49        103    154
NYK           7          45         99    151
CLE          27          75        129    231
IND           1          43         98    142
MIA           4          59        117    180
WAS           1          50        115    166
PHI           2          57        129    188
CHI           8          57        122    187
MIL           9          49        109    167
DET           5          38         87    130
HOU           5          59        128    192
DEN           9          54        117    180
MEM           1          52        124    177
DAL           2          66        145    213
MIN           0          40         97    137
UTA           4          67        140    211
NOP           4          49        107    160
OKC           5          59        127    191
SAS           7          55        118    180
TOR           3          55        118    176
GSW           1          40         99    140
LAC           6          41         92    139
POR           0          61        139    200
LAL           3          44        105    152
SAC           1          42         99    142
PHX           1          47        114    162

C:\Users\mandy\AppData\Local\Temp\ipykernel_26060\2942641469.py:214: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  first_second_third[f'recentgames_{target}'] = first_second_third[f'recentgames_{target}'].astype(str).str.replace(r'[\[\]]', '', regex=True)

               Player team  REB_First  REB_Second  REB_Third  First_Pct  Second_Pct  Third_Pct                     recentgames_REB
0      Keaton Wallace  ATL          0           0          2       95.0        95.0       20.0        0, 1, 2, 0, 1, 0, 1, 0, 0, 2
1        Caris LeVert  ATL          0           3          5       95.0        80.0       30.0        4, 3, 6, 5, 4, 4, 2, 3, 5, 1
2       Dyson Daniels  ATL          3           8         12       90.0        60.0        0.0      10, 9, 5, 6, 2, 6, 10, 9, 8, 8
3  Zaccharie Risacher  ATL          0           3          7       95.0        70.0        0.0        3, 4, 1, 2, 4, 3, 3, 6, 0, 4
4          Trae Young  ATL          0           2          5       95.0        70.0       10.0        3, 1, 1, 5, 1, 4, 4, 3, 2, 2
5        Terance Mann  ATL          0           2          5       95.0        80.0       20.0        2, 3, 4, 5, 6, 3, 3, 1, 1, 4
6        Clint Capela  ATL          0           6         12       95.0        50.0        0.0       9, 9, 5, 8, 4, 4, 3, 11, 7, 4
7      Onyeka Okongwu  ATL          2           9         15       95.0        70.0       20.0  8, 15, 14, 12, 5, 14, 6, 10, 9, 15
8      Mouhamed Gueye  ATL          0           8         16       95.0        30.0       10.0      18, 12, 5, 3, 3, 5, 2, 9, 4, 1
9       Georges Niang  ATL          0           2          5       95.0        40.0        0.0        3, 0, 1, 1, 4, 2, 0, 1, 3, 0

               Player team        3PM  cv-1_3PM                 recentgames_3PM      rmse_3PM  3PM_First  3PM_Second  3PM_Third
0      Keaton Wallace  ATL  0 - 0 - 2      6.90  [0, 0, 1, 0, 1, 1, 1, 1, 0, 0]  3.945938e-01          0           0          2
1        Caris LeVert  ATL  0 - 2 - 4     29.80  [4, 0, 2, 3, 1, 1, 0, 1, 2, 1]  8.361503e-15          0           2          4
2       Dyson Daniels  ATL  0 - 0 - 2     38.11  [0, 0, 0, 2, 1, 3, 0, 0, 1, 3]  1.363064e-08          0           0          2
3  Zaccharie Risacher  ATL  0 - 1 - 4     15.55  [0, 6, 2, 2, 2, 1, 0, 5, 1, 0]  1.591162e-09          0           1          4
4          Trae Young  ATL  0 - 4 - 7     37.71  [6, 3, 3, 4, 3, 2, 3, 2, 6, 3]  1.278381e-13          0           4          7
5        Terance Mann  ATL  0 - 1 - 2     12.01  [1, 1, 0, 1, 2, 1, 0, 1, 2, 2]  1.353168e-09          0           1          2
6        Clint Capela  ATL  0 - 0 - 0    100.00  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  0.000000e+00          0           0          0
7      Onyeka Okongwu  ATL  0 - 1 - 3     57.91  [0, 1, 4, 2, 0, 1, 0, 1, 1, 2]  3.978337e-14          0           1          3
8      Mouhamed Gueye  ATL  0 - 0 - 1     12.61  [1, 0, 1, 1, 0, 1, 0, 1, 0, 0]  6.037162e-01          0           0          1
9       Georges Niang  ATL  0 - 2 - 4     41.04  [4, 3, 1, 2, 3, 2, 1, 4, 1, 3]  2.380788e-14          0           2          4

      3PM_First  3PM_Second  3PM_Third  Total
team
ATL           7          20         45     72
ORL           0          12         34     46
BOS           0          20         52     72
CHA           0          17         38     55
BKN           0          16         41     57
NYK           0          13         31     44
CLE           0          19         42     61
IND           0          15         36     51
MIA           0          18         43     61
WAS           0          14         46     60
PHI           0          13         41     54
CHI           0          19         47     66
MIL           0          17         39     56
DET           0          14         34     48
HOU           0          17         43     60
DEN           0          10         36     46
MEM           0          14         39     53
DAL           0          14         36     50
MIN           0          15         38     53
UTA           0          16         43     59
NOP           0          14         37     51
OKC           0          23         52     75
SAS           1          18         43     62
TOR           0          16         38     54
GSW           0          14         39     53
LAC           0          14         33     47
POR           0          13         36     49
LAL           0          16         42     58
SAC           0          13         35     48
PHX           0          21         52     73

C:\Users\mandy\AppData\Local\Temp\ipykernel_26060\2942641469.py:214: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  first_second_third[f'recentgames_{target}'] = first_second_third[f'recentgames_{target}'].astype(str).str.replace(r'[\[\]]', '', regex=True)

               Player team  3PM_First  3PM_Second  3PM_Third  First_Pct  Second_Pct  Third_Pct               recentgames_3PM
0      Keaton Wallace  ATL          0           0          2       95.0        95.0        0.0  0, 0, 1, 0, 1, 1, 1, 1, 0, 0
1        Caris LeVert  ATL          0           2          4       95.0        40.0       10.0  4, 0, 2, 3, 1, 1, 0, 1, 2, 1
2       Dyson Daniels  ATL          0           0          2       95.0        95.0       30.0  0, 0, 0, 2, 1, 3, 0, 0, 1, 3
3  Zaccharie Risacher  ATL          0           1          4       95.0        70.0       20.0  0, 6, 2, 2, 2, 1, 0, 5, 1, 0
4          Trae Young  ATL          0           4          7       95.0        30.0        0.0  6, 3, 3, 4, 3, 2, 3, 2, 6, 3
5        Terance Mann  ATL          0           1          2       95.0        80.0       30.0  1, 1, 0, 1, 2, 1, 0, 1, 2, 2
6        Clint Capela  ATL          0           0          0       95.0        95.0       95.0  0, 0, 0, 0, 0, 0, 0, 0, 0, 0
7      Onyeka Okongwu  ATL          0           1          3       95.0        70.0       10.0  0, 1, 4, 2, 0, 1, 0, 1, 1, 2
8      Mouhamed Gueye  ATL          0           0          1       95.0        95.0       50.0  1, 0, 1, 1, 0, 1, 0, 1, 0, 0
9       Georges Niang  ATL          0           2          4       95.0        70.0       20.0  4, 3, 1, 2, 3, 2, 1, 4, 1, 3

                       Player team           PTS  cv-1_PTS                         recentgames_PTS      rmse_PTS  PTS_First  PTS_Second  PTS_Third  PTS_First_Pct  PTS_Second_Pct  PTS_Third_Pct          AST  cv-1_AST                        recentgames_AST      rmse_AST  AST_First  AST_Second  AST_Third  AST_First_Pct  AST_Second_Pct  AST_Third_Pct           REB  cv-1_REB                         recentgames_REB      rmse_REB  REB_First  REB_Second  REB_Third  REB_First_Pct  REB_Second_Pct  REB_Third_Pct        3PM  cv-1_3PM                recentgames_3PM      rmse_3PM  3PM_First  3PM_Second  3PM_Third  3PM_First_Pct  3PM_Second_Pct  3PM_Third_Pct
0                 A.J. Lawson  TOR    0 - 9 - 25     19.07       12, 14, 13, 9, 13, 13, 0, 2, 2, 8  1.111741e-13          0           9         25          95.00           60.00           0.00    0 - 1 - 5     28.82           2, 7, 0, 1, 4, 1, 0, 0, 0, 2  1.765714e+00          0           1          5          95.00           60.00          10.00    0 - 5 - 11     24.55           10, 6, 1, 3, 3, 6, 3, 1, 3, 2  8.343680e-16          0           5         11          95.00           30.00           0.00  0 - 1 - 4     75.10   1, 2, 1, 1, 1, 2, 0, 0, 0, 1  8.713685e-09          0           1          4           95.0            70.0            0.0
1                    AJ Green  MIL    0 - 8 - 17     30.70         9, 3, 9, 6, 10, 12, 8, 15, 2, 3  1.672325e-15          0           8         17          95.00           60.00           0.00    0 - 1 - 3     16.23           0, 3, 1, 1, 2, 0, 0, 5, 2, 3  1.450824e+00          0           1          3          95.00           70.00          30.00     1 - 4 - 6     46.47            6, 3, 4, 3, 3, 2, 2, 5, 2, 2  5.377915e-16          1           4          6          95.00           30.00          10.00  0 - 2 - 5     18.89   3, 1, 3, 2, 2, 4, 2, 5, 0, 1  2.032375e-14          0           2          5           95.0            70.0           10.0
2                  AJ Johnson  WAS    0 - 6 - 16     41.77        8, 7, 8, 12, 11, 19, 8, 20, 2, 9  8.753946e-01          0           6         16          95.00           90.00          20.00    0 - 1 - 5     24.25           1, 3, 0, 4, 2, 6, 1, 4, 0, 6  7.607051e+00          0           1          5          95.00           80.00          20.00     0 - 2 - 5     21.59            3, 4, 1, 0, 4, 2, 3, 1, 3, 5  6.488857e-01          0           2          5          95.00           70.00          10.00  0 - 0 - 1      6.63   0, 1, 0, 2, 1, 2, 0, 3, 0, 1  5.720356e-01          0           0          1           95.0            95.0           60.0
3                Aaron Gordon  DEN   0 - 19 - 38     44.24     33, 21, 5, 15, 30, 6, 7, 13, 23, 26  3.768222e-15          0          19         38          95.00           50.00           0.00    0 - 4 - 8     28.09           0, 5, 4, 8, 5, 5, 1, 8, 4, 0  2.066338e+00          0           4          8          95.00           70.00          20.00     0 - 4 - 9     46.25           5, 3, 3, 2, 8, 5, 2, 4, 3, 11  5.984157e-16          0           4          9          95.00           50.00          10.00  0 - 1 - 4      8.23   2, 1, 0, 0, 4, 1, 1, 1, 1, 5  6.831490e-14          0           1          4           95.0            80.0           20.0
4               Aaron Holiday  HOU    0 - 6 - 17     13.09         11, 16, 3, 0, 6, 11, 2, 6, 0, 8  7.054814e-15          0           6         17          95.00           60.00           0.00    0 - 1 - 4      6.56           4, 4, 1, 0, 2, 1, 1, 1, 0, 1  1.090219e+00          0           1          4          95.00           80.00          20.00     0 - 1 - 3     22.96            2, 2, 2, 0, 2, 2, 0, 1, 0, 1  7.254409e-16          0           1          3          95.00           70.00           0.00  0 - 1 - 3     13.67   2, 4, 1, 0, 2, 3, 0, 2, 0, 2  6.054983e-14          0           1          3           95.0            70.0           20.0
5               Aaron Nesmith  IND   4 - 17 - 29     58.74    22, 7, 17, 12, 16, 24, 7, 11, 13, 17  4.913734e-15          4          17         29          95.00           40.00           0.00    0 - 1 - 2     14.16           1, 1, 0, 0, 1, 0, 0, 0, 2, 1  1.578823e+00          0           1          2          95.00           50.00          10.00     1 - 5 - 8     60.42            6, 6, 6, 3, 3, 6, 4, 4, 1, 7  6.377746e-16          1           5          8          95.00           50.00           0.00  0 - 2 - 4     50.58   3, 1, 3, 2, 3, 1, 1, 3, 3, 3  1.189587e-08          0           2          4           95.0            70.0            0.0
6               Aaron Wiggins  OKC   1 - 20 - 38     34.40       35, 17, 3, 4, 8, 19, 11, 26, 9, 0  9.377899e-15          1          20         38          90.00           20.00           0.00    0 - 2 - 4     23.00           2, 3, 2, 1, 0, 1, 1, 6, 3, 1  1.290968e+00          0           2          4          95.00           50.00          10.00     0 - 4 - 7     53.02            7, 5, 4, 5, 3, 3, 2, 4, 4, 3  1.130394e-15          0           4          7          95.00           60.00          10.00  0 - 3 - 5     32.05   4, 1, 1, 0, 2, 3, 3, 4, 1, 0  2.023248e-13          0           3          5           95.0            40.0            0.0
7                Adam Flagler  OKC    0 - 7 - 15      6.00           17, 2, 0, 0, 0, 0, 0, 5, 5, 0  2.500000e-01          0           7         15          95.00           10.00          10.00    0 - 1 - 3     45.39           4, 0, 0, 0, 0, 0, 0, 4, 4, 0  1.732051e+00          0           1          3          95.00           30.00          30.00     0 - 1 - 4     11.88            6, 1, 0, 0, 2, 1, 0, 2, 4, 1  9.726665e-16          0           1          4          95.00           70.00          20.00  0 - 1 - 2      0.00   4, 0, 0, 0, 0, 0, 0, 1, 1, 0  2.319292e-01          0           1          2           95.0            30.0           10.0
8                   Adem Bona  PHI   0 - 10 - 23     33.79      18, 17, 16, 4, 28, 9, 14, 16, 6, 6  4.953221e-15          0          10         23          95.00           60.00          10.00    0 - 0 - 1     52.65           1, 0, 1, 2, 0, 2, 0, 1, 3, 1  1.259363e+00          0           0          1          95.00           95.00          70.00    0 - 6 - 13     42.17         6, 9, 11, 10, 6, 8, 8, 10, 6, 7  1.225803e-15          0           6         13          95.00           95.00           0.00  0 - 0 - 0    100.00   0, 0, 0, 0, 0, 0, 0, 0, 0, 0  0.000000e+00          0           0          0           95.0            95.0           95.0
9               Ajay Mitchell  OKC    0 - 7 - 16     33.36        9, 8, 11, 3, 17, 10, 9, 16, 2, 5  0.000000e+00          0           7         16          95.00           70.00          20.00    0 - 2 - 5      5.14           5, 0, 3, 0, 3, 4, 0, 2, 1, 2  4.040488e+00          0           2          5          95.00           60.00          10.00     0 - 1 - 6      2.66           0, 1, 2, 3, 1, 5, 1, 12, 3, 1  0.000000e+00          0           1          6          95.00           90.00          10.00  0 - 0 - 1      9.10   0, 0, 1, 0, 3, 1, 1, 2, 0, 1  5.886019e-01          0           0          1           95.0            95.0           60.0
10                 Al Horford  BOS   0 - 10 - 21     47.17      13, 11, 7, 26, 16, 14, 5, 4, 9, 18  4.991132e-16          0          10         21          95.00           60.00          10.00    0 - 2 - 5     23.16           0, 4, 2, 2, 5, 1, 2, 6, 5, 6  1.828844e+00          0           2          5          95.00           80.00          40.00    3 - 8 - 12     68.79        11, 10, 3, 8, 10, 6, 9, 5, 9, 10  2.070468e-15          3           8         12          95.00           70.00           0.00  0 - 2 - 5     25.38   3, 3, 1, 6, 2, 2, 1, 1, 1, 6  2.703892e-14          0           2          5           95.0            60.0           20.0
11                 Alec Burks  MIA    0 - 7 - 20     21.91     12, 7, 11, 24, 2, 10, 3, 20, 11, 17  2.986228e-15          0           7         20          95.00           80.00          20.00    0 - 1 - 3      2.62           3, 0, 2, 2, 1, 0, 2, 0, 2, 0  1.045768e+00          0           1          3          95.00           60.00          10.00     0 - 3 - 6     29.23            4, 2, 0, 5, 2, 2, 3, 3, 1, 2  1.304628e-15          0           3          6          95.00           40.00           0.00  0 - 3 - 6     15.25   4, 2, 3, 6, 0, 1, 1, 6, 3, 5  2.051482e-14          0           3          6           95.0            60.0           20.0
12                Alex Caruso  OKC   3 - 13 - 22     43.41         19, 9, 7, 2, 7, 6, 6, 15, 14, 9  6.547738e-16          3          13         22          90.00           30.00           0.00    0 - 3 - 6     29.23           3, 3, 2, 1, 3, 2, 1, 6, 5, 0  1.694675e+00          0           3          6          95.00           50.00          10.00     0 - 3 - 6     44.98            5, 4, 3, 4, 5, 5, 3, 5, 6, 3  0.000000e+00          0           3          6          95.00           95.00          10.00  0 - 2 - 3     23.90   2, 1, 1, 0, 1, 0, 2, 2, 2, 1  4.838991e-14          0           2          3           95.0            40.0            0.0
13                 Alex Ducas  OKC     0 - 1 - 5      0.00            2, 3, 3, 0, 0, 0, 3, 0, 0, 2  4.440892e-16          0           1          5          95.00           50.00           0.00    0 - 0 - 0      0.00           1, 0, 1, 0, 0, 0, 1, 0, 0, 0  3.377337e-01          0           0          0          95.00           95.00          95.00     0 - 1 - 4      0.00            2, 0, 4, 0, 0, 0, 2, 1, 2, 7  5.629858e-16          0           1          4          95.00           60.00          20.00  0 - 0 - 1      0.00   0, 1, 1, 0, 0, 0, 1, 0, 0, 0  1.918948e-01          0           0          1           95.0            95.0           30.0
14                   Alex Len  LAL     0 - 0 - 4      0.00           0, 10, 2, 2, 0, 0, 0, 0, 4, 0  1.174950e-15          0           0          4          95.00           95.00          20.00    0 - 1 - 2     31.02           0, 1, 1, 1, 2, 0, 0, 0, 2, 0  1.243399e+00          0           1          2          95.00           50.00          20.00     0 - 1 - 5     14.53            1, 9, 5, 3, 2, 0, 1, 1, 7, 0  1.574883e-15          0           1          5          95.00           80.00          30.00  0 - 0 - 0     31.18   0, 1, 0, 0, 0, 0, 0, 0, 0, 0  1.666667e-01          0           0          0           95.0            95.0           95.0
15                 Alex Reese  PHI     2 - 2 - 2    100.00          4, 3, 10, 2, 8, 11, 6, 6, 5, 2  4.259443e+00          2           2          2          95.00           95.00          95.00    1 - 1 - 1    100.00           0, 0, 1, 0, 1, 0, 0, 1, 0, 0  5.345225e-01          1           1          1          30.00           30.00          30.00     1 - 1 - 1    100.00            2, 2, 4, 6, 3, 5, 1, 2, 3, 3  3.139609e+00          1           1          1          95.00           95.00          95.00  0 - 0 - 0    100.00   1, 1, 2, 0, 1, 3, 2, 2, 1, 0  1.388730e+00          0           0          0           95.0            95.0           95.0
16                  Alex Sarr  WAS    0 - 9 - 22     57.01    7, 12, 20, 16, 10, 15, 8, 12, 22, 24  5.894186e-15          0           9         22          95.00           80.00          20.00    0 - 2 - 4     43.53           3, 3, 6, 2, 6, 1, 3, 1, 1, 2  1.702539e+00          0           2          4          95.00           70.00          20.00    0 - 4 - 10     51.48           3, 4, 12, 4, 6, 4, 3, 4, 7, 7  1.087792e-15          0           4         10          95.00           80.00          10.00  0 - 1 - 4     11.33   1, 0, 1, 2, 0, 3, 1, 0, 1, 4  5.532636e-10          0           1          4           95.0            70.0           10.0
17             Alperen Sengun  HOU   4 - 18 - 31     64.61   19, 31, 15, 14, 16, 33, 18, 17, 8, 22  6.194368e-15          4          18         31          95.00           50.00          20.00    0 - 5 - 9     56.90          4, 4, 9, 6, 3, 2, 5, 10, 2, 4  1.981096e+00          0           5          9          95.00           40.00          20.00   3 - 11 - 18     62.29      14, 2, 14, 7, 9, 10, 9, 14, 10, 12  8.331852e-16          3          11         18          90.00           40.00           0.00  0 - 0 - 0      0.00   0, 0, 0, 0, 0, 0, 0, 0, 0, 1  3.732154e-09          0           0          0           95.0            95.0           95.0
18              Amen Thompson  HOU   0 - 12 - 23     61.37   14, 16, 9, 20, 12, 15, 11, 18, 15, 21  3.249919e-15          0          12         23          95.00           80.00           0.00    0 - 4 - 9     50.61          6, 6, 5, 4, 9, 5, 1, 5, 11, 2  3.002344e+00          0           4          9          95.00           80.00          20.00    2 - 7 - 11     75.80         6, 8, 4, 5, 10, 10, 6, 9, 9, 11  1.003987e-15          2           7         11          95.00           60.00          10.00  0 - 0 - 1     69.14   0, 2, 0, 1, 0, 1, 1, 0, 0, 0  2.051811e-09          0           0          1           95.0            95.0           40.0
19                Amir Coffey  LAC    0 - 6 - 15     41.33          1, 5, 9, 6, 3, 9, 12, 13, 9, 2  2.467419e-14          0           6         15          95.00           60.00           0.00    0 - 0 - 2     15.48           0, 1, 0, 1, 1, 1, 3, 1, 1, 0  9.242395e-01          0           0          2          95.00           95.00          10.00     0 - 1 - 3     46.27            1, 1, 1, 2, 2, 3, 1, 2, 1, 0  3.715517e-16          0           1          3          95.00           90.00          10.00  0 - 1 - 2      5.31   0, 1, 0, 1, 1, 1, 2, 3, 1, 0  1.928361e-14          0           1          2           95.0            70.0           20.0
20             Andre Drummond  PHI    0 - 5 - 15     22.75         4, 6, 9, 4, 25, 10, 7, 10, 6, 8  1.144024e-15          0           5         15          95.00           80.00          10.00    0 - 0 - 2     49.84           1, 0, 2, 3, 1, 2, 5, 0, 0, 1  1.964185e+00          0           0          2          95.00           95.00          40.00    0 - 6 - 14     38.82         6, 2, 10, 7, 18, 14, 9, 8, 3, 7  4.638361e-16          0           6         14          95.00           80.00          20.00  0 - 0 - 0     31.18   0, 0, 1, 0, 1, 0, 0, 0, 0, 0  2.132007e-01          0           0          0           95.0            95.0           95.0
21          Andre Jackson Jr.  MIL     0 - 4 - 9      5.42            6, 0, 0, 0, 1, 0, 3, 2, 0, 0  1.754177e-15          0           4          9          95.00           10.00           0.00    0 - 1 - 2     21.35           0, 1, 0, 0, 1, 0, 1, 0, 0, 0  6.158824e-01          0           1          2          95.00           30.00           0.00     0 - 0 - 2      9.20            0, 3, 1, 0, 3, 0, 2, 2, 0, 1  4.030044e-16          0           0          2          95.00           95.00          40.00  0 - 0 - 0      0.00   0, 0, 0, 0, 0, 0, 0, 0, 0, 0  1.144233e-14          0           0          0           95.0            95.0           95.0
22            Andrew Nembhard  IND    0 - 4 - 14     46.61        2, 4, 19, 11, 9, 5, 16, 7, 16, 6  1.721926e-15          0           4         14          95.00           90.00          30.00    0 - 4 - 9     45.90           7, 4, 6, 3, 2, 2, 7, 8, 3, 5  2.763906e+00          0           4          9          95.00           60.00           0.00     0 - 2 - 5     48.05            1, 7, 4, 6, 2, 7, 5, 4, 7, 3  2.973329e-16          0           2          5          95.00           90.00          50.00  0 - 1 - 2     21.08   0, 0, 0, 0, 1, 1, 1, 1, 1, 0  6.726950e-15          0           1          2           95.0            50.0            0.0
23             Andrew Wiggins  MIA   0 - 15 - 31     58.34   10, 14, 16, 10, 42, 30, 8, 23, 22, 19  1.827856e-15          0          15         31          95.00           60.00          10.00    0 - 3 - 6     47.88           3, 5, 3, 5, 5, 3, 1, 3, 5, 2  1.911057e+00          0           3          6          95.00           80.00           0.00     0 - 5 - 9     51.63            5, 6, 5, 5, 3, 2, 0, 4, 3, 7  7.987799e-16          0           5          9          95.00           50.00           0.00  0 - 1 - 3     30.40   0, 3, 2, 2, 6, 2, 1, 3, 2, 1  3.643464e-09          0           1          3           95.0            90.0           30.0
24            Anfernee Simons  POR   0 - 16 - 33     57.72    15, 20, 7, 15, 22, 30, 22, 6, 32, 34  4.411187e-15          0          16         33          95.00           60.00          10.00    0 - 4 - 7     58.45           4, 5, 8, 5, 3, 2, 4, 5, 2, 1  1.940218e+00          0           4          7          95.00           60.00          10.00     0 - 2 - 4     50.31            3, 1, 1, 3, 5, 1, 1, 4, 2, 2  1.336666e-15          0           2          4          95.00           60.00          20.00  0 - 2 - 5     43.33   1, 3, 1, 3, 2, 5, 6, 2, 6, 4  7.494889e-15          0           2          5           95.0            80.0           30.0
25              Anthony Black  ORL   1 - 12 - 22     44.73        21, 6, 8, 6, 4, 8, 8, 14, 20, 17  8.706024e-15          1          12         22          95.00           40.00           0.00    0 - 3 - 6     30.45           7, 2, 2, 4, 3, 2, 2, 3, 0, 6  1.631570e+00          0           3          6          95.00           50.00          20.00     0 - 3 - 6     47.20            6, 5, 1, 3, 2, 1, 4, 3, 5, 5  7.251946e-16          0           3          6          95.00           70.00          10.00  0 - 0 - 2     54.74   0, 2, 1, 0, 0, 0, 1, 1, 2, 3  1.293482e-09          0           0          2           95.0            95.0           30.0
26              Anthony Davis  DAL   6 - 25 - 43     58.75   23, 13, 27, 34, 12, 18, 15, 12, 26, 4  6.793259e-15          6          25         43          90.00           30.00           0.00    0 - 3 - 7     34.76          10, 6, 0, 2, 5, 5, 2, 3, 7, 0  2.705774e+00          0           3          7          95.00           60.00          20.00   2 - 12 - 21     57.82        13, 11, 9, 15, 7, 7, 7, 6, 16, 2  2.808667e-15          2          12         21          95.00           30.00           0.00  0 - 0 - 1     65.23   1, 0, 1, 2, 0, 0, 1, 0, 2, 0  2.716277e-09          0           0          1           95.0            95.0           50.0
27            Anthony Edwards  MIN   4 - 24 - 43     63.49   9, 44, 25, 37, 28, 34, 25, 20, 17, 17  4.044942e-15          4          24         43          95.00           60.00          10.00    1 - 5 - 8     60.02           5, 3, 4, 2, 3, 8, 4, 5, 4, 5  3.173174e+00          1           5          8          95.00           40.00          10.00     0 - 3 - 8     43.21           4, 5, 7, 2, 5, 10, 6, 4, 2, 3  1.375429e-15          0           3          8          95.00           80.00          10.00  0 - 3 - 6     50.39   1, 7, 2, 6, 5, 5, 4, 4, 1, 3  1.568209e-09          0           3          6           95.0            70.0           20.0
28               Anthony Gill  WAS     0 - 1 - 7     36.92         0, 6, 4, 10, 2, 4, 10, 10, 7, 0  2.050642e-15          0           1          7          95.00           80.00          40.00    0 - 0 - 1     65.90           0, 1, 0, 1, 0, 0, 1, 2, 1, 0  7.447359e-01          0           0          1          95.00           95.00          50.00     0 - 1 - 4     48.10            4, 5, 5, 5, 1, 1, 5, 1, 4, 0  1.598892e-15          0           1          4          95.00           90.00          60.00  0 - 0 - 1     50.80   0, 0, 0, 2, 0, 0, 0, 1, 0, 0  2.615975e-09          0           0          1           95.0            95.0           20.0

In [574]:
import numpy as np

# Step 1: Parse the string
low_str, mean_str, high_str = player_prediction.split(" - ")
low = int(low_str)
mean = int(mean_str)
high = int(high_str) 



# Step 2: Estimate standard deviation from range
std_estimate = (high - low) / 2

# Step 3: Monte Carlo simulation
simulated_outcomes = np.random.normal(loc=mean, scale=std_estimate, size=100000)

# Step 4: Probability of exceeding a threshold, e.g., 20 points
threshold = 24
prob_over_threshold = np.mean(simulated_outcomes >= threshold)

print(f"Probability of scoring ≥ {threshold} points: {prob_over_threshold:.2%}")

NameError: name 'player_prediction' is not defined

In [351]:
import numpy as np
from scipy.stats import norm

def get_most_likely_score(player_prediction: str):
    low_str, mean_str, high_str = player_prediction.split(" - ")
    low, mean, high = int(low_str), int(mean_str), int(high_str)

    std = (high - low) / 2
    simulated = np.random.normal(loc=mean, scale=std, size=10000)
    
    # Round to nearest integer and count frequency
    values, counts = np.unique(simulated.round().astype(int), return_counts=True)
    most_likely_score = values[np.argmax(counts)]
    
    return most_likely_score

In [549]:
get_most_likely_score("16 - 27 - 38")  # Might return 18

27